// Mocks generated by Mockito 5.4.6 from annotations
// in xceleration/test/unit/coach/resolve_bib_number_screen/controller/resolve_bib_number_controller_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;
import 'dart:ui' as _i9;

import 'package:mockito/mockito.dart' as _i1;
import 'package:xceleration/shared/models/database/i_master_race_resolver.dart'
    as _i2;
import 'package:xceleration/shared/models/database/race_participant.dart'
    as _i6;
import 'package:xceleration/shared/models/database/race_runner.dart' as _i5;
import 'package:xceleration/shared/models/database/runner.dart' as _i7;
import 'package:xceleration/shared/models/database/team.dart' as _i4;
import 'package:xceleration/shared/models/database/team_participant.dart'
    as _i8;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [IMasterRaceResolver].
///
/// See the documentation for Mockito's code generation for more information.
class MockIMasterRaceResolver extends _i1.Mock
    implements _i2.IMasterRaceResolver {
  MockIMasterRaceResolver() {
    _i1.throwOnMissingStub(this);
  }

  @override
  int get raceId =>
      (super.noSuchMethod(Invocation.getter(#raceId), returnValue: 0) as int);

  @override
  _i3.Future<List<_i4.Team>> get teams =>
      (super.noSuchMethod(
            Invocation.getter(#teams),
            returnValue: _i3.Future<List<_i4.Team>>.value(<_i4.Team>[]),
          )
          as _i3.Future<List<_i4.Team>>);

  @override
  _i3.Future<List<_i5.RaceRunner>> get raceRunners =>
      (super.noSuchMethod(
            Invocation.getter(#raceRunners),
            returnValue: _i3.Future<List<_i5.RaceRunner>>.value(
              <_i5.RaceRunner>[],
            ),
          )
          as _i3.Future<List<_i5.RaceRunner>>);

  @override
  _i3.Future<List<_i6.RaceParticipant>> get raceParticipants =>
      (super.noSuchMethod(
            Invocation.getter(#raceParticipants),
            returnValue: _i3.Future<List<_i6.RaceParticipant>>.value(
              <_i6.RaceParticipant>[],
            ),
          )
          as _i3.Future<List<_i6.RaceParticipant>>);

  @override
  _i3.Future<Map<_i4.Team, List<_i5.RaceRunner>>> get filteredSearchResults =>
      (super.noSuchMethod(
            Invocation.getter(#filteredSearchResults),
            returnValue: _i3.Future<Map<_i4.Team, List<_i5.RaceRunner>>>.value(
              <_i4.Team, List<_i5.RaceRunner>>{},
            ),
          )
          as _i3.Future<Map<_i4.Team, List<_i5.RaceRunner>>>);

  @override
  _i3.Future<void> searchRaceRunners(
    String? query, [
    String? searchAttribute = 'all',
  ]) =>
      (super.noSuchMethod(
            Invocation.method(#searchRaceRunners, [query, searchAttribute]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<_i7.Runner?> getRunnerByBib(String? bibNumber) =>
      (super.noSuchMethod(
            Invocation.method(#getRunnerByBib, [bibNumber]),
            returnValue: _i3.Future<_i7.Runner?>.value(),
          )
          as _i3.Future<_i7.Runner?>);

  @override
  _i3.Future<int> createRunner(_i7.Runner? runner) =>
      (super.noSuchMethod(
            Invocation.method(#createRunner, [runner]),
            returnValue: _i3.Future<int>.value(0),
          )
          as _i3.Future<int>);

  @override
  _i3.Future<void> addRunnerToTeam(int? teamId, int? runnerId) =>
      (super.noSuchMethod(
            Invocation.method(#addRunnerToTeam, [teamId, runnerId]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<_i4.Team?> getTeamByName(String? teamName) =>
      (super.noSuchMethod(
            Invocation.method(#getTeamByName, [teamName]),
            returnValue: _i3.Future<_i4.Team?>.value(),
          )
          as _i3.Future<_i4.Team?>);

  @override
  _i3.Future<List<_i4.Team>> getOtherTeams() =>
      (super.noSuchMethod(
            Invocation.method(#getOtherTeams, []),
            returnValue: _i3.Future<List<_i4.Team>>.value(<_i4.Team>[]),
          )
          as _i3.Future<List<_i4.Team>>);

  @override
  _i3.Future<void> addRaceParticipant(_i6.RaceParticipant? raceParticipant) =>
      (super.noSuchMethod(
            Invocation.method(#addRaceParticipant, [raceParticipant]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> addRaceParticipantsBulk(
    List<_i6.RaceParticipant>? raceParticipants,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#addRaceParticipantsBulk, [raceParticipants]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> removeRaceParticipant(
    _i6.RaceParticipant? raceParticipant,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#removeRaceParticipant, [raceParticipant]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> updateRaceParticipant(
    _i6.RaceParticipant? raceParticipant,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateRaceParticipant, [raceParticipant]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> removeRaceRunner(_i5.RaceRunner? raceRunner) =>
      (super.noSuchMethod(
            Invocation.method(#removeRaceRunner, [raceRunner]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> addTeamParticipant(_i8.TeamParticipant? teamParticipant) =>
      (super.noSuchMethod(
            Invocation.method(#addTeamParticipant, [teamParticipant]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> removeTeamFromRace(_i8.TeamParticipant? teamParticipant) =>
      (super.noSuchMethod(
            Invocation.method(#removeTeamFromRace, [teamParticipant]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  void invalidateCache() => super.noSuchMethod(
    Invocation.method(#invalidateCache, []),
    returnValueForMissingStub: null,
  );

  @override
  void addListener(_i9.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i9.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );
}
