// Mocks generated by Mockito 5.4.6 from annotations
// in xceleration/test/unit/coach/resolve_bib_number_screen/controller/resolve_bib_number_controller_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;
import 'dart:ui' as _i8;

import 'package:mockito/mockito.dart' as _i1;
import 'package:xceleration/shared/models/database/i_master_race_resolver.dart'
    as _i2;
import 'package:xceleration/shared/models/database/race_participant.dart'
    as _i7;
import 'package:xceleration/shared/models/database/race_runner.dart' as _i5;
import 'package:xceleration/shared/models/database/runner.dart' as _i6;
import 'package:xceleration/shared/models/database/team.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [IMasterRaceResolver].
///
/// See the documentation for Mockito's code generation for more information.
class MockIMasterRaceResolver extends _i1.Mock
    implements _i2.IMasterRaceResolver {
  MockIMasterRaceResolver() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.Team>> get teams => (super.noSuchMethod(
        Invocation.getter(#teams),
        returnValue: _i3.Future<List<_i4.Team>>.value(<_i4.Team>[]),
      ) as _i3.Future<List<_i4.Team>>);

  @override
  _i3.Future<List<_i5.RaceRunner>> get raceRunners => (super.noSuchMethod(
        Invocation.getter(#raceRunners),
        returnValue: _i3.Future<List<_i5.RaceRunner>>.value(<_i5.RaceRunner>[]),
      ) as _i3.Future<List<_i5.RaceRunner>>);

  @override
  _i3.Future<Map<_i4.Team, List<_i5.RaceRunner>>> get filteredSearchResults =>
      (super.noSuchMethod(
        Invocation.getter(#filteredSearchResults),
        returnValue: _i3.Future<Map<_i4.Team, List<_i5.RaceRunner>>>.value(
            <_i4.Team, List<_i5.RaceRunner>>{}),
      ) as _i3.Future<Map<_i4.Team, List<_i5.RaceRunner>>>);

  @override
  _i3.Future<void> searchRaceRunners(String? query) => (super.noSuchMethod(
        Invocation.method(
          #searchRaceRunners,
          [query],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<_i6.Runner?> getRunnerByBib(String? bibNumber) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRunnerByBib,
          [bibNumber],
        ),
        returnValue: _i3.Future<_i6.Runner?>.value(),
      ) as _i3.Future<_i6.Runner?>);

  @override
  _i3.Future<int> createRunner(_i6.Runner? runner) => (super.noSuchMethod(
        Invocation.method(
          #createRunner,
          [runner],
        ),
        returnValue: _i3.Future<int>.value(0),
      ) as _i3.Future<int>);

  @override
  _i3.Future<void> addRunnerToTeam(
    int? teamId,
    int? runnerId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #addRunnerToTeam,
          [
            teamId,
            runnerId,
          ],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> addRaceParticipant(_i7.RaceParticipant? raceParticipant) =>
      (super.noSuchMethod(
        Invocation.method(
          #addRaceParticipant,
          [raceParticipant],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  void addListener(_i8.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i8.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );
}
