// Mocks generated by Mockito 5.4.6 from annotations
// in xceleration/test/unit/assistant/race_timer/controller/timing_controller_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;
import 'package:xceleration/assistant/shared/models/bib_record.dart' as _i10;
import 'package:xceleration/assistant/shared/models/race_record.dart' as _i5;
import 'package:xceleration/assistant/shared/models/runner.dart' as _i9;
import 'package:xceleration/assistant/shared/services/i_assistant_storage_service.dart'
    as _i2;
import 'package:xceleration/core/result.dart' as _i4;
import 'package:xceleration/shared/models/timing_records/timing_chunk.dart'
    as _i7;
import 'package:xceleration/shared/models/timing_records/timing_datum.dart'
    as _i8;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [IAssistantStorageService].
///
/// See the documentation for Mockito's code generation for more information.
class MockIAssistantStorageService extends _i1.Mock
    implements _i2.IAssistantStorageService {
  MockIAssistantStorageService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Result<void>> saveNewRace(_i5.RaceRecord? race) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveNewRace,
          [race],
        ),
        returnValue:
            _i3.Future<_i4.Result<void>>.value(_i6.dummyValue<_i4.Result<void>>(
          this,
          Invocation.method(
            #saveNewRace,
            [race],
          ),
        )),
      ) as _i3.Future<_i4.Result<void>>);

  @override
  _i3.Future<_i4.Result<void>> updateRace(_i5.RaceRecord? race) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateRace,
          [race],
        ),
        returnValue:
            _i3.Future<_i4.Result<void>>.value(_i6.dummyValue<_i4.Result<void>>(
          this,
          Invocation.method(
            #updateRace,
            [race],
          ),
        )),
      ) as _i3.Future<_i4.Result<void>>);

  @override
  _i3.Future<_i4.Result<void>> updateRaceDuration(
    int? raceId,
    String? type,
    Duration? time,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateRaceDuration,
          [
            raceId,
            type,
            time,
          ],
        ),
        returnValue:
            _i3.Future<_i4.Result<void>>.value(_i6.dummyValue<_i4.Result<void>>(
          this,
          Invocation.method(
            #updateRaceDuration,
            [
              raceId,
              type,
              time,
            ],
          ),
        )),
      ) as _i3.Future<_i4.Result<void>>);

  @override
  _i3.Future<_i4.Result<void>> updateRaceStartTime(
    int? raceId,
    String? type,
    DateTime? startedAt,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateRaceStartTime,
          [
            raceId,
            type,
            startedAt,
          ],
        ),
        returnValue:
            _i3.Future<_i4.Result<void>>.value(_i6.dummyValue<_i4.Result<void>>(
          this,
          Invocation.method(
            #updateRaceStartTime,
            [
              raceId,
              type,
              startedAt,
            ],
          ),
        )),
      ) as _i3.Future<_i4.Result<void>>);

  @override
  _i3.Future<_i4.Result<void>> updateRaceStatus(
    int? raceId,
    String? type,
    bool? stopped,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateRaceStatus,
          [
            raceId,
            type,
            stopped,
          ],
        ),
        returnValue:
            _i3.Future<_i4.Result<void>>.value(_i6.dummyValue<_i4.Result<void>>(
          this,
          Invocation.method(
            #updateRaceStatus,
            [
              raceId,
              type,
              stopped,
            ],
          ),
        )),
      ) as _i3.Future<_i4.Result<void>>);

  @override
  _i3.Future<_i4.Result<List<_i5.RaceRecord>>> getRecentRaces(
    String? type, {
    Duration? since,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRecentRaces,
          [type],
          {#since: since},
        ),
        returnValue: _i3.Future<_i4.Result<List<_i5.RaceRecord>>>.value(
            _i6.dummyValue<_i4.Result<List<_i5.RaceRecord>>>(
          this,
          Invocation.method(
            #getRecentRaces,
            [type],
            {#since: since},
          ),
        )),
      ) as _i3.Future<_i4.Result<List<_i5.RaceRecord>>>);

  @override
  _i3.Future<_i4.Result<List<_i5.RaceRecord>>> getRaces(String? type) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRaces,
          [type],
        ),
        returnValue: _i3.Future<_i4.Result<List<_i5.RaceRecord>>>.value(
            _i6.dummyValue<_i4.Result<List<_i5.RaceRecord>>>(
          this,
          Invocation.method(
            #getRaces,
            [type],
          ),
        )),
      ) as _i3.Future<_i4.Result<List<_i5.RaceRecord>>>);

  @override
  _i3.Future<_i4.Result<_i5.RaceRecord?>> getRace(
    int? raceId,
    String? type,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRace,
          [
            raceId,
            type,
          ],
        ),
        returnValue: _i3.Future<_i4.Result<_i5.RaceRecord?>>.value(
            _i6.dummyValue<_i4.Result<_i5.RaceRecord?>>(
          this,
          Invocation.method(
            #getRace,
            [
              raceId,
              type,
            ],
          ),
        )),
      ) as _i3.Future<_i4.Result<_i5.RaceRecord?>>);

  @override
  _i3.Future<_i4.Result<void>> deleteRace(
    int? raceId,
    String? type,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteRace,
          [
            raceId,
            type,
          ],
        ),
        returnValue:
            _i3.Future<_i4.Result<void>>.value(_i6.dummyValue<_i4.Result<void>>(
          this,
          Invocation.method(
            #deleteRace,
            [
              raceId,
              type,
            ],
          ),
        )),
      ) as _i3.Future<_i4.Result<void>>);

  @override
  _i3.Future<_i4.Result<void>> deleteOldRaces({Duration? olderThan}) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteOldRaces,
          [],
          {#olderThan: olderThan},
        ),
        returnValue:
            _i3.Future<_i4.Result<void>>.value(_i6.dummyValue<_i4.Result<void>>(
          this,
          Invocation.method(
            #deleteOldRaces,
            [],
            {#olderThan: olderThan},
          ),
        )),
      ) as _i3.Future<_i4.Result<void>>);

  @override
  _i3.Future<_i4.Result<void>> saveChunk(
    int? raceId,
    _i7.TimingChunk? chunk,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveChunk,
          [
            raceId,
            chunk,
          ],
        ),
        returnValue:
            _i3.Future<_i4.Result<void>>.value(_i6.dummyValue<_i4.Result<void>>(
          this,
          Invocation.method(
            #saveChunk,
            [
              raceId,
              chunk,
            ],
          ),
        )),
      ) as _i3.Future<_i4.Result<void>>);

  @override
  _i3.Future<_i4.Result<_i7.TimingChunk?>> getChunk(
    int? raceId,
    int? chunkId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getChunk,
          [
            raceId,
            chunkId,
          ],
        ),
        returnValue: _i3.Future<_i4.Result<_i7.TimingChunk?>>.value(
            _i6.dummyValue<_i4.Result<_i7.TimingChunk?>>(
          this,
          Invocation.method(
            #getChunk,
            [
              raceId,
              chunkId,
            ],
          ),
        )),
      ) as _i3.Future<_i4.Result<_i7.TimingChunk?>>);

  @override
  _i3.Future<_i4.Result<String?>> getChunkTimingData(
    int? raceId,
    int? chunkId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getChunkTimingData,
          [
            raceId,
            chunkId,
          ],
        ),
        returnValue: _i3.Future<_i4.Result<String?>>.value(
            _i6.dummyValue<_i4.Result<String?>>(
          this,
          Invocation.method(
            #getChunkTimingData,
            [
              raceId,
              chunkId,
            ],
          ),
        )),
      ) as _i3.Future<_i4.Result<String?>>);

  @override
  _i3.Future<_i4.Result<List<_i7.TimingChunk>>> getChunks(int? raceId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getChunks,
          [raceId],
        ),
        returnValue: _i3.Future<_i4.Result<List<_i7.TimingChunk>>>.value(
            _i6.dummyValue<_i4.Result<List<_i7.TimingChunk>>>(
          this,
          Invocation.method(
            #getChunks,
            [raceId],
          ),
        )),
      ) as _i3.Future<_i4.Result<List<_i7.TimingChunk>>>);

  @override
  _i3.Future<_i4.Result<void>> deleteChunk(
    int? raceId,
    int? chunkId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteChunk,
          [
            raceId,
            chunkId,
          ],
        ),
        returnValue:
            _i3.Future<_i4.Result<void>>.value(_i6.dummyValue<_i4.Result<void>>(
          this,
          Invocation.method(
            #deleteChunk,
            [
              raceId,
              chunkId,
            ],
          ),
        )),
      ) as _i3.Future<_i4.Result<void>>);

  @override
  _i3.Future<_i4.Result<void>> deleteChunks(int? raceId) => (super.noSuchMethod(
        Invocation.method(
          #deleteChunks,
          [raceId],
        ),
        returnValue:
            _i3.Future<_i4.Result<void>>.value(_i6.dummyValue<_i4.Result<void>>(
          this,
          Invocation.method(
            #deleteChunks,
            [raceId],
          ),
        )),
      ) as _i3.Future<_i4.Result<void>>);

  @override
  _i3.Future<_i4.Result<void>> saveChunkConflict(
    int? raceId,
    int? chunkId,
    _i8.TimingDatum? conflictRecord,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveChunkConflict,
          [
            raceId,
            chunkId,
            conflictRecord,
          ],
        ),
        returnValue:
            _i3.Future<_i4.Result<void>>.value(_i6.dummyValue<_i4.Result<void>>(
          this,
          Invocation.method(
            #saveChunkConflict,
            [
              raceId,
              chunkId,
              conflictRecord,
            ],
          ),
        )),
      ) as _i3.Future<_i4.Result<void>>);

  @override
  _i3.Future<_i4.Result<void>> updateChunkConflict(
    String? chunkId,
    _i8.TimingDatum? conflictRecord,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateChunkConflict,
          [
            chunkId,
            conflictRecord,
          ],
        ),
        returnValue:
            _i3.Future<_i4.Result<void>>.value(_i6.dummyValue<_i4.Result<void>>(
          this,
          Invocation.method(
            #updateChunkConflict,
            [
              chunkId,
              conflictRecord,
            ],
          ),
        )),
      ) as _i3.Future<_i4.Result<void>>);

  @override
  _i3.Future<_i4.Result<String?>> getChunkConflict(String? chunkId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getChunkConflict,
          [chunkId],
        ),
        returnValue: _i3.Future<_i4.Result<String?>>.value(
            _i6.dummyValue<_i4.Result<String?>>(
          this,
          Invocation.method(
            #getChunkConflict,
            [chunkId],
          ),
        )),
      ) as _i3.Future<_i4.Result<String?>>);

  @override
  _i3.Future<_i4.Result<void>> saveChunkTimingData(
    String? chunkId,
    List<String>? encodedRecords,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveChunkTimingData,
          [
            chunkId,
            encodedRecords,
          ],
        ),
        returnValue:
            _i3.Future<_i4.Result<void>>.value(_i6.dummyValue<_i4.Result<void>>(
          this,
          Invocation.method(
            #saveChunkTimingData,
            [
              chunkId,
              encodedRecords,
            ],
          ),
        )),
      ) as _i3.Future<_i4.Result<void>>);

  @override
  _i3.Future<_i4.Result<void>> updateChunkTimingData(
    int? raceId,
    int? chunkId,
    List<_i8.TimingDatum>? timingData,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateChunkTimingData,
          [
            raceId,
            chunkId,
            timingData,
          ],
        ),
        returnValue:
            _i3.Future<_i4.Result<void>>.value(_i6.dummyValue<_i4.Result<void>>(
          this,
          Invocation.method(
            #updateChunkTimingData,
            [
              raceId,
              chunkId,
              timingData,
            ],
          ),
        )),
      ) as _i3.Future<_i4.Result<void>>);

  @override
  _i3.Future<_i4.Result<void>> addLoggedTimingDatum(
    int? raceId,
    int? chunkId,
    _i8.TimingDatum? datum,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #addLoggedTimingDatum,
          [
            raceId,
            chunkId,
            datum,
          ],
        ),
        returnValue:
            _i3.Future<_i4.Result<void>>.value(_i6.dummyValue<_i4.Result<void>>(
          this,
          Invocation.method(
            #addLoggedTimingDatum,
            [
              raceId,
              chunkId,
              datum,
            ],
          ),
        )),
      ) as _i3.Future<_i4.Result<void>>);

  @override
  _i3.Future<_i4.Result<void>> saveRunner(_i9.Runner? runner) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveRunner,
          [runner],
        ),
        returnValue:
            _i3.Future<_i4.Result<void>>.value(_i6.dummyValue<_i4.Result<void>>(
          this,
          Invocation.method(
            #saveRunner,
            [runner],
          ),
        )),
      ) as _i3.Future<_i4.Result<void>>);

  @override
  _i3.Future<_i4.Result<void>> saveRunners(
    int? raceId,
    List<_i9.Runner>? runners,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveRunners,
          [
            raceId,
            runners,
          ],
        ),
        returnValue:
            _i3.Future<_i4.Result<void>>.value(_i6.dummyValue<_i4.Result<void>>(
          this,
          Invocation.method(
            #saveRunners,
            [
              raceId,
              runners,
            ],
          ),
        )),
      ) as _i3.Future<_i4.Result<void>>);

  @override
  _i3.Future<_i4.Result<_i9.Runner?>> getRunner(
    int? raceId,
    String? bibNumber,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRunner,
          [
            raceId,
            bibNumber,
          ],
        ),
        returnValue: _i3.Future<_i4.Result<_i9.Runner?>>.value(
            _i6.dummyValue<_i4.Result<_i9.Runner?>>(
          this,
          Invocation.method(
            #getRunner,
            [
              raceId,
              bibNumber,
            ],
          ),
        )),
      ) as _i3.Future<_i4.Result<_i9.Runner?>>);

  @override
  _i3.Future<_i4.Result<List<_i9.Runner>>> getRunners(int? raceId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRunners,
          [raceId],
        ),
        returnValue: _i3.Future<_i4.Result<List<_i9.Runner>>>.value(
            _i6.dummyValue<_i4.Result<List<_i9.Runner>>>(
          this,
          Invocation.method(
            #getRunners,
            [raceId],
          ),
        )),
      ) as _i3.Future<_i4.Result<List<_i9.Runner>>>);

  @override
  _i3.Future<_i4.Result<void>> updateRunner(_i9.Runner? runner) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateRunner,
          [runner],
        ),
        returnValue:
            _i3.Future<_i4.Result<void>>.value(_i6.dummyValue<_i4.Result<void>>(
          this,
          Invocation.method(
            #updateRunner,
            [runner],
          ),
        )),
      ) as _i3.Future<_i4.Result<void>>);

  @override
  _i3.Future<_i4.Result<void>> deleteRunner(
    int? raceId,
    String? bibNumber,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteRunner,
          [
            raceId,
            bibNumber,
          ],
        ),
        returnValue:
            _i3.Future<_i4.Result<void>>.value(_i6.dummyValue<_i4.Result<void>>(
          this,
          Invocation.method(
            #deleteRunner,
            [
              raceId,
              bibNumber,
            ],
          ),
        )),
      ) as _i3.Future<_i4.Result<void>>);

  @override
  _i3.Future<_i4.Result<void>> deleteRunners(int? raceId) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteRunners,
          [raceId],
        ),
        returnValue:
            _i3.Future<_i4.Result<void>>.value(_i6.dummyValue<_i4.Result<void>>(
          this,
          Invocation.method(
            #deleteRunners,
            [raceId],
          ),
        )),
      ) as _i3.Future<_i4.Result<void>>);

  @override
  _i3.Future<_i4.Result<void>> saveBibRecord(_i10.BibRecord? bibRecord) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveBibRecord,
          [bibRecord],
        ),
        returnValue:
            _i3.Future<_i4.Result<void>>.value(_i6.dummyValue<_i4.Result<void>>(
          this,
          Invocation.method(
            #saveBibRecord,
            [bibRecord],
          ),
        )),
      ) as _i3.Future<_i4.Result<void>>);

  @override
  _i3.Future<_i4.Result<void>> saveBibRecords(
    int? raceId,
    List<_i10.BibRecord>? bibRecords,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveBibRecords,
          [
            raceId,
            bibRecords,
          ],
        ),
        returnValue:
            _i3.Future<_i4.Result<void>>.value(_i6.dummyValue<_i4.Result<void>>(
          this,
          Invocation.method(
            #saveBibRecords,
            [
              raceId,
              bibRecords,
            ],
          ),
        )),
      ) as _i3.Future<_i4.Result<void>>);

  @override
  _i3.Future<_i4.Result<void>> addBibRecord(
    int? raceId,
    int? bibId,
    String? bibNumber,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #addBibRecord,
          [
            raceId,
            bibId,
            bibNumber,
          ],
        ),
        returnValue:
            _i3.Future<_i4.Result<void>>.value(_i6.dummyValue<_i4.Result<void>>(
          this,
          Invocation.method(
            #addBibRecord,
            [
              raceId,
              bibId,
              bibNumber,
            ],
          ),
        )),
      ) as _i3.Future<_i4.Result<void>>);

  @override
  _i3.Future<_i4.Result<void>> removeBibRecord(
    int? raceId,
    int? bibId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeBibRecord,
          [
            raceId,
            bibId,
          ],
        ),
        returnValue:
            _i3.Future<_i4.Result<void>>.value(_i6.dummyValue<_i4.Result<void>>(
          this,
          Invocation.method(
            #removeBibRecord,
            [
              raceId,
              bibId,
            ],
          ),
        )),
      ) as _i3.Future<_i4.Result<void>>);

  @override
  _i3.Future<_i4.Result<void>> updateBibRecordValue(
    int? raceId,
    int? bibId,
    String? bibNumber,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateBibRecordValue,
          [
            raceId,
            bibId,
            bibNumber,
          ],
        ),
        returnValue:
            _i3.Future<_i4.Result<void>>.value(_i6.dummyValue<_i4.Result<void>>(
          this,
          Invocation.method(
            #updateBibRecordValue,
            [
              raceId,
              bibId,
              bibNumber,
            ],
          ),
        )),
      ) as _i3.Future<_i4.Result<void>>);

  @override
  _i3.Future<_i4.Result<_i10.BibRecord?>> getBibRecord(
    int? raceId,
    int? bibId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getBibRecord,
          [
            raceId,
            bibId,
          ],
        ),
        returnValue: _i3.Future<_i4.Result<_i10.BibRecord?>>.value(
            _i6.dummyValue<_i4.Result<_i10.BibRecord?>>(
          this,
          Invocation.method(
            #getBibRecord,
            [
              raceId,
              bibId,
            ],
          ),
        )),
      ) as _i3.Future<_i4.Result<_i10.BibRecord?>>);

  @override
  _i3.Future<_i4.Result<List<_i10.BibRecord>>> getBibRecords(int? raceId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getBibRecords,
          [raceId],
        ),
        returnValue: _i3.Future<_i4.Result<List<_i10.BibRecord>>>.value(
            _i6.dummyValue<_i4.Result<List<_i10.BibRecord>>>(
          this,
          Invocation.method(
            #getBibRecords,
            [raceId],
          ),
        )),
      ) as _i3.Future<_i4.Result<List<_i10.BibRecord>>>);

  @override
  _i3.Future<_i4.Result<void>> updateBibRecord(_i10.BibRecord? bibRecord) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateBibRecord,
          [bibRecord],
        ),
        returnValue:
            _i3.Future<_i4.Result<void>>.value(_i6.dummyValue<_i4.Result<void>>(
          this,
          Invocation.method(
            #updateBibRecord,
            [bibRecord],
          ),
        )),
      ) as _i3.Future<_i4.Result<void>>);

  @override
  _i3.Future<_i4.Result<void>> deleteBibRecord(
    int? raceId,
    int? bibId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteBibRecord,
          [
            raceId,
            bibId,
          ],
        ),
        returnValue:
            _i3.Future<_i4.Result<void>>.value(_i6.dummyValue<_i4.Result<void>>(
          this,
          Invocation.method(
            #deleteBibRecord,
            [
              raceId,
              bibId,
            ],
          ),
        )),
      ) as _i3.Future<_i4.Result<void>>);

  @override
  _i3.Future<_i4.Result<void>> deleteBibRecords(int? raceId) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteBibRecords,
          [raceId],
        ),
        returnValue:
            _i3.Future<_i4.Result<void>>.value(_i6.dummyValue<_i4.Result<void>>(
          this,
          Invocation.method(
            #deleteBibRecords,
            [raceId],
          ),
        )),
      ) as _i3.Future<_i4.Result<void>>);

  @override
  _i3.Future<_i4.Result<int>> getNextBibId(int? raceId) => (super.noSuchMethod(
        Invocation.method(
          #getNextBibId,
          [raceId],
        ),
        returnValue:
            _i3.Future<_i4.Result<int>>.value(_i6.dummyValue<_i4.Result<int>>(
          this,
          Invocation.method(
            #getNextBibId,
            [raceId],
          ),
        )),
      ) as _i3.Future<_i4.Result<int>>);
}
