// Mocks generated by Mockito 5.4.6 from annotations
// in xceleration/test/unit/assistant/bib_number_recorder/services/voice_recognition_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i5;
import 'package:xceleration/assistant/bib_number_recorder/services/i_bib_audio_recorder.dart'
    as _i2;
import 'package:xceleration/assistant/bib_number_recorder/services/i_model_download_service.dart'
    as _i6;
import 'package:xceleration/assistant/bib_number_recorder/services/i_speech_recognition_service.dart'
    as _i8;
import 'package:xceleration/assistant/bib_number_recorder/services/model_assets.dart'
    as _i7;
import 'package:xceleration/core/result.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [IBibAudioRecorder].
///
/// See the documentation for Mockito's code generation for more information.
class MockIBibAudioRecorder extends _i1.Mock implements _i2.IBibAudioRecorder {
  MockIBibAudioRecorder() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Result<void>> open() =>
      (super.noSuchMethod(
            Invocation.method(#open, []),
            returnValue: _i3.Future<_i4.Result<void>>.value(
              _i5.dummyValue<_i4.Result<void>>(
                this,
                Invocation.method(#open, []),
              ),
            ),
          )
          as _i3.Future<_i4.Result<void>>);

  @override
  _i3.Future<void> start() =>
      (super.noSuchMethod(
            Invocation.method(#start, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<String?> stop() =>
      (super.noSuchMethod(
            Invocation.method(#stop, []),
            returnValue: _i3.Future<String?>.value(),
          )
          as _i3.Future<String?>);

  @override
  _i3.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}

/// A class which mocks [IModelDownloadService].
///
/// See the documentation for Mockito's code generation for more information.
class MockIModelDownloadService extends _i1.Mock
    implements _i6.IModelDownloadService {
  MockIModelDownloadService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Result<_i7.ModelAssets>> ensureModelReady() =>
      (super.noSuchMethod(
            Invocation.method(#ensureModelReady, []),
            returnValue: _i3.Future<_i4.Result<_i7.ModelAssets>>.value(
              _i5.dummyValue<_i4.Result<_i7.ModelAssets>>(
                this,
                Invocation.method(#ensureModelReady, []),
              ),
            ),
          )
          as _i3.Future<_i4.Result<_i7.ModelAssets>>);
}

/// A class which mocks [ISpeechRecognitionService].
///
/// See the documentation for Mockito's code generation for more information.
class MockISpeechRecognitionService extends _i1.Mock
    implements _i8.ISpeechRecognitionService {
  MockISpeechRecognitionService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> initialize(_i7.ModelAssets? assets) =>
      (super.noSuchMethod(
            Invocation.method(#initialize, [assets]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<String> transcribe(String? wavPath) =>
      (super.noSuchMethod(
            Invocation.method(#transcribe, [wavPath]),
            returnValue: _i3.Future<String>.value(
              _i5.dummyValue<String>(
                this,
                Invocation.method(#transcribe, [wavPath]),
              ),
            ),
          )
          as _i3.Future<String>);

  @override
  _i3.Future<void> dispose() =>
      (super.noSuchMethod(
            Invocation.method(#dispose, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}
