// Mocks generated by Mockito 5.4.6 from annotations
// in xceleration/test/unit/core/data_protocol_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:flutter_nearby_connections/flutter_nearby_connections.dart'
    as _i6;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i5;
import 'package:xceleration/core/result.dart' as _i4;
import 'package:xceleration/core/utils/connection_interfaces.dart' as _i2;
import 'package:xceleration/core/utils/data_package.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [DeviceConnectionServiceInterface].
///
/// See the documentation for Mockito's code generation for more information.
class MockDeviceConnectionServiceInterface extends _i1.Mock
    implements _i2.DeviceConnectionServiceInterface {
  MockDeviceConnectionServiceInterface() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isActive => (super.noSuchMethod(
        Invocation.getter(#isActive),
        returnValue: false,
      ) as bool);

  @override
  _i3.Future<_i4.Result<bool>> init() => (super.noSuchMethod(
        Invocation.method(
          #init,
          [],
        ),
        returnValue:
            _i3.Future<_i4.Result<bool>>.value(_i5.dummyValue<_i4.Result<bool>>(
          this,
          Invocation.method(
            #init,
            [],
          ),
        )),
      ) as _i3.Future<_i4.Result<bool>>);

  @override
  _i3.Future<void> monitorDevicesConnectionStatus({
    _i3.Future<void> Function(_i6.Device)? deviceFoundCallback,
    _i3.Future<void> Function(_i6.Device)? deviceConnectingCallback,
    _i3.Future<void> Function(_i6.Device)? deviceConnectedCallback,
    Duration? timeout = const Duration(seconds: 60),
    _i3.Future<void> Function()? timeoutCallback,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #monitorDevicesConnectionStatus,
          [],
          {
            #deviceFoundCallback: deviceFoundCallback,
            #deviceConnectingCallback: deviceConnectingCallback,
            #deviceConnectedCallback: deviceConnectedCallback,
            #timeout: timeout,
            #timeoutCallback: timeoutCallback,
          },
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<bool> sendMessageToDevice(
    _i6.Device? device,
    _i7.Package? package,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #sendMessageToDevice,
          [
            device,
            package,
          ],
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);

  @override
  _i3.Future<String?> monitorMessageReceives(
    _i6.Device? device, {
    required dynamic Function(
      _i7.Package,
      String,
    )? messageReceivedCallback,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #monitorMessageReceives,
          [device],
          {#messageReceivedCallback: messageReceivedCallback},
        ),
        returnValue: _i3.Future<String?>.value(),
      ) as _i3.Future<String?>);

  @override
  void stopMessageMonitoring(String? token) => super.noSuchMethod(
        Invocation.method(
          #stopMessageMonitoring,
          [token],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i3.Future<bool> inviteDevice(_i6.Device? device) => (super.noSuchMethod(
        Invocation.method(
          #inviteDevice,
          [device],
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);

  @override
  _i3.Future<_i4.Result<bool>> checkIfNearbyConnectionsWorks(
          {Duration? timeout = const Duration(seconds: 5)}) =>
      (super.noSuchMethod(
        Invocation.method(
          #checkIfNearbyConnectionsWorks,
          [],
          {#timeout: timeout},
        ),
        returnValue:
            _i3.Future<_i4.Result<bool>>.value(_i5.dummyValue<_i4.Result<bool>>(
          this,
          Invocation.method(
            #checkIfNearbyConnectionsWorks,
            [],
            {#timeout: timeout},
          ),
        )),
      ) as _i3.Future<_i4.Result<bool>>);

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
