name: xceleration
description: "Professional race timing and management application"
publish_to: "none"
version: 1.0.1+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  # Core UI & State Management
  provider: ^6.0.0
  flutter_portal: ^1.1.4
  cupertino_icons: ^1.0.2

  # File & Data Processing
  file_picker: ^8.1.4
  csv: ^5.0.2
  excel: ^2.0.3
  path_provider: ^2.0.15
  path: ^1.8.3

  # Database & Storage
  sqflite: ^2.2.8+4
  shared_preferences: ^2.2.2

  # Networking & APIs
  http: ^1.2.0
  googleapis: ^11.0.0
  google_sign_in: ^6.1.6

  # Utilities & Formatting
  intl: ^0.18.0
  crypto: ^3.0.3
  collection: ^1.17.0

  # Device Features
  flutter_nearby_connections: ^1.1.2
  audioplayers: ^6.1.0
  share_plus: ^11.0.0
  url_launcher: ^6.1.10
  geolocator: ^13.0.2
  geocoding: ^2.1.1
  permission_handler: ^11.1.0

  # UI Components & Widgets
  flutter_svg: ^2.0.9
  flutter_slidable: ^3.0.1
  flutter_colorpicker: ^1.0.3
  flutter_spinkit: ^5.2.1

  # QR & Barcode
  qr_flutter: ^4.1.0
  barcode_scan2: ^4.1.0

  # Document Generation
  pdf: ^3.10.7

  # Web & External Content
  webview_flutter: ^4.13.0

  # User Feedback & Notifications
  fluttertoast: ^8.2.12

  # Monitoring & Analytics
  sentry_flutter: ^8.14.2
  package_info_plus: ^8.3.0

  # Configuration
  flutter_dotenv: ^5.1.0

  # App Lifecycle
  flutter_native_splash: ^2.4.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.2
  flutter_lints: ^5.0.0
  mockito: ^5.4.4
  build_runner: ^2.4.8

flutter_native_splash:
  color: "#E2572B"
  image: "assets/icon/XCeleration_text.png"

  android_12:
    image: assets/icon/XCeleration_text.png
    icon_background_color: "#E2572B"

  android_gravity: center
  ios_content_mode: center
  fullscreen: true

  android: true
  ios: true
  web: false

flutter:
  uses-material-design: true

  assets:
    - assets/icon/
    - assets/sounds/click.mp3
    - assets/sounds/completed_ding.mp3
    - assets/sample_sheets/
    - .env

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/XCeleration_icon.png"
  macos:
    generate: true
    image_path: "assets/icon/XCeleration_icon.png"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/XCeleration_icon.png"
  min_sdk_android: 21
  remove_alpha_ios: true
