// Mocks generated by Mockito 5.4.6 from annotations
// in xceleration/test/widget/assistant/finish_line_roles/fixer/fixer_screen_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;
import 'dart:ui' as _i7;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i5;
import 'package:xceleration/assistant/finish_line_roles/fixer/controller/fixer_controller.dart'
    as _i2;
import 'package:xceleration/assistant/finish_line_roles/shared/models/fixer_entry.dart'
    as _i3;
import 'package:xceleration/assistant/shared/models/runner.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [FixerController].
///
/// See the documentation for Mockito's code generation for more information.
class MockFixerController extends _i1.Mock implements _i2.FixerController {
  MockFixerController() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<_i3.FixerEntry> get queue => (super.noSuchMethod(
        Invocation.getter(#queue),
        returnValue: <_i3.FixerEntry>[],
      ) as List<_i3.FixerEntry>);

  @override
  List<_i4.Runner> get searchResults => (super.noSuchMethod(
        Invocation.getter(#searchResults),
        returnValue: <_i4.Runner>[],
      ) as List<_i4.Runner>);

  @override
  String get searchQuery => (super.noSuchMethod(
        Invocation.getter(#searchQuery),
        returnValue: _i5.dummyValue<String>(
          this,
          Invocation.getter(#searchQuery),
        ),
      ) as String);

  @override
  int get unresolvedCount => (super.noSuchMethod(
        Invocation.getter(#unresolvedCount),
        returnValue: 0,
      ) as int);

  @override
  bool get isInRace => (super.noSuchMethod(
        Invocation.getter(#isInRace),
        returnValue: false,
      ) as bool);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  void initialize() => super.noSuchMethod(
        Invocation.method(
          #initialize,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i6.Future<void> joinRace() => (super.noSuchMethod(
        Invocation.method(
          #joinRace,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  void leaveRace() => super.noSuchMethod(
        Invocation.method(
          #leaveRace,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void search(String? query) => super.noSuchMethod(
        Invocation.method(
          #search,
          [query],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void clearSearch() => super.noSuchMethod(
        Invocation.method(
          #clearSearch,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void resolveWithRunner(
    int? entryId,
    _i4.Runner? runner,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #resolveWithRunner,
          [
            entryId,
            runner,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void resolveWithBib(
    int? entryId,
    int? newBib,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #resolveWithBib,
          [
            entryId,
            newBib,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void resolveAsNewRunner(
    int? entryId, {
    String? name,
    int? newBib,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #resolveAsNewRunner,
          [entryId],
          {
            #name: name,
            #newBib: newBib,
          },
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addListener(_i7.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i7.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
