// Mocks generated by Mockito 5.4.6 from annotations
// in xceleration/test/unit/assistant/finish_line_roles/fixer/controller/fixer_controller_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i9;
import 'package:xceleration/assistant/finish_line_roles/shared/models/fixer_entry.dart'
    as _i15;
import 'package:xceleration/assistant/finish_line_roles/shared/models/verifier_entry.dart'
    as _i14;
import 'package:xceleration/assistant/finish_line_roles/shared/peer_connection/messages/messages.dart'
    as _i5;
import 'package:xceleration/assistant/finish_line_roles/shared/peer_connection/p2p_session_service.dart'
    as _i2;
import 'package:xceleration/assistant/shared/models/bib_record.dart' as _i13;
import 'package:xceleration/assistant/shared/models/race_record.dart' as _i8;
import 'package:xceleration/assistant/shared/models/runner.dart' as _i12;
import 'package:xceleration/assistant/shared/services/i_assistant_storage_service.dart'
    as _i6;
import 'package:xceleration/core/result.dart' as _i7;
import 'package:xceleration/core/services/haptic_feedback_service.dart' as _i16;
import 'package:xceleration/shared/models/timing_records/timing_chunk.dart'
    as _i10;
import 'package:xceleration/shared/models/timing_records/timing_datum.dart'
    as _i11;
import 'package:xceleration/shared/role_bar/models/role_enums.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [P2PSessionService].
///
/// See the documentation for Mockito's code generation for more information.
class MockP2PSessionService extends _i1.Mock implements _i2.P2PSessionService {
  MockP2PSessionService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Role get localRole => (super.noSuchMethod(
        Invocation.getter(#localRole),
        returnValue: _i3.Role.timer,
      ) as _i3.Role);

  @override
  int get raceId => (super.noSuchMethod(
        Invocation.getter(#raceId),
        returnValue: 0,
      ) as int);

  @override
  _i4.Stream<(_i3.Role, _i5.MessageEnvelope)> get incomingMessages =>
      (super.noSuchMethod(
        Invocation.getter(#incomingMessages),
        returnValue: _i4.Stream<(_i3.Role, _i5.MessageEnvelope)>.empty(),
      ) as _i4.Stream<(_i3.Role, _i5.MessageEnvelope)>);

  @override
  _i4.Stream<_i2.PeerStateEvent> get peerStateEvents => (super.noSuchMethod(
        Invocation.getter(#peerStateEvents),
        returnValue: _i4.Stream<_i2.PeerStateEvent>.empty(),
      ) as _i4.Stream<_i2.PeerStateEvent>);

  @override
  _i4.Future<void> init() => (super.noSuchMethod(
        Invocation.method(
          #init,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> sendMessage(
    _i3.Role? target,
    _i5.MessageEnvelope? msg,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #sendMessage,
          [
            target,
            msg,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  int pendingCount(_i3.Role? peer) => (super.noSuchMethod(
        Invocation.method(
          #pendingCount,
          [peer],
        ),
        returnValue: 0,
      ) as int);

  @override
  _i4.Future<void> clearPersistedSequence() => (super.noSuchMethod(
        Invocation.method(
          #clearPersistedSequence,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> dispose() => (super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}

/// A class which mocks [IAssistantStorageService].
///
/// See the documentation for Mockito's code generation for more information.
class MockIAssistantStorageService extends _i1.Mock
    implements _i6.IAssistantStorageService {
  MockIAssistantStorageService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i7.Result<void>> saveNewRace(_i8.RaceRecord? race) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveNewRace,
          [race],
        ),
        returnValue:
            _i4.Future<_i7.Result<void>>.value(_i9.dummyValue<_i7.Result<void>>(
          this,
          Invocation.method(
            #saveNewRace,
            [race],
          ),
        )),
      ) as _i4.Future<_i7.Result<void>>);

  @override
  _i4.Future<_i7.Result<void>> updateRace(_i8.RaceRecord? race) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateRace,
          [race],
        ),
        returnValue:
            _i4.Future<_i7.Result<void>>.value(_i9.dummyValue<_i7.Result<void>>(
          this,
          Invocation.method(
            #updateRace,
            [race],
          ),
        )),
      ) as _i4.Future<_i7.Result<void>>);

  @override
  _i4.Future<_i7.Result<void>> updateRaceDuration(
    int? raceId,
    String? type,
    Duration? time,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateRaceDuration,
          [
            raceId,
            type,
            time,
          ],
        ),
        returnValue:
            _i4.Future<_i7.Result<void>>.value(_i9.dummyValue<_i7.Result<void>>(
          this,
          Invocation.method(
            #updateRaceDuration,
            [
              raceId,
              type,
              time,
            ],
          ),
        )),
      ) as _i4.Future<_i7.Result<void>>);

  @override
  _i4.Future<_i7.Result<void>> updateRaceStartTime(
    int? raceId,
    String? type,
    DateTime? startedAt,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateRaceStartTime,
          [
            raceId,
            type,
            startedAt,
          ],
        ),
        returnValue:
            _i4.Future<_i7.Result<void>>.value(_i9.dummyValue<_i7.Result<void>>(
          this,
          Invocation.method(
            #updateRaceStartTime,
            [
              raceId,
              type,
              startedAt,
            ],
          ),
        )),
      ) as _i4.Future<_i7.Result<void>>);

  @override
  _i4.Future<_i7.Result<void>> updateRaceStatus(
    int? raceId,
    String? type,
    bool? stopped,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateRaceStatus,
          [
            raceId,
            type,
            stopped,
          ],
        ),
        returnValue:
            _i4.Future<_i7.Result<void>>.value(_i9.dummyValue<_i7.Result<void>>(
          this,
          Invocation.method(
            #updateRaceStatus,
            [
              raceId,
              type,
              stopped,
            ],
          ),
        )),
      ) as _i4.Future<_i7.Result<void>>);

  @override
  _i4.Future<_i7.Result<List<_i8.RaceRecord>>> getRecentRaces(
    String? type, {
    Duration? since,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRecentRaces,
          [type],
          {#since: since},
        ),
        returnValue: _i4.Future<_i7.Result<List<_i8.RaceRecord>>>.value(
            _i9.dummyValue<_i7.Result<List<_i8.RaceRecord>>>(
          this,
          Invocation.method(
            #getRecentRaces,
            [type],
            {#since: since},
          ),
        )),
      ) as _i4.Future<_i7.Result<List<_i8.RaceRecord>>>);

  @override
  _i4.Future<_i7.Result<List<_i8.RaceRecord>>> getRaces(String? type) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRaces,
          [type],
        ),
        returnValue: _i4.Future<_i7.Result<List<_i8.RaceRecord>>>.value(
            _i9.dummyValue<_i7.Result<List<_i8.RaceRecord>>>(
          this,
          Invocation.method(
            #getRaces,
            [type],
          ),
        )),
      ) as _i4.Future<_i7.Result<List<_i8.RaceRecord>>>);

  @override
  _i4.Future<_i7.Result<_i8.RaceRecord?>> getRace(
    int? raceId,
    String? type,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRace,
          [
            raceId,
            type,
          ],
        ),
        returnValue: _i4.Future<_i7.Result<_i8.RaceRecord?>>.value(
            _i9.dummyValue<_i7.Result<_i8.RaceRecord?>>(
          this,
          Invocation.method(
            #getRace,
            [
              raceId,
              type,
            ],
          ),
        )),
      ) as _i4.Future<_i7.Result<_i8.RaceRecord?>>);

  @override
  _i4.Future<_i7.Result<void>> deleteRace(
    int? raceId,
    String? type,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteRace,
          [
            raceId,
            type,
          ],
        ),
        returnValue:
            _i4.Future<_i7.Result<void>>.value(_i9.dummyValue<_i7.Result<void>>(
          this,
          Invocation.method(
            #deleteRace,
            [
              raceId,
              type,
            ],
          ),
        )),
      ) as _i4.Future<_i7.Result<void>>);

  @override
  _i4.Future<_i7.Result<void>> deleteOldRaces({Duration? olderThan}) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteOldRaces,
          [],
          {#olderThan: olderThan},
        ),
        returnValue:
            _i4.Future<_i7.Result<void>>.value(_i9.dummyValue<_i7.Result<void>>(
          this,
          Invocation.method(
            #deleteOldRaces,
            [],
            {#olderThan: olderThan},
          ),
        )),
      ) as _i4.Future<_i7.Result<void>>);

  @override
  _i4.Future<_i7.Result<void>> saveChunk(
    int? raceId,
    _i10.TimingChunk? chunk,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveChunk,
          [
            raceId,
            chunk,
          ],
        ),
        returnValue:
            _i4.Future<_i7.Result<void>>.value(_i9.dummyValue<_i7.Result<void>>(
          this,
          Invocation.method(
            #saveChunk,
            [
              raceId,
              chunk,
            ],
          ),
        )),
      ) as _i4.Future<_i7.Result<void>>);

  @override
  _i4.Future<_i7.Result<_i10.TimingChunk?>> getChunk(
    int? raceId,
    int? chunkId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getChunk,
          [
            raceId,
            chunkId,
          ],
        ),
        returnValue: _i4.Future<_i7.Result<_i10.TimingChunk?>>.value(
            _i9.dummyValue<_i7.Result<_i10.TimingChunk?>>(
          this,
          Invocation.method(
            #getChunk,
            [
              raceId,
              chunkId,
            ],
          ),
        )),
      ) as _i4.Future<_i7.Result<_i10.TimingChunk?>>);

  @override
  _i4.Future<_i7.Result<String?>> getChunkTimingData(
    int? raceId,
    int? chunkId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getChunkTimingData,
          [
            raceId,
            chunkId,
          ],
        ),
        returnValue: _i4.Future<_i7.Result<String?>>.value(
            _i9.dummyValue<_i7.Result<String?>>(
          this,
          Invocation.method(
            #getChunkTimingData,
            [
              raceId,
              chunkId,
            ],
          ),
        )),
      ) as _i4.Future<_i7.Result<String?>>);

  @override
  _i4.Future<_i7.Result<List<_i10.TimingChunk>>> getChunks(int? raceId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getChunks,
          [raceId],
        ),
        returnValue: _i4.Future<_i7.Result<List<_i10.TimingChunk>>>.value(
            _i9.dummyValue<_i7.Result<List<_i10.TimingChunk>>>(
          this,
          Invocation.method(
            #getChunks,
            [raceId],
          ),
        )),
      ) as _i4.Future<_i7.Result<List<_i10.TimingChunk>>>);

  @override
  _i4.Future<_i7.Result<void>> deleteChunk(
    int? raceId,
    int? chunkId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteChunk,
          [
            raceId,
            chunkId,
          ],
        ),
        returnValue:
            _i4.Future<_i7.Result<void>>.value(_i9.dummyValue<_i7.Result<void>>(
          this,
          Invocation.method(
            #deleteChunk,
            [
              raceId,
              chunkId,
            ],
          ),
        )),
      ) as _i4.Future<_i7.Result<void>>);

  @override
  _i4.Future<_i7.Result<void>> deleteChunks(int? raceId) => (super.noSuchMethod(
        Invocation.method(
          #deleteChunks,
          [raceId],
        ),
        returnValue:
            _i4.Future<_i7.Result<void>>.value(_i9.dummyValue<_i7.Result<void>>(
          this,
          Invocation.method(
            #deleteChunks,
            [raceId],
          ),
        )),
      ) as _i4.Future<_i7.Result<void>>);

  @override
  _i4.Future<_i7.Result<void>> saveChunkConflict(
    int? raceId,
    int? chunkId,
    _i11.TimingDatum? conflictRecord,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveChunkConflict,
          [
            raceId,
            chunkId,
            conflictRecord,
          ],
        ),
        returnValue:
            _i4.Future<_i7.Result<void>>.value(_i9.dummyValue<_i7.Result<void>>(
          this,
          Invocation.method(
            #saveChunkConflict,
            [
              raceId,
              chunkId,
              conflictRecord,
            ],
          ),
        )),
      ) as _i4.Future<_i7.Result<void>>);

  @override
  _i4.Future<_i7.Result<void>> updateChunkConflict(
    String? chunkId,
    _i11.TimingDatum? conflictRecord,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateChunkConflict,
          [
            chunkId,
            conflictRecord,
          ],
        ),
        returnValue:
            _i4.Future<_i7.Result<void>>.value(_i9.dummyValue<_i7.Result<void>>(
          this,
          Invocation.method(
            #updateChunkConflict,
            [
              chunkId,
              conflictRecord,
            ],
          ),
        )),
      ) as _i4.Future<_i7.Result<void>>);

  @override
  _i4.Future<_i7.Result<String?>> getChunkConflict(String? chunkId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getChunkConflict,
          [chunkId],
        ),
        returnValue: _i4.Future<_i7.Result<String?>>.value(
            _i9.dummyValue<_i7.Result<String?>>(
          this,
          Invocation.method(
            #getChunkConflict,
            [chunkId],
          ),
        )),
      ) as _i4.Future<_i7.Result<String?>>);

  @override
  _i4.Future<_i7.Result<void>> saveChunkTimingData(
    String? chunkId,
    List<String>? encodedRecords,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveChunkTimingData,
          [
            chunkId,
            encodedRecords,
          ],
        ),
        returnValue:
            _i4.Future<_i7.Result<void>>.value(_i9.dummyValue<_i7.Result<void>>(
          this,
          Invocation.method(
            #saveChunkTimingData,
            [
              chunkId,
              encodedRecords,
            ],
          ),
        )),
      ) as _i4.Future<_i7.Result<void>>);

  @override
  _i4.Future<_i7.Result<void>> updateChunkTimingData(
    int? raceId,
    int? chunkId,
    List<_i11.TimingDatum>? timingData,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateChunkTimingData,
          [
            raceId,
            chunkId,
            timingData,
          ],
        ),
        returnValue:
            _i4.Future<_i7.Result<void>>.value(_i9.dummyValue<_i7.Result<void>>(
          this,
          Invocation.method(
            #updateChunkTimingData,
            [
              raceId,
              chunkId,
              timingData,
            ],
          ),
        )),
      ) as _i4.Future<_i7.Result<void>>);

  @override
  _i4.Future<_i7.Result<void>> addLoggedTimingDatum(
    int? raceId,
    int? chunkId,
    _i11.TimingDatum? datum,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #addLoggedTimingDatum,
          [
            raceId,
            chunkId,
            datum,
          ],
        ),
        returnValue:
            _i4.Future<_i7.Result<void>>.value(_i9.dummyValue<_i7.Result<void>>(
          this,
          Invocation.method(
            #addLoggedTimingDatum,
            [
              raceId,
              chunkId,
              datum,
            ],
          ),
        )),
      ) as _i4.Future<_i7.Result<void>>);

  @override
  _i4.Future<_i7.Result<void>> saveRunner(_i12.Runner? runner) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveRunner,
          [runner],
        ),
        returnValue:
            _i4.Future<_i7.Result<void>>.value(_i9.dummyValue<_i7.Result<void>>(
          this,
          Invocation.method(
            #saveRunner,
            [runner],
          ),
        )),
      ) as _i4.Future<_i7.Result<void>>);

  @override
  _i4.Future<_i7.Result<void>> saveRunners(
    int? raceId,
    List<_i12.Runner>? runners,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveRunners,
          [
            raceId,
            runners,
          ],
        ),
        returnValue:
            _i4.Future<_i7.Result<void>>.value(_i9.dummyValue<_i7.Result<void>>(
          this,
          Invocation.method(
            #saveRunners,
            [
              raceId,
              runners,
            ],
          ),
        )),
      ) as _i4.Future<_i7.Result<void>>);

  @override
  _i4.Future<_i7.Result<_i12.Runner?>> getRunner(
    int? raceId,
    String? bibNumber,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRunner,
          [
            raceId,
            bibNumber,
          ],
        ),
        returnValue: _i4.Future<_i7.Result<_i12.Runner?>>.value(
            _i9.dummyValue<_i7.Result<_i12.Runner?>>(
          this,
          Invocation.method(
            #getRunner,
            [
              raceId,
              bibNumber,
            ],
          ),
        )),
      ) as _i4.Future<_i7.Result<_i12.Runner?>>);

  @override
  _i4.Future<_i7.Result<List<_i12.Runner>>> getRunners(int? raceId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRunners,
          [raceId],
        ),
        returnValue: _i4.Future<_i7.Result<List<_i12.Runner>>>.value(
            _i9.dummyValue<_i7.Result<List<_i12.Runner>>>(
          this,
          Invocation.method(
            #getRunners,
            [raceId],
          ),
        )),
      ) as _i4.Future<_i7.Result<List<_i12.Runner>>>);

  @override
  _i4.Future<_i7.Result<void>> updateRunner(_i12.Runner? runner) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateRunner,
          [runner],
        ),
        returnValue:
            _i4.Future<_i7.Result<void>>.value(_i9.dummyValue<_i7.Result<void>>(
          this,
          Invocation.method(
            #updateRunner,
            [runner],
          ),
        )),
      ) as _i4.Future<_i7.Result<void>>);

  @override
  _i4.Future<_i7.Result<void>> deleteRunner(
    int? raceId,
    String? bibNumber,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteRunner,
          [
            raceId,
            bibNumber,
          ],
        ),
        returnValue:
            _i4.Future<_i7.Result<void>>.value(_i9.dummyValue<_i7.Result<void>>(
          this,
          Invocation.method(
            #deleteRunner,
            [
              raceId,
              bibNumber,
            ],
          ),
        )),
      ) as _i4.Future<_i7.Result<void>>);

  @override
  _i4.Future<_i7.Result<void>> deleteRunners(int? raceId) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteRunners,
          [raceId],
        ),
        returnValue:
            _i4.Future<_i7.Result<void>>.value(_i9.dummyValue<_i7.Result<void>>(
          this,
          Invocation.method(
            #deleteRunners,
            [raceId],
          ),
        )),
      ) as _i4.Future<_i7.Result<void>>);

  @override
  _i4.Future<_i7.Result<void>> saveBibRecord(_i13.BibRecord? bibRecord) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveBibRecord,
          [bibRecord],
        ),
        returnValue:
            _i4.Future<_i7.Result<void>>.value(_i9.dummyValue<_i7.Result<void>>(
          this,
          Invocation.method(
            #saveBibRecord,
            [bibRecord],
          ),
        )),
      ) as _i4.Future<_i7.Result<void>>);

  @override
  _i4.Future<_i7.Result<void>> saveBibRecords(
    int? raceId,
    List<_i13.BibRecord>? bibRecords,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveBibRecords,
          [
            raceId,
            bibRecords,
          ],
        ),
        returnValue:
            _i4.Future<_i7.Result<void>>.value(_i9.dummyValue<_i7.Result<void>>(
          this,
          Invocation.method(
            #saveBibRecords,
            [
              raceId,
              bibRecords,
            ],
          ),
        )),
      ) as _i4.Future<_i7.Result<void>>);

  @override
  _i4.Future<_i7.Result<void>> addBibRecord(
    int? raceId,
    int? bibId,
    String? bibNumber,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #addBibRecord,
          [
            raceId,
            bibId,
            bibNumber,
          ],
        ),
        returnValue:
            _i4.Future<_i7.Result<void>>.value(_i9.dummyValue<_i7.Result<void>>(
          this,
          Invocation.method(
            #addBibRecord,
            [
              raceId,
              bibId,
              bibNumber,
            ],
          ),
        )),
      ) as _i4.Future<_i7.Result<void>>);

  @override
  _i4.Future<_i7.Result<void>> removeBibRecord(
    int? raceId,
    int? bibId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeBibRecord,
          [
            raceId,
            bibId,
          ],
        ),
        returnValue:
            _i4.Future<_i7.Result<void>>.value(_i9.dummyValue<_i7.Result<void>>(
          this,
          Invocation.method(
            #removeBibRecord,
            [
              raceId,
              bibId,
            ],
          ),
        )),
      ) as _i4.Future<_i7.Result<void>>);

  @override
  _i4.Future<_i7.Result<void>> updateBibRecordValue(
    int? raceId,
    int? bibId,
    String? bibNumber,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateBibRecordValue,
          [
            raceId,
            bibId,
            bibNumber,
          ],
        ),
        returnValue:
            _i4.Future<_i7.Result<void>>.value(_i9.dummyValue<_i7.Result<void>>(
          this,
          Invocation.method(
            #updateBibRecordValue,
            [
              raceId,
              bibId,
              bibNumber,
            ],
          ),
        )),
      ) as _i4.Future<_i7.Result<void>>);

  @override
  _i4.Future<_i7.Result<_i13.BibRecord?>> getBibRecord(
    int? raceId,
    int? bibId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getBibRecord,
          [
            raceId,
            bibId,
          ],
        ),
        returnValue: _i4.Future<_i7.Result<_i13.BibRecord?>>.value(
            _i9.dummyValue<_i7.Result<_i13.BibRecord?>>(
          this,
          Invocation.method(
            #getBibRecord,
            [
              raceId,
              bibId,
            ],
          ),
        )),
      ) as _i4.Future<_i7.Result<_i13.BibRecord?>>);

  @override
  _i4.Future<_i7.Result<List<_i13.BibRecord>>> getBibRecords(int? raceId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getBibRecords,
          [raceId],
        ),
        returnValue: _i4.Future<_i7.Result<List<_i13.BibRecord>>>.value(
            _i9.dummyValue<_i7.Result<List<_i13.BibRecord>>>(
          this,
          Invocation.method(
            #getBibRecords,
            [raceId],
          ),
        )),
      ) as _i4.Future<_i7.Result<List<_i13.BibRecord>>>);

  @override
  _i4.Future<_i7.Result<void>> updateBibRecord(_i13.BibRecord? bibRecord) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateBibRecord,
          [bibRecord],
        ),
        returnValue:
            _i4.Future<_i7.Result<void>>.value(_i9.dummyValue<_i7.Result<void>>(
          this,
          Invocation.method(
            #updateBibRecord,
            [bibRecord],
          ),
        )),
      ) as _i4.Future<_i7.Result<void>>);

  @override
  _i4.Future<_i7.Result<void>> deleteBibRecord(
    int? raceId,
    int? bibId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteBibRecord,
          [
            raceId,
            bibId,
          ],
        ),
        returnValue:
            _i4.Future<_i7.Result<void>>.value(_i9.dummyValue<_i7.Result<void>>(
          this,
          Invocation.method(
            #deleteBibRecord,
            [
              raceId,
              bibId,
            ],
          ),
        )),
      ) as _i4.Future<_i7.Result<void>>);

  @override
  _i4.Future<_i7.Result<void>> deleteBibRecords(int? raceId) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteBibRecords,
          [raceId],
        ),
        returnValue:
            _i4.Future<_i7.Result<void>>.value(_i9.dummyValue<_i7.Result<void>>(
          this,
          Invocation.method(
            #deleteBibRecords,
            [raceId],
          ),
        )),
      ) as _i4.Future<_i7.Result<void>>);

  @override
  _i4.Future<_i7.Result<int>> getNextBibId(int? raceId) => (super.noSuchMethod(
        Invocation.method(
          #getNextBibId,
          [raceId],
        ),
        returnValue:
            _i4.Future<_i7.Result<int>>.value(_i9.dummyValue<_i7.Result<int>>(
          this,
          Invocation.method(
            #getNextBibId,
            [raceId],
          ),
        )),
      ) as _i4.Future<_i7.Result<int>>);

  @override
  _i4.Future<_i7.Result<void>> saveVerifierEntry(
    int? raceId,
    _i14.VerifierEntry? entry,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveVerifierEntry,
          [
            raceId,
            entry,
          ],
        ),
        returnValue:
            _i4.Future<_i7.Result<void>>.value(_i9.dummyValue<_i7.Result<void>>(
          this,
          Invocation.method(
            #saveVerifierEntry,
            [
              raceId,
              entry,
            ],
          ),
        )),
      ) as _i4.Future<_i7.Result<void>>);

  @override
  _i4.Future<_i7.Result<void>> updateVerifierEntryStatus(
    int? raceId,
    int? entryId,
    _i14.VerificationStatus? status,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateVerifierEntryStatus,
          [
            raceId,
            entryId,
            status,
          ],
        ),
        returnValue:
            _i4.Future<_i7.Result<void>>.value(_i9.dummyValue<_i7.Result<void>>(
          this,
          Invocation.method(
            #updateVerifierEntryStatus,
            [
              raceId,
              entryId,
              status,
            ],
          ),
        )),
      ) as _i4.Future<_i7.Result<void>>);

  @override
  _i4.Future<_i7.Result<List<_i14.VerifierEntry>>> getVerifierEntries(
          int? raceId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getVerifierEntries,
          [raceId],
        ),
        returnValue: _i4.Future<_i7.Result<List<_i14.VerifierEntry>>>.value(
            _i9.dummyValue<_i7.Result<List<_i14.VerifierEntry>>>(
          this,
          Invocation.method(
            #getVerifierEntries,
            [raceId],
          ),
        )),
      ) as _i4.Future<_i7.Result<List<_i14.VerifierEntry>>>);

  @override
  _i4.Future<_i7.Result<void>> deleteVerifierEntries(int? raceId) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteVerifierEntries,
          [raceId],
        ),
        returnValue:
            _i4.Future<_i7.Result<void>>.value(_i9.dummyValue<_i7.Result<void>>(
          this,
          Invocation.method(
            #deleteVerifierEntries,
            [raceId],
          ),
        )),
      ) as _i4.Future<_i7.Result<void>>);

  @override
  _i4.Future<_i7.Result<void>> saveFixerEntry(
    int? raceId,
    _i15.FixerEntry? entry,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveFixerEntry,
          [
            raceId,
            entry,
          ],
        ),
        returnValue:
            _i4.Future<_i7.Result<void>>.value(_i9.dummyValue<_i7.Result<void>>(
          this,
          Invocation.method(
            #saveFixerEntry,
            [
              raceId,
              entry,
            ],
          ),
        )),
      ) as _i4.Future<_i7.Result<void>>);

  @override
  _i4.Future<_i7.Result<void>> updateFixerEntryResolution(
    int? raceId,
    int? entryId, {
    required bool? isResolved,
    int? correctedBib,
    String? resolvedName,
    required bool? isNewRunner,
    required String? correctionType,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateFixerEntryResolution,
          [
            raceId,
            entryId,
          ],
          {
            #isResolved: isResolved,
            #correctedBib: correctedBib,
            #resolvedName: resolvedName,
            #isNewRunner: isNewRunner,
            #correctionType: correctionType,
          },
        ),
        returnValue:
            _i4.Future<_i7.Result<void>>.value(_i9.dummyValue<_i7.Result<void>>(
          this,
          Invocation.method(
            #updateFixerEntryResolution,
            [
              raceId,
              entryId,
            ],
            {
              #isResolved: isResolved,
              #correctedBib: correctedBib,
              #resolvedName: resolvedName,
              #isNewRunner: isNewRunner,
              #correctionType: correctionType,
            },
          ),
        )),
      ) as _i4.Future<_i7.Result<void>>);

  @override
  _i4.Future<_i7.Result<List<_i15.FixerEntry>>> getFixerEntries(int? raceId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getFixerEntries,
          [raceId],
        ),
        returnValue: _i4.Future<_i7.Result<List<_i15.FixerEntry>>>.value(
            _i9.dummyValue<_i7.Result<List<_i15.FixerEntry>>>(
          this,
          Invocation.method(
            #getFixerEntries,
            [raceId],
          ),
        )),
      ) as _i4.Future<_i7.Result<List<_i15.FixerEntry>>>);

  @override
  _i4.Future<_i7.Result<void>> deleteFixerEntries(int? raceId) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteFixerEntries,
          [raceId],
        ),
        returnValue:
            _i4.Future<_i7.Result<void>>.value(_i9.dummyValue<_i7.Result<void>>(
          this,
          Invocation.method(
            #deleteFixerEntries,
            [raceId],
          ),
        )),
      ) as _i4.Future<_i7.Result<void>>);
}

/// A class which mocks [IHapticFeedback].
///
/// See the documentation for Mockito's code generation for more information.
class MockIHapticFeedback extends _i1.Mock implements _i16.IHapticFeedback {
  MockIHapticFeedback() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<void> vibrate() => (super.noSuchMethod(
        Invocation.method(
          #vibrate,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> lightImpact() => (super.noSuchMethod(
        Invocation.method(
          #lightImpact,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}
