// Mocks generated by Mockito 5.4.6 from annotations
// in xceleration/test/unit/assistant/finish_line_roles/fixer/controller/fixer_controller_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:xceleration/assistant/finish_line_roles/shared/peer_connection/messages/messages.dart'
    as _i5;
import 'package:xceleration/assistant/finish_line_roles/shared/peer_connection/p2p_session_service.dart'
    as _i2;
import 'package:xceleration/shared/role_bar/models/role_enums.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [P2PSessionService].
///
/// See the documentation for Mockito's code generation for more information.
class MockP2PSessionService extends _i1.Mock implements _i2.P2PSessionService {
  MockP2PSessionService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Role get localRole => (super.noSuchMethod(
        Invocation.getter(#localRole),
        returnValue: _i3.Role.timer,
      ) as _i3.Role);

  @override
  int get raceId => (super.noSuchMethod(
        Invocation.getter(#raceId),
        returnValue: 0,
      ) as int);

  @override
  _i4.Stream<(_i3.Role, _i5.MessageEnvelope)> get incomingMessages =>
      (super.noSuchMethod(
        Invocation.getter(#incomingMessages),
        returnValue: _i4.Stream<(_i3.Role, _i5.MessageEnvelope)>.empty(),
      ) as _i4.Stream<(_i3.Role, _i5.MessageEnvelope)>);

  @override
  _i4.Future<void> init() => (super.noSuchMethod(
        Invocation.method(
          #init,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> sendMessage(
    _i3.Role? target,
    _i5.MessageEnvelope? msg,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #sendMessage,
          [
            target,
            msg,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  int pendingCount(_i3.Role? peer) => (super.noSuchMethod(
        Invocation.method(
          #pendingCount,
          [peer],
        ),
        returnValue: 0,
      ) as int);

  @override
  _i4.Future<void> dispose() => (super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}
