// Mocks generated by Mockito 5.4.6 from annotations
// in xceleration/test/unit/coach/share_race/controller/share_race_controller_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i7;
import 'dart:ui' as _i10;

import 'package:flutter/foundation.dart' as _i5;
import 'package:flutter/material.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:share_plus/share_plus.dart' as _i12;
import 'package:xceleration/coach/race_results/model/team_record.dart' as _i9;
import 'package:xceleration/coach/share_race/controller/share_race_controller.dart'
    as _i6;
import 'package:xceleration/coach/share_race/services/i_share_service.dart'
    as _i11;
import 'package:xceleration/core/utils/i_google_sheets_service.dart' as _i13;
import 'package:xceleration/shared/models/database/base_models.dart' as _i3;
import 'package:xceleration/shared/models/database/master_race.dart' as _i8;
import 'package:xceleration/shared/services/race_results_service.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeRaceResultsData_0 extends _i1.SmartFake
    implements _i2.RaceResultsData {
  _FakeRaceResultsData_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeRace_1 extends _i1.SmartFake implements _i3.Race {
  _FakeRace_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeWidget_2 extends _i1.SmartFake implements _i4.Widget {
  _FakeWidget_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );

  @override
  String toString({_i4.DiagnosticLevel? minLevel = _i4.DiagnosticLevel.info}) =>
      super.toString();
}

class _FakeInheritedWidget_3 extends _i1.SmartFake
    implements _i4.InheritedWidget {
  _FakeInheritedWidget_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );

  @override
  String toString({_i4.DiagnosticLevel? minLevel = _i4.DiagnosticLevel.info}) =>
      super.toString();
}

class _FakeDiagnosticsNode_4 extends _i1.SmartFake
    implements _i4.DiagnosticsNode {
  _FakeDiagnosticsNode_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );

  @override
  String toString({
    _i5.TextTreeConfiguration? parentConfiguration,
    _i4.DiagnosticLevel? minLevel = _i4.DiagnosticLevel.info,
  }) =>
      super.toString();
}

class _FakeUri_5 extends _i1.SmartFake implements Uri {
  _FakeUri_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ShareResultsController].
///
/// See the documentation for Mockito's code generation for more information.
class MockShareResultsController extends _i1.Mock
    implements _i6.ShareResultsController {
  MockShareResultsController() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.RaceResultsData get raceResultsData => (super.noSuchMethod(
        Invocation.getter(#raceResultsData),
        returnValue: _FakeRaceResultsData_0(
          this,
          Invocation.getter(#raceResultsData),
        ),
      ) as _i2.RaceResultsData);

  @override
  _i7.Future<void> handlePlainTextCopy(_i4.BuildContext? context) =>
      (super.noSuchMethod(
        Invocation.method(
          #handlePlainTextCopy,
          [context],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> handleGoogleSheet(_i4.BuildContext? context) =>
      (super.noSuchMethod(
        Invocation.method(
          #handleGoogleSheet,
          [context],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> handlePdf(_i4.BuildContext? context) => (super.noSuchMethod(
        Invocation.method(
          #handlePdf,
          [context],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);
}

/// A class which mocks [MasterRace].
///
/// See the documentation for Mockito's code generation for more information.
class MockMasterRace extends _i1.Mock implements _i8.MasterRace {
  MockMasterRace() {
    _i1.throwOnMissingStub(this);
  }

  @override
  int get raceId => (super.noSuchMethod(
        Invocation.getter(#raceId),
        returnValue: 0,
      ) as int);

  @override
  _i7.Future<_i3.Race> get race => (super.noSuchMethod(
        Invocation.getter(#race),
        returnValue: _i7.Future<_i3.Race>.value(_FakeRace_1(
          this,
          Invocation.getter(#race),
        )),
      ) as _i7.Future<_i3.Race>);

  @override
  _i7.Future<List<_i3.RaceParticipant>> get raceParticipants =>
      (super.noSuchMethod(
        Invocation.getter(#raceParticipants),
        returnValue: _i7.Future<List<_i3.RaceParticipant>>.value(
            <_i3.RaceParticipant>[]),
      ) as _i7.Future<List<_i3.RaceParticipant>>);

  @override
  _i7.Future<List<_i3.RaceRunner>> get raceRunners => (super.noSuchMethod(
        Invocation.getter(#raceRunners),
        returnValue: _i7.Future<List<_i3.RaceRunner>>.value(<_i3.RaceRunner>[]),
      ) as _i7.Future<List<_i3.RaceRunner>>);

  @override
  _i7.Future<List<_i3.Team>> get teams => (super.noSuchMethod(
        Invocation.getter(#teams),
        returnValue: _i7.Future<List<_i3.Team>>.value(<_i3.Team>[]),
      ) as _i7.Future<List<_i3.Team>>);

  @override
  _i7.Future<Map<_i3.Team, List<_i3.RaceRunner>>> get teamtoRaceRunnersMap =>
      (super.noSuchMethod(
        Invocation.getter(#teamtoRaceRunnersMap),
        returnValue: _i7.Future<Map<_i3.Team, List<_i3.RaceRunner>>>.value(
            <_i3.Team, List<_i3.RaceRunner>>{}),
      ) as _i7.Future<Map<_i3.Team, List<_i3.RaceRunner>>>);

  @override
  _i7.Future<Map<_i3.Team, List<_i3.RaceRunner>>> get filteredSearchResults =>
      (super.noSuchMethod(
        Invocation.getter(#filteredSearchResults),
        returnValue: _i7.Future<Map<_i3.Team, List<_i3.RaceRunner>>>.value(
            <_i3.Team, List<_i3.RaceRunner>>{}),
      ) as _i7.Future<Map<_i3.Team, List<_i3.RaceRunner>>>);

  @override
  _i7.Future<List<_i3.RaceResult>> get results => (super.noSuchMethod(
        Invocation.getter(#results),
        returnValue: _i7.Future<List<_i3.RaceResult>>.value(<_i3.RaceResult>[]),
      ) as _i7.Future<List<_i3.RaceResult>>);

  @override
  _i7.Future<List<_i9.TeamRecord>> get teamStandings => (super.noSuchMethod(
        Invocation.getter(#teamStandings),
        returnValue: _i7.Future<List<_i9.TeamRecord>>.value(<_i9.TeamRecord>[]),
      ) as _i7.Future<List<_i9.TeamRecord>>);

  @override
  _i7.Future<_i2.RaceResultsData> get raceResultsData => (super.noSuchMethod(
        Invocation.getter(#raceResultsData),
        returnValue:
            _i7.Future<_i2.RaceResultsData>.value(_FakeRaceResultsData_0(
          this,
          Invocation.getter(#raceResultsData),
        )),
      ) as _i7.Future<_i2.RaceResultsData>);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  _i7.Future<_i3.RaceRunner?> getRaceRunnerFromRaceParticipant(
          _i3.RaceParticipant? raceParticipant) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRaceRunnerFromRaceParticipant,
          [raceParticipant],
        ),
        returnValue: _i7.Future<_i3.RaceRunner?>.value(),
      ) as _i7.Future<_i3.RaceRunner?>);

  @override
  _i7.Future<void> updateRaceParticipant(
          _i3.RaceParticipant? raceParticipant) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateRaceParticipant,
          [raceParticipant],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> addRaceParticipant(_i3.RaceParticipant? raceParticipant) =>
      (super.noSuchMethod(
        Invocation.method(
          #addRaceParticipant,
          [raceParticipant],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> addRaceParticipantsBulk(
          List<_i3.RaceParticipant>? raceParticipants) =>
      (super.noSuchMethod(
        Invocation.method(
          #addRaceParticipantsBulk,
          [raceParticipants],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> removeRaceParticipant(
          _i3.RaceParticipant? raceParticipant) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeRaceParticipant,
          [raceParticipant],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> addTeamParticipant(_i3.TeamParticipant? teamParticipant) =>
      (super.noSuchMethod(
        Invocation.method(
          #addTeamParticipant,
          [teamParticipant],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> removeTeamFromRace(_i3.TeamParticipant? teamParticipant) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeTeamFromRace,
          [teamParticipant],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> updateRace(_i3.Race? race) => (super.noSuchMethod(
        Invocation.method(
          #updateRace,
          [race],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> removeRaceRunner(_i3.RaceRunner? raceRunner) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeRaceRunner,
          [raceRunner],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> addResult(_i3.RaceResult? result) => (super.noSuchMethod(
        Invocation.method(
          #addResult,
          [result],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> saveResults(List<_i3.RaceResult>? results) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveResults,
          [results],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<_i3.Team?> getTeamByName(String? teamName) => (super.noSuchMethod(
        Invocation.method(
          #getTeamByName,
          [teamName],
        ),
        returnValue: _i7.Future<_i3.Team?>.value(),
      ) as _i7.Future<_i3.Team?>);

  @override
  _i7.Future<_i3.RaceRunner?> getRaceRunnerByBib(String? bibNumber) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRaceRunnerByBib,
          [bibNumber],
        ),
        returnValue: _i7.Future<_i3.RaceRunner?>.value(),
      ) as _i7.Future<_i3.RaceRunner?>);

  @override
  _i7.Future<void> searchRaceRunners(
    String? query, [
    String? searchAttribute = 'all',
  ]) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchRaceRunners,
          [
            query,
            searchAttribute,
          ],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<_i3.Runner?> getRunnerByBib(String? bibNumber) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRunnerByBib,
          [bibNumber],
        ),
        returnValue: _i7.Future<_i3.Runner?>.value(),
      ) as _i7.Future<_i3.Runner?>);

  @override
  _i7.Future<int> createRunner(_i3.Runner? runner) => (super.noSuchMethod(
        Invocation.method(
          #createRunner,
          [runner],
        ),
        returnValue: _i7.Future<int>.value(0),
      ) as _i7.Future<int>);

  @override
  _i7.Future<void> addRunnerToTeam(
    int? teamId,
    int? runnerId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #addRunnerToTeam,
          [
            teamId,
            runnerId,
          ],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<List<_i3.Team>> getOtherTeams() => (super.noSuchMethod(
        Invocation.method(
          #getOtherTeams,
          [],
        ),
        returnValue: _i7.Future<List<_i3.Team>>.value(<_i3.Team>[]),
      ) as _i7.Future<List<_i3.Team>>);

  @override
  void invalidateCache() => super.noSuchMethod(
        Invocation.method(
          #invalidateCache,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addListener(_i10.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i10.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [BuildContext].
///
/// See the documentation for Mockito's code generation for more information.
class MockBuildContext extends _i1.Mock implements _i4.BuildContext {
  MockBuildContext() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Widget get widget => (super.noSuchMethod(
        Invocation.getter(#widget),
        returnValue: _FakeWidget_2(
          this,
          Invocation.getter(#widget),
        ),
      ) as _i4.Widget);

  @override
  bool get mounted => (super.noSuchMethod(
        Invocation.getter(#mounted),
        returnValue: false,
      ) as bool);

  @override
  bool get debugDoingBuild => (super.noSuchMethod(
        Invocation.getter(#debugDoingBuild),
        returnValue: false,
      ) as bool);

  @override
  _i4.InheritedWidget dependOnInheritedElement(
    _i4.InheritedElement? ancestor, {
    Object? aspect,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #dependOnInheritedElement,
          [ancestor],
          {#aspect: aspect},
        ),
        returnValue: _FakeInheritedWidget_3(
          this,
          Invocation.method(
            #dependOnInheritedElement,
            [ancestor],
            {#aspect: aspect},
          ),
        ),
      ) as _i4.InheritedWidget);

  @override
  void visitAncestorElements(_i4.ConditionalElementVisitor? visitor) =>
      super.noSuchMethod(
        Invocation.method(
          #visitAncestorElements,
          [visitor],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void visitChildElements(_i4.ElementVisitor? visitor) => super.noSuchMethod(
        Invocation.method(
          #visitChildElements,
          [visitor],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispatchNotification(_i4.Notification? notification) =>
      super.noSuchMethod(
        Invocation.method(
          #dispatchNotification,
          [notification],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i4.DiagnosticsNode describeElement(
    String? name, {
    _i5.DiagnosticsTreeStyle? style = _i5.DiagnosticsTreeStyle.errorProperty,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #describeElement,
          [name],
          {#style: style},
        ),
        returnValue: _FakeDiagnosticsNode_4(
          this,
          Invocation.method(
            #describeElement,
            [name],
            {#style: style},
          ),
        ),
      ) as _i4.DiagnosticsNode);

  @override
  _i4.DiagnosticsNode describeWidget(
    String? name, {
    _i5.DiagnosticsTreeStyle? style = _i5.DiagnosticsTreeStyle.errorProperty,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #describeWidget,
          [name],
          {#style: style},
        ),
        returnValue: _FakeDiagnosticsNode_4(
          this,
          Invocation.method(
            #describeWidget,
            [name],
            {#style: style},
          ),
        ),
      ) as _i4.DiagnosticsNode);

  @override
  List<_i4.DiagnosticsNode> describeMissingAncestor(
          {required Type? expectedAncestorType}) =>
      (super.noSuchMethod(
        Invocation.method(
          #describeMissingAncestor,
          [],
          {#expectedAncestorType: expectedAncestorType},
        ),
        returnValue: <_i4.DiagnosticsNode>[],
      ) as List<_i4.DiagnosticsNode>);

  @override
  _i4.DiagnosticsNode describeOwnershipChain(String? name) =>
      (super.noSuchMethod(
        Invocation.method(
          #describeOwnershipChain,
          [name],
        ),
        returnValue: _FakeDiagnosticsNode_4(
          this,
          Invocation.method(
            #describeOwnershipChain,
            [name],
          ),
        ),
      ) as _i4.DiagnosticsNode);
}

/// A class which mocks [IShareService].
///
/// See the documentation for Mockito's code generation for more information.
class MockIShareService extends _i1.Mock implements _i11.IShareService {
  MockIShareService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Future<void> share(_i12.ShareParams? params) => (super.noSuchMethod(
        Invocation.method(
          #share,
          [params],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);
}

/// A class which mocks [IGoogleSheetsService].
///
/// See the documentation for Mockito's code generation for more information.
class MockIGoogleSheetsService extends _i1.Mock
    implements _i13.IGoogleSheetsService {
  MockIGoogleSheetsService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Future<bool> signIn() => (super.noSuchMethod(
        Invocation.method(
          #signIn,
          [],
        ),
        returnValue: _i7.Future<bool>.value(false),
      ) as _i7.Future<bool>);

  @override
  _i7.Future<String?> createSheet({required String? title}) =>
      (super.noSuchMethod(
        Invocation.method(
          #createSheet,
          [],
          {#title: title},
        ),
        returnValue: _i7.Future<String?>.value(),
      ) as _i7.Future<String?>);

  @override
  _i7.Future<bool> updateSheet({
    required String? spreadsheetId,
    required List<List<dynamic>>? data,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateSheet,
          [],
          {
            #spreadsheetId: spreadsheetId,
            #data: data,
          },
        ),
        returnValue: _i7.Future<bool>.value(false),
      ) as _i7.Future<bool>);

  @override
  _i7.Future<Uri> getSheetUri(String? spreadsheetId) => (super.noSuchMethod(
        Invocation.method(
          #getSheetUri,
          [spreadsheetId],
        ),
        returnValue: _i7.Future<Uri>.value(_FakeUri_5(
          this,
          Invocation.method(
            #getSheetUri,
            [spreadsheetId],
          ),
        )),
      ) as _i7.Future<Uri>);
}
