// Mocks generated by Mockito 5.4.6 from annotations
// in xceleration/test/unit/coach/share_race/controller/share_race_controller_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i8;
import 'dart:ui' as _i11;

import 'package:flutter/foundation.dart' as _i6;
import 'package:flutter/material.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;
import 'package:xceleration/coach/race_results/model/team_record.dart' as _i10;
import 'package:xceleration/coach/share_race/controller/share_race_controller.dart'
    as _i7;
import 'package:xceleration/core/utils/database_helper.dart' as _i3;
import 'package:xceleration/shared/models/database/base_models.dart' as _i4;
import 'package:xceleration/shared/models/database/master_race.dart' as _i9;
import 'package:xceleration/shared/services/race_results_service.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeRaceResultsData_0 extends _i1.SmartFake
    implements _i2.RaceResultsData {
  _FakeRaceResultsData_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDatabaseHelper_1 extends _i1.SmartFake
    implements _i3.DatabaseHelper {
  _FakeDatabaseHelper_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeRace_2 extends _i1.SmartFake implements _i4.Race {
  _FakeRace_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeWidget_3 extends _i1.SmartFake implements _i5.Widget {
  _FakeWidget_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );

  @override
  String toString({_i5.DiagnosticLevel? minLevel = _i5.DiagnosticLevel.info}) =>
      super.toString();
}

class _FakeInheritedWidget_4 extends _i1.SmartFake
    implements _i5.InheritedWidget {
  _FakeInheritedWidget_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );

  @override
  String toString({_i5.DiagnosticLevel? minLevel = _i5.DiagnosticLevel.info}) =>
      super.toString();
}

class _FakeDiagnosticsNode_5 extends _i1.SmartFake
    implements _i5.DiagnosticsNode {
  _FakeDiagnosticsNode_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );

  @override
  String toString({
    _i6.TextTreeConfiguration? parentConfiguration,
    _i5.DiagnosticLevel? minLevel = _i5.DiagnosticLevel.info,
  }) =>
      super.toString();
}

/// A class which mocks [ShareResultsController].
///
/// See the documentation for Mockito's code generation for more information.
class MockShareResultsController extends _i1.Mock
    implements _i7.ShareResultsController {
  MockShareResultsController() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.RaceResultsData get raceResultsData => (super.noSuchMethod(
        Invocation.getter(#raceResultsData),
        returnValue: _FakeRaceResultsData_0(
          this,
          Invocation.getter(#raceResultsData),
        ),
      ) as _i2.RaceResultsData);

  @override
  _i8.Future<void> handlePlainTextCopy(_i5.BuildContext? context) =>
      (super.noSuchMethod(
        Invocation.method(
          #handlePlainTextCopy,
          [context],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> handleGoogleSheet(_i5.BuildContext? context) =>
      (super.noSuchMethod(
        Invocation.method(
          #handleGoogleSheet,
          [context],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> handlePdf(_i5.BuildContext? context) => (super.noSuchMethod(
        Invocation.method(
          #handlePdf,
          [context],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);
}

/// A class which mocks [MasterRace].
///
/// See the documentation for Mockito's code generation for more information.
class MockMasterRace extends _i1.Mock implements _i9.MasterRace {
  MockMasterRace() {
    _i1.throwOnMissingStub(this);
  }

  @override
  int get raceId => (super.noSuchMethod(
        Invocation.getter(#raceId),
        returnValue: 0,
      ) as int);

  @override
  _i3.DatabaseHelper get db => (super.noSuchMethod(
        Invocation.getter(#db),
        returnValue: _FakeDatabaseHelper_1(
          this,
          Invocation.getter(#db),
        ),
      ) as _i3.DatabaseHelper);

  @override
  _i8.Future<_i4.Race> get race => (super.noSuchMethod(
        Invocation.getter(#race),
        returnValue: _i8.Future<_i4.Race>.value(_FakeRace_2(
          this,
          Invocation.getter(#race),
        )),
      ) as _i8.Future<_i4.Race>);

  @override
  _i8.Future<List<_i4.RaceParticipant>> get raceParticipants =>
      (super.noSuchMethod(
        Invocation.getter(#raceParticipants),
        returnValue: _i8.Future<List<_i4.RaceParticipant>>.value(
            <_i4.RaceParticipant>[]),
      ) as _i8.Future<List<_i4.RaceParticipant>>);

  @override
  _i8.Future<List<_i4.RaceRunner>> get raceRunners => (super.noSuchMethod(
        Invocation.getter(#raceRunners),
        returnValue: _i8.Future<List<_i4.RaceRunner>>.value(<_i4.RaceRunner>[]),
      ) as _i8.Future<List<_i4.RaceRunner>>);

  @override
  _i8.Future<List<_i4.Team>> get teams => (super.noSuchMethod(
        Invocation.getter(#teams),
        returnValue: _i8.Future<List<_i4.Team>>.value(<_i4.Team>[]),
      ) as _i8.Future<List<_i4.Team>>);

  @override
  _i8.Future<Map<_i4.Team, List<_i4.RaceRunner>>> get teamtoRaceRunnersMap =>
      (super.noSuchMethod(
        Invocation.getter(#teamtoRaceRunnersMap),
        returnValue: _i8.Future<Map<_i4.Team, List<_i4.RaceRunner>>>.value(
            <_i4.Team, List<_i4.RaceRunner>>{}),
      ) as _i8.Future<Map<_i4.Team, List<_i4.RaceRunner>>>);

  @override
  _i8.Future<Map<_i4.Team, List<_i4.RaceRunner>>> get filteredSearchResults =>
      (super.noSuchMethod(
        Invocation.getter(#filteredSearchResults),
        returnValue: _i8.Future<Map<_i4.Team, List<_i4.RaceRunner>>>.value(
            <_i4.Team, List<_i4.RaceRunner>>{}),
      ) as _i8.Future<Map<_i4.Team, List<_i4.RaceRunner>>>);

  @override
  _i8.Future<List<_i4.RaceResult>> get results => (super.noSuchMethod(
        Invocation.getter(#results),
        returnValue: _i8.Future<List<_i4.RaceResult>>.value(<_i4.RaceResult>[]),
      ) as _i8.Future<List<_i4.RaceResult>>);

  @override
  _i8.Future<List<_i10.TeamRecord>> get teamStandings => (super.noSuchMethod(
        Invocation.getter(#teamStandings),
        returnValue:
            _i8.Future<List<_i10.TeamRecord>>.value(<_i10.TeamRecord>[]),
      ) as _i8.Future<List<_i10.TeamRecord>>);

  @override
  _i8.Future<_i2.RaceResultsData> get raceResultsData => (super.noSuchMethod(
        Invocation.getter(#raceResultsData),
        returnValue:
            _i8.Future<_i2.RaceResultsData>.value(_FakeRaceResultsData_0(
          this,
          Invocation.getter(#raceResultsData),
        )),
      ) as _i8.Future<_i2.RaceResultsData>);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  _i8.Future<_i4.RaceRunner?> getRaceRunnerFromRaceParticipant(
          _i4.RaceParticipant? raceParticipant) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRaceRunnerFromRaceParticipant,
          [raceParticipant],
        ),
        returnValue: _i8.Future<_i4.RaceRunner?>.value(),
      ) as _i8.Future<_i4.RaceRunner?>);

  @override
  _i8.Future<void> updateRaceParticipant(
          _i4.RaceParticipant? raceParticipant) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateRaceParticipant,
          [raceParticipant],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> addRaceParticipant(_i4.RaceParticipant? raceParticipant) =>
      (super.noSuchMethod(
        Invocation.method(
          #addRaceParticipant,
          [raceParticipant],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> addRaceParticipantsBulk(
          List<_i4.RaceParticipant>? raceParticipants) =>
      (super.noSuchMethod(
        Invocation.method(
          #addRaceParticipantsBulk,
          [raceParticipants],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> removeRaceParticipant(
          _i4.RaceParticipant? raceParticipant) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeRaceParticipant,
          [raceParticipant],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> addTeamParticipant(_i4.TeamParticipant? teamParticipant) =>
      (super.noSuchMethod(
        Invocation.method(
          #addTeamParticipant,
          [teamParticipant],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> removeTeamFromRace(_i4.TeamParticipant? teamParticipant) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeTeamFromRace,
          [teamParticipant],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> updateRace(_i4.Race? race) => (super.noSuchMethod(
        Invocation.method(
          #updateRace,
          [race],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> removeRaceRunner(_i4.RaceRunner? raceRunner) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeRaceRunner,
          [raceRunner],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> addResult(_i4.RaceResult? result) => (super.noSuchMethod(
        Invocation.method(
          #addResult,
          [result],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> saveResults(List<_i4.RaceResult>? results) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveResults,
          [results],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<_i4.Team?> getTeamByName(String? teamName) => (super.noSuchMethod(
        Invocation.method(
          #getTeamByName,
          [teamName],
        ),
        returnValue: _i8.Future<_i4.Team?>.value(),
      ) as _i8.Future<_i4.Team?>);

  @override
  _i8.Future<_i4.RaceRunner?> getRaceRunnerByBib(String? bibNumber) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRaceRunnerByBib,
          [bibNumber],
        ),
        returnValue: _i8.Future<_i4.RaceRunner?>.value(),
      ) as _i8.Future<_i4.RaceRunner?>);

  @override
  _i8.Future<void> searchRaceRunners(
    String? query, [
    String? searchAttribute = 'all',
  ]) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchRaceRunners,
          [
            query,
            searchAttribute,
          ],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<_i4.Runner?> getRunnerByBib(String? bibNumber) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRunnerByBib,
          [bibNumber],
        ),
        returnValue: _i8.Future<_i4.Runner?>.value(),
      ) as _i8.Future<_i4.Runner?>);

  @override
  _i8.Future<int> createRunner(_i4.Runner? runner) => (super.noSuchMethod(
        Invocation.method(
          #createRunner,
          [runner],
        ),
        returnValue: _i8.Future<int>.value(0),
      ) as _i8.Future<int>);

  @override
  _i8.Future<void> addRunnerToTeam(
    int? teamId,
    int? runnerId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #addRunnerToTeam,
          [
            teamId,
            runnerId,
          ],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<List<_i4.Team>> getOtherTeams() => (super.noSuchMethod(
        Invocation.method(
          #getOtherTeams,
          [],
        ),
        returnValue: _i8.Future<List<_i4.Team>>.value(<_i4.Team>[]),
      ) as _i8.Future<List<_i4.Team>>);

  @override
  void invalidateCache() => super.noSuchMethod(
        Invocation.method(
          #invalidateCache,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addListener(_i11.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i11.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [BuildContext].
///
/// See the documentation for Mockito's code generation for more information.
class MockBuildContext extends _i1.Mock implements _i5.BuildContext {
  MockBuildContext() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Widget get widget => (super.noSuchMethod(
        Invocation.getter(#widget),
        returnValue: _FakeWidget_3(
          this,
          Invocation.getter(#widget),
        ),
      ) as _i5.Widget);

  @override
  bool get mounted => (super.noSuchMethod(
        Invocation.getter(#mounted),
        returnValue: false,
      ) as bool);

  @override
  bool get debugDoingBuild => (super.noSuchMethod(
        Invocation.getter(#debugDoingBuild),
        returnValue: false,
      ) as bool);

  @override
  _i5.InheritedWidget dependOnInheritedElement(
    _i5.InheritedElement? ancestor, {
    Object? aspect,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #dependOnInheritedElement,
          [ancestor],
          {#aspect: aspect},
        ),
        returnValue: _FakeInheritedWidget_4(
          this,
          Invocation.method(
            #dependOnInheritedElement,
            [ancestor],
            {#aspect: aspect},
          ),
        ),
      ) as _i5.InheritedWidget);

  @override
  void visitAncestorElements(_i5.ConditionalElementVisitor? visitor) =>
      super.noSuchMethod(
        Invocation.method(
          #visitAncestorElements,
          [visitor],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void visitChildElements(_i5.ElementVisitor? visitor) => super.noSuchMethod(
        Invocation.method(
          #visitChildElements,
          [visitor],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispatchNotification(_i5.Notification? notification) =>
      super.noSuchMethod(
        Invocation.method(
          #dispatchNotification,
          [notification],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i5.DiagnosticsNode describeElement(
    String? name, {
    _i6.DiagnosticsTreeStyle? style = _i6.DiagnosticsTreeStyle.errorProperty,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #describeElement,
          [name],
          {#style: style},
        ),
        returnValue: _FakeDiagnosticsNode_5(
          this,
          Invocation.method(
            #describeElement,
            [name],
            {#style: style},
          ),
        ),
      ) as _i5.DiagnosticsNode);

  @override
  _i5.DiagnosticsNode describeWidget(
    String? name, {
    _i6.DiagnosticsTreeStyle? style = _i6.DiagnosticsTreeStyle.errorProperty,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #describeWidget,
          [name],
          {#style: style},
        ),
        returnValue: _FakeDiagnosticsNode_5(
          this,
          Invocation.method(
            #describeWidget,
            [name],
            {#style: style},
          ),
        ),
      ) as _i5.DiagnosticsNode);

  @override
  List<_i5.DiagnosticsNode> describeMissingAncestor(
          {required Type? expectedAncestorType}) =>
      (super.noSuchMethod(
        Invocation.method(
          #describeMissingAncestor,
          [],
          {#expectedAncestorType: expectedAncestorType},
        ),
        returnValue: <_i5.DiagnosticsNode>[],
      ) as List<_i5.DiagnosticsNode>);

  @override
  _i5.DiagnosticsNode describeOwnershipChain(String? name) =>
      (super.noSuchMethod(
        Invocation.method(
          #describeOwnershipChain,
          [name],
        ),
        returnValue: _FakeDiagnosticsNode_5(
          this,
          Invocation.method(
            #describeOwnershipChain,
            [name],
          ),
        ),
      ) as _i5.DiagnosticsNode);
}
