// Mocks generated by Mockito 5.4.6 from annotations
// in xceleration/test/widget/assistant/finish_line_roles/bib_recorder/bib_recorder_v2_screen_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i7;
import 'dart:ui' as _i10;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;
import 'package:xceleration/assistant/finish_line_roles/bib_recorder/controller/bib_recorder_v2_controller.dart'
    as _i2;
import 'package:xceleration/assistant/finish_line_roles/shared/models/bib_correction_message.dart'
    as _i8;
import 'package:xceleration/assistant/finish_line_roles/shared/models/bib_entry.dart'
    as _i4;
import 'package:xceleration/assistant/shared/models/race_record.dart' as _i3;
import 'package:xceleration/assistant/shared/models/runner.dart' as _i5;
import 'package:xceleration/core/result.dart' as _i9;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [BibRecorderV2Controller].
///
/// See the documentation for Mockito's code generation for more information.
class MockBibRecorderV2Controller extends _i1.Mock
    implements _i2.BibRecorderV2Controller {
  MockBibRecorderV2Controller() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<_i3.RaceRecord> get races => (super.noSuchMethod(
        Invocation.getter(#races),
        returnValue: <_i3.RaceRecord>[],
      ) as List<_i3.RaceRecord>);

  @override
  bool get raceStarted => (super.noSuchMethod(
        Invocation.getter(#raceStarted),
        returnValue: false,
      ) as bool);

  @override
  bool get raceStopped => (super.noSuchMethod(
        Invocation.getter(#raceStopped),
        returnValue: false,
      ) as bool);

  @override
  List<_i4.BibEntry> get entries => (super.noSuchMethod(
        Invocation.getter(#entries),
        returnValue: <_i4.BibEntry>[],
      ) as List<_i4.BibEntry>);

  @override
  List<_i5.Runner> get runners => (super.noSuchMethod(
        Invocation.getter(#runners),
        returnValue: <_i5.Runner>[],
      ) as List<_i5.Runner>);

  @override
  bool get voiceReady => (super.noSuchMethod(
        Invocation.getter(#voiceReady),
        returnValue: false,
      ) as bool);

  @override
  bool get isListening => (super.noSuchMethod(
        Invocation.getter(#isListening),
        returnValue: false,
      ) as bool);

  @override
  bool get isProcessing => (super.noSuchMethod(
        Invocation.getter(#isProcessing),
        returnValue: false,
      ) as bool);

  @override
  String get transcript => (super.noSuchMethod(
        Invocation.getter(#transcript),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.getter(#transcript),
        ),
      ) as String);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  _i7.Future<void> initialize() => (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  void selectRace(_i3.RaceRecord? race) => super.noSuchMethod(
        Invocation.method(
          #selectRace,
          [race],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void beginRace() => super.noSuchMethod(
        Invocation.method(
          #beginRace,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void stopRace() => super.noSuchMethod(
        Invocation.method(
          #stopRace,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void resumeRace() => super.noSuchMethod(
        Invocation.method(
          #resumeRace,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void leaveRace() => super.noSuchMethod(
        Invocation.method(
          #leaveRace,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i7.Future<void> deleteRace() => (super.noSuchMethod(
        Invocation.method(
          #deleteRace,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  String? flagFor(
    int? bib, {
    int? excludeId,
  }) =>
      (super.noSuchMethod(Invocation.method(
        #flagFor,
        [bib],
        {#excludeId: excludeId},
      )) as String?);

  @override
  void applyCorrection(_i8.BibCorrectionMessage? msg) => super.noSuchMethod(
        Invocation.method(
          #applyCorrection,
          [msg],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i5.Runner? runnerFor(int? bib) => (super.noSuchMethod(Invocation.method(
        #runnerFor,
        [bib],
      )) as _i5.Runner?);

  @override
  _i7.Future<void> startListening() => (super.noSuchMethod(
        Invocation.method(
          #startListening,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> stopListening() => (super.noSuchMethod(
        Invocation.method(
          #stopListening,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  void addBib(int? bib) => super.noSuchMethod(
        Invocation.method(
          #addBib,
          [bib],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void reRecordLast() => super.noSuchMethod(
        Invocation.method(
          #reRecordLast,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void deleteEntry(int? id) => super.noSuchMethod(
        Invocation.method(
          #deleteEntry,
          [id],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void editEntry(
    int? id,
    int? newBib,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #editEntry,
          [
            id,
            newBib,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void clearEntries() => super.noSuchMethod(
        Invocation.method(
          #clearEntries,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i7.Future<_i9.Result<void>> processLoadedRaceData(String? data) =>
      (super.noSuchMethod(
        Invocation.method(
          #processLoadedRaceData,
          [data],
        ),
        returnValue:
            _i7.Future<_i9.Result<void>>.value(_i6.dummyValue<_i9.Result<void>>(
          this,
          Invocation.method(
            #processLoadedRaceData,
            [data],
          ),
        )),
      ) as _i7.Future<_i9.Result<void>>);

  @override
  _i7.Future<String> getEncodedBibData() => (super.noSuchMethod(
        Invocation.method(
          #getEncodedBibData,
          [],
        ),
        returnValue: _i7.Future<String>.value(_i6.dummyValue<String>(
          this,
          Invocation.method(
            #getEncodedBibData,
            [],
          ),
        )),
      ) as _i7.Future<String>);

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addListener(_i10.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i10.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
