// Mocks generated by Mockito 5.4.6 from annotations
// in xceleration/test/unit/coach/race_screen/controller/race_screen_controller_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i12;
import 'dart:ui' as _i14;

import 'package:flutter/material.dart' as _i5;
import 'package:geocoding/geocoding.dart' as _i19;
import 'package:geolocator/geolocator.dart' as _i10;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i16;
import 'package:xceleration/coach/flows/controller/flow_controller.dart'
    as _i17;
import 'package:xceleration/coach/flows/PostRaceFlow/controller/post_race_controller.dart'
    as _i9;
import 'package:xceleration/coach/flows/PreRaceFlow/controller/pre_race_controller.dart'
    as _i8;
import 'package:xceleration/coach/race_results/model/team_record.dart' as _i13;
import 'package:xceleration/coach/race_screen/controller/race_screen_controller.dart'
    as _i7;
import 'package:xceleration/coach/races_screen/controller/races_controller.dart'
    as _i15;
import 'package:xceleration/core/services/geo_location_service.dart' as _i18;
import 'package:xceleration/core/services/tutorial_manager.dart' as _i6;
import 'package:xceleration/core/utils/database_helper.dart' as _i2;
import 'package:xceleration/shared/models/database/base_models.dart' as _i3;
import 'package:xceleration/shared/models/database/master_race.dart' as _i11;
import 'package:xceleration/shared/services/race_results_service.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeDatabaseHelper_0 extends _i1.SmartFake
    implements _i2.DatabaseHelper {
  _FakeDatabaseHelper_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeRace_1 extends _i1.SmartFake implements _i3.Race {
  _FakeRace_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeRaceResultsData_2 extends _i1.SmartFake
    implements _i4.RaceResultsData {
  _FakeRaceResultsData_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeTextEditingController_3 extends _i1.SmartFake
    implements _i5.TextEditingController {
  _FakeTextEditingController_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeTutorialManager_4 extends _i1.SmartFake
    implements _i6.TutorialManager {
  _FakeTutorialManager_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeBuildContext_5 extends _i1.SmartFake implements _i5.BuildContext {
  _FakeBuildContext_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeRaceController_6 extends _i1.SmartFake
    implements _i7.RaceController {
  _FakeRaceController_6(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePreRaceController_7 extends _i1.SmartFake
    implements _i8.PreRaceController {
  _FakePreRaceController_7(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePostRaceController_8 extends _i1.SmartFake
    implements _i9.PostRaceController {
  _FakePostRaceController_8(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePosition_9 extends _i1.SmartFake implements _i10.Position {
  _FakePosition_9(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [MasterRace].
///
/// See the documentation for Mockito's code generation for more information.
class MockMasterRace extends _i1.Mock implements _i11.MasterRace {
  MockMasterRace() {
    _i1.throwOnMissingStub(this);
  }

  @override
  int get raceId => (super.noSuchMethod(
        Invocation.getter(#raceId),
        returnValue: 0,
      ) as int);

  @override
  _i2.DatabaseHelper get db => (super.noSuchMethod(
        Invocation.getter(#db),
        returnValue: _FakeDatabaseHelper_0(
          this,
          Invocation.getter(#db),
        ),
      ) as _i2.DatabaseHelper);

  @override
  _i12.Future<_i3.Race> get race => (super.noSuchMethod(
        Invocation.getter(#race),
        returnValue: _i12.Future<_i3.Race>.value(_FakeRace_1(
          this,
          Invocation.getter(#race),
        )),
      ) as _i12.Future<_i3.Race>);

  @override
  _i12.Future<List<_i3.RaceParticipant>> get raceParticipants =>
      (super.noSuchMethod(
        Invocation.getter(#raceParticipants),
        returnValue: _i12.Future<List<_i3.RaceParticipant>>.value(
            <_i3.RaceParticipant>[]),
      ) as _i12.Future<List<_i3.RaceParticipant>>);

  @override
  _i12.Future<List<_i3.RaceRunner>> get raceRunners => (super.noSuchMethod(
        Invocation.getter(#raceRunners),
        returnValue:
            _i12.Future<List<_i3.RaceRunner>>.value(<_i3.RaceRunner>[]),
      ) as _i12.Future<List<_i3.RaceRunner>>);

  @override
  _i12.Future<List<_i3.Team>> get teams => (super.noSuchMethod(
        Invocation.getter(#teams),
        returnValue: _i12.Future<List<_i3.Team>>.value(<_i3.Team>[]),
      ) as _i12.Future<List<_i3.Team>>);

  @override
  _i12.Future<Map<_i3.Team, List<_i3.RaceRunner>>> get teamtoRaceRunnersMap =>
      (super.noSuchMethod(
        Invocation.getter(#teamtoRaceRunnersMap),
        returnValue: _i12.Future<Map<_i3.Team, List<_i3.RaceRunner>>>.value(
            <_i3.Team, List<_i3.RaceRunner>>{}),
      ) as _i12.Future<Map<_i3.Team, List<_i3.RaceRunner>>>);

  @override
  _i12.Future<Map<_i3.Team, List<_i3.RaceRunner>>> get filteredSearchResults =>
      (super.noSuchMethod(
        Invocation.getter(#filteredSearchResults),
        returnValue: _i12.Future<Map<_i3.Team, List<_i3.RaceRunner>>>.value(
            <_i3.Team, List<_i3.RaceRunner>>{}),
      ) as _i12.Future<Map<_i3.Team, List<_i3.RaceRunner>>>);

  @override
  _i12.Future<List<_i3.RaceResult>> get results => (super.noSuchMethod(
        Invocation.getter(#results),
        returnValue:
            _i12.Future<List<_i3.RaceResult>>.value(<_i3.RaceResult>[]),
      ) as _i12.Future<List<_i3.RaceResult>>);

  @override
  _i12.Future<List<_i13.TeamRecord>> get teamStandings => (super.noSuchMethod(
        Invocation.getter(#teamStandings),
        returnValue:
            _i12.Future<List<_i13.TeamRecord>>.value(<_i13.TeamRecord>[]),
      ) as _i12.Future<List<_i13.TeamRecord>>);

  @override
  _i12.Future<_i4.RaceResultsData> get raceResultsData => (super.noSuchMethod(
        Invocation.getter(#raceResultsData),
        returnValue:
            _i12.Future<_i4.RaceResultsData>.value(_FakeRaceResultsData_2(
          this,
          Invocation.getter(#raceResultsData),
        )),
      ) as _i12.Future<_i4.RaceResultsData>);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  _i12.Future<_i3.RaceRunner?> getRaceRunnerFromRaceParticipant(
          _i3.RaceParticipant? raceParticipant) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRaceRunnerFromRaceParticipant,
          [raceParticipant],
        ),
        returnValue: _i12.Future<_i3.RaceRunner?>.value(),
      ) as _i12.Future<_i3.RaceRunner?>);

  @override
  _i12.Future<void> updateRaceParticipant(
          _i3.RaceParticipant? raceParticipant) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateRaceParticipant,
          [raceParticipant],
        ),
        returnValue: _i12.Future<void>.value(),
        returnValueForMissingStub: _i12.Future<void>.value(),
      ) as _i12.Future<void>);

  @override
  _i12.Future<void> addRaceParticipant(_i3.RaceParticipant? raceParticipant) =>
      (super.noSuchMethod(
        Invocation.method(
          #addRaceParticipant,
          [raceParticipant],
        ),
        returnValue: _i12.Future<void>.value(),
        returnValueForMissingStub: _i12.Future<void>.value(),
      ) as _i12.Future<void>);

  @override
  _i12.Future<void> addRaceParticipantsBulk(
          List<_i3.RaceParticipant>? raceParticipants) =>
      (super.noSuchMethod(
        Invocation.method(
          #addRaceParticipantsBulk,
          [raceParticipants],
        ),
        returnValue: _i12.Future<void>.value(),
        returnValueForMissingStub: _i12.Future<void>.value(),
      ) as _i12.Future<void>);

  @override
  _i12.Future<void> removeRaceParticipant(
          _i3.RaceParticipant? raceParticipant) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeRaceParticipant,
          [raceParticipant],
        ),
        returnValue: _i12.Future<void>.value(),
        returnValueForMissingStub: _i12.Future<void>.value(),
      ) as _i12.Future<void>);

  @override
  _i12.Future<void> addTeamParticipant(_i3.TeamParticipant? teamParticipant) =>
      (super.noSuchMethod(
        Invocation.method(
          #addTeamParticipant,
          [teamParticipant],
        ),
        returnValue: _i12.Future<void>.value(),
        returnValueForMissingStub: _i12.Future<void>.value(),
      ) as _i12.Future<void>);

  @override
  _i12.Future<void> removeTeamFromRace(_i3.TeamParticipant? teamParticipant) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeTeamFromRace,
          [teamParticipant],
        ),
        returnValue: _i12.Future<void>.value(),
        returnValueForMissingStub: _i12.Future<void>.value(),
      ) as _i12.Future<void>);

  @override
  _i12.Future<void> updateRace(_i3.Race? race) => (super.noSuchMethod(
        Invocation.method(
          #updateRace,
          [race],
        ),
        returnValue: _i12.Future<void>.value(),
        returnValueForMissingStub: _i12.Future<void>.value(),
      ) as _i12.Future<void>);

  @override
  _i12.Future<void> removeRaceRunner(_i3.RaceRunner? raceRunner) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeRaceRunner,
          [raceRunner],
        ),
        returnValue: _i12.Future<void>.value(),
        returnValueForMissingStub: _i12.Future<void>.value(),
      ) as _i12.Future<void>);

  @override
  _i12.Future<void> addResult(_i3.RaceResult? result) => (super.noSuchMethod(
        Invocation.method(
          #addResult,
          [result],
        ),
        returnValue: _i12.Future<void>.value(),
        returnValueForMissingStub: _i12.Future<void>.value(),
      ) as _i12.Future<void>);

  @override
  _i12.Future<void> saveResults(List<_i3.RaceResult>? results) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveResults,
          [results],
        ),
        returnValue: _i12.Future<void>.value(),
        returnValueForMissingStub: _i12.Future<void>.value(),
      ) as _i12.Future<void>);

  @override
  _i12.Future<_i3.Team?> getTeamByName(String? teamName) => (super.noSuchMethod(
        Invocation.method(
          #getTeamByName,
          [teamName],
        ),
        returnValue: _i12.Future<_i3.Team?>.value(),
      ) as _i12.Future<_i3.Team?>);

  @override
  _i12.Future<_i3.RaceRunner?> getRaceRunnerByBib(String? bibNumber) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRaceRunnerByBib,
          [bibNumber],
        ),
        returnValue: _i12.Future<_i3.RaceRunner?>.value(),
      ) as _i12.Future<_i3.RaceRunner?>);

  @override
  _i12.Future<void> searchRaceRunners(
    String? query, [
    String? searchAttribute = 'all',
  ]) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchRaceRunners,
          [
            query,
            searchAttribute,
          ],
        ),
        returnValue: _i12.Future<void>.value(),
        returnValueForMissingStub: _i12.Future<void>.value(),
      ) as _i12.Future<void>);

  @override
  _i12.Future<List<_i3.Team>> getOtherTeams() => (super.noSuchMethod(
        Invocation.method(
          #getOtherTeams,
          [],
        ),
        returnValue: _i12.Future<List<_i3.Team>>.value(<_i3.Team>[]),
      ) as _i12.Future<List<_i3.Team>>);

  @override
  void invalidateCache() => super.noSuchMethod(
        Invocation.method(
          #invalidateCache,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addListener(_i14.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i14.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [RacesController].
///
/// See the documentation for Mockito's code generation for more information.
class MockRacesController extends _i1.Mock implements _i15.RacesController {
  MockRacesController() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<_i3.Race> get races => (super.noSuchMethod(
        Invocation.getter(#races),
        returnValue: <_i3.Race>[],
      ) as List<_i3.Race>);

  @override
  bool get isLocationButtonVisible => (super.noSuchMethod(
        Invocation.getter(#isLocationButtonVisible),
        returnValue: false,
      ) as bool);

  @override
  _i5.TextEditingController get nameController => (super.noSuchMethod(
        Invocation.getter(#nameController),
        returnValue: _FakeTextEditingController_3(
          this,
          Invocation.getter(#nameController),
        ),
      ) as _i5.TextEditingController);

  @override
  _i5.TextEditingController get locationController => (super.noSuchMethod(
        Invocation.getter(#locationController),
        returnValue: _FakeTextEditingController_3(
          this,
          Invocation.getter(#locationController),
        ),
      ) as _i5.TextEditingController);

  @override
  _i5.TextEditingController get dateController => (super.noSuchMethod(
        Invocation.getter(#dateController),
        returnValue: _FakeTextEditingController_3(
          this,
          Invocation.getter(#dateController),
        ),
      ) as _i5.TextEditingController);

  @override
  _i5.TextEditingController get distanceController => (super.noSuchMethod(
        Invocation.getter(#distanceController),
        returnValue: _FakeTextEditingController_3(
          this,
          Invocation.getter(#distanceController),
        ),
      ) as _i5.TextEditingController);

  @override
  _i5.TextEditingController get unitController => (super.noSuchMethod(
        Invocation.getter(#unitController),
        returnValue: _FakeTextEditingController_3(
          this,
          Invocation.getter(#unitController),
        ),
      ) as _i5.TextEditingController);

  @override
  _i5.TextEditingController get userlocationController => (super.noSuchMethod(
        Invocation.getter(#userlocationController),
        returnValue: _FakeTextEditingController_3(
          this,
          Invocation.getter(#userlocationController),
        ),
      ) as _i5.TextEditingController);

  @override
  List<_i5.TextEditingController> get teamControllers => (super.noSuchMethod(
        Invocation.getter(#teamControllers),
        returnValue: <_i5.TextEditingController>[],
      ) as List<_i5.TextEditingController>);

  @override
  List<_i14.Color> get teamColors => (super.noSuchMethod(
        Invocation.getter(#teamColors),
        returnValue: <_i14.Color>[],
      ) as List<_i14.Color>);

  @override
  String get unit => (super.noSuchMethod(
        Invocation.getter(#unit),
        returnValue: _i16.dummyValue<String>(
          this,
          Invocation.getter(#unit),
        ),
      ) as String);

  @override
  _i6.TutorialManager get tutorialManager => (super.noSuchMethod(
        Invocation.getter(#tutorialManager),
        returnValue: _FakeTutorialManager_4(
          this,
          Invocation.getter(#tutorialManager),
        ),
      ) as _i6.TutorialManager);

  @override
  bool get canEdit => (super.noSuchMethod(
        Invocation.getter(#canEdit),
        returnValue: false,
      ) as bool);

  @override
  _i5.BuildContext get context => (super.noSuchMethod(
        Invocation.getter(#context),
        returnValue: _FakeBuildContext_5(
          this,
          Invocation.getter(#context),
        ),
      ) as _i5.BuildContext);

  @override
  set races(List<_i3.Race>? value) => super.noSuchMethod(
        Invocation.setter(
          #races,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set isLocationButtonVisible(bool? value) => super.noSuchMethod(
        Invocation.setter(
          #isLocationButtonVisible,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set unit(String? value) => super.noSuchMethod(
        Invocation.setter(
          #unit,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set nameError(String? value) => super.noSuchMethod(
        Invocation.setter(
          #nameError,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set locationError(String? value) => super.noSuchMethod(
        Invocation.setter(
          #locationError,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set dateError(String? value) => super.noSuchMethod(
        Invocation.setter(
          #dateError,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set distanceError(String? value) => super.noSuchMethod(
        Invocation.setter(
          #distanceError,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set teamsError(String? value) => super.noSuchMethod(
        Invocation.setter(
          #teamsError,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  void setContext(_i5.BuildContext? context) => super.noSuchMethod(
        Invocation.method(
          #setContext,
          [context],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void initState() => super.noSuchMethod(
        Invocation.method(
          #initState,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setupTutorials() => super.noSuchMethod(
        Invocation.method(
          #setupTutorials,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void updateLocationButtonVisibility() => super.noSuchMethod(
        Invocation.method(
          #updateLocationButtonVisibility,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addTeamField() => super.noSuchMethod(
        Invocation.method(
          #addTeamField,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i12.Future<void> showCreateRaceSheet(_i5.BuildContext? context) =>
      (super.noSuchMethod(
        Invocation.method(
          #showCreateRaceSheet,
          [context],
        ),
        returnValue: _i12.Future<void>.value(),
        returnValueForMissingStub: _i12.Future<void>.value(),
      ) as _i12.Future<void>);

  @override
  void validateName(
    dynamic name,
    _i5.StateSetter? setSheetState,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #validateName,
          [
            name,
            setSheetState,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void validateLocation(
    String? location,
    _i5.StateSetter? setSheetState,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #validateLocation,
          [
            location,
            setSheetState,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void validateDate(
    String? dateString,
    _i5.StateSetter? setSheetState,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #validateDate,
          [
            dateString,
            setSheetState,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void validateDistance(
    String? distanceString,
    _i5.StateSetter? setSheetState,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #validateDistance,
          [
            distanceString,
            setSheetState,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void resetControllers() => super.noSuchMethod(
        Invocation.method(
          #resetControllers,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool validateRaceName() => (super.noSuchMethod(
        Invocation.method(
          #validateRaceName,
          [],
        ),
        returnValue: false,
      ) as bool);

  @override
  bool validateRaceCreation() => (super.noSuchMethod(
        Invocation.method(
          #validateRaceCreation,
          [],
        ),
        returnValue: false,
      ) as bool);

  @override
  _i12.Future<void> getCurrentLocation() => (super.noSuchMethod(
        Invocation.method(
          #getCurrentLocation,
          [],
        ),
        returnValue: _i12.Future<void>.value(),
        returnValueForMissingStub: _i12.Future<void>.value(),
      ) as _i12.Future<void>);

  @override
  _i12.Future<void> selectDate(_i5.BuildContext? context) =>
      (super.noSuchMethod(
        Invocation.method(
          #selectDate,
          [context],
        ),
        returnValue: _i12.Future<void>.value(),
        returnValueForMissingStub: _i12.Future<void>.value(),
      ) as _i12.Future<void>);

  @override
  void showColorPicker(
    _i5.StateSetter? setSheetState,
    _i5.TextEditingController? controller,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #showColorPicker,
          [
            setSheetState,
            controller,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i12.Future<void> editRace(_i3.Race? race) => (super.noSuchMethod(
        Invocation.method(
          #editRace,
          [race],
        ),
        returnValue: _i12.Future<void>.value(),
        returnValueForMissingStub: _i12.Future<void>.value(),
      ) as _i12.Future<void>);

  @override
  _i12.Future<void> deleteRace(_i3.Race? race) => (super.noSuchMethod(
        Invocation.method(
          #deleteRace,
          [race],
        ),
        returnValue: _i12.Future<void>.value(),
        returnValueForMissingStub: _i12.Future<void>.value(),
      ) as _i12.Future<void>);

  @override
  _i12.Future<int> createRace(_i3.Race? race) => (super.noSuchMethod(
        Invocation.method(
          #createRace,
          [race],
        ),
        returnValue: _i12.Future<int>.value(0),
      ) as _i12.Future<int>);

  @override
  _i12.Future<void> updateRace(_i3.Race? race) => (super.noSuchMethod(
        Invocation.method(
          #updateRace,
          [race],
        ),
        returnValue: _i12.Future<void>.value(),
        returnValueForMissingStub: _i12.Future<void>.value(),
      ) as _i12.Future<void>);

  @override
  _i12.Future<void> loadRaces() => (super.noSuchMethod(
        Invocation.method(
          #loadRaces,
          [],
        ),
        returnValue: _i12.Future<void>.value(),
        returnValueForMissingStub: _i12.Future<void>.value(),
      ) as _i12.Future<void>);

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addListener(_i14.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i14.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [MasterFlowController].
///
/// See the documentation for Mockito's code generation for more information.
class MockMasterFlowController extends _i1.Mock
    implements _i17.MasterFlowController {
  MockMasterFlowController() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.RaceController get raceController => (super.noSuchMethod(
        Invocation.getter(#raceController),
        returnValue: _FakeRaceController_6(
          this,
          Invocation.getter(#raceController),
        ),
      ) as _i7.RaceController);

  @override
  _i8.PreRaceController get preRaceController => (super.noSuchMethod(
        Invocation.getter(#preRaceController),
        returnValue: _FakePreRaceController_7(
          this,
          Invocation.getter(#preRaceController),
        ),
      ) as _i8.PreRaceController);

  @override
  _i9.PostRaceController get postRaceController => (super.noSuchMethod(
        Invocation.getter(#postRaceController),
        returnValue: _FakePostRaceController_8(
          this,
          Invocation.getter(#postRaceController),
        ),
      ) as _i9.PostRaceController);

  @override
  set preRaceController(_i8.PreRaceController? value) => super.noSuchMethod(
        Invocation.setter(
          #preRaceController,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set postRaceController(_i9.PostRaceController? value) => super.noSuchMethod(
        Invocation.setter(
          #postRaceController,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i12.Future<void> continueRaceFlow(_i5.BuildContext? context) =>
      (super.noSuchMethod(
        Invocation.method(
          #continueRaceFlow,
          [context],
        ),
        returnValue: _i12.Future<void>.value(),
        returnValueForMissingStub: _i12.Future<void>.value(),
      ) as _i12.Future<void>);

  @override
  _i12.Future<void> updateRaceFlowState(
    _i5.BuildContext? context,
    String? newState,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateRaceFlowState,
          [
            context,
            newState,
          ],
        ),
        returnValue: _i12.Future<void>.value(),
        returnValueForMissingStub: _i12.Future<void>.value(),
      ) as _i12.Future<void>);

  @override
  _i12.Future<bool> handleFlowNavigation(
    _i5.BuildContext? context,
    String? flowState,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #handleFlowNavigation,
          [
            context,
            flowState,
          ],
        ),
        returnValue: _i12.Future<bool>.value(false),
      ) as _i12.Future<bool>);
}

/// A class which mocks [IGeoLocationService].
///
/// See the documentation for Mockito's code generation for more information.
class MockIGeoLocationService extends _i1.Mock
    implements _i18.IGeoLocationService {
  MockIGeoLocationService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i12.Future<_i10.LocationPermission> checkPermission() => (super.noSuchMethod(
        Invocation.method(
          #checkPermission,
          [],
        ),
        returnValue: _i12.Future<_i10.LocationPermission>.value(
            _i10.LocationPermission.denied),
      ) as _i12.Future<_i10.LocationPermission>);

  @override
  _i12.Future<_i10.LocationPermission> requestPermission() =>
      (super.noSuchMethod(
        Invocation.method(
          #requestPermission,
          [],
        ),
        returnValue: _i12.Future<_i10.LocationPermission>.value(
            _i10.LocationPermission.denied),
      ) as _i12.Future<_i10.LocationPermission>);

  @override
  _i12.Future<bool> isLocationServiceEnabled() => (super.noSuchMethod(
        Invocation.method(
          #isLocationServiceEnabled,
          [],
        ),
        returnValue: _i12.Future<bool>.value(false),
      ) as _i12.Future<bool>);

  @override
  _i12.Future<_i10.Position> getCurrentPosition() => (super.noSuchMethod(
        Invocation.method(
          #getCurrentPosition,
          [],
        ),
        returnValue: _i12.Future<_i10.Position>.value(_FakePosition_9(
          this,
          Invocation.method(
            #getCurrentPosition,
            [],
          ),
        )),
      ) as _i12.Future<_i10.Position>);

  @override
  _i12.Future<List<_i19.Placemark>> placemarkFromCoordinates(
    double? lat,
    double? lng,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #placemarkFromCoordinates,
          [
            lat,
            lng,
          ],
        ),
        returnValue:
            _i12.Future<List<_i19.Placemark>>.value(<_i19.Placemark>[]),
      ) as _i12.Future<List<_i19.Placemark>>);
}
