// Mocks generated by Mockito 5.4.6 from annotations
// in xceleration/test/unit/coach/race_screen/controller/race_screen_controller_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i8;
import 'dart:ui' as _i13;

import 'package:flutter/material.dart' as _i16;
import 'package:mockito/mockito.dart' as _i1;
import 'package:xceleration/coach/flows/controller/flow_controller.dart'
    as _i15;
import 'package:xceleration/coach/flows/PostRaceFlow/controller/post_race_controller.dart'
    as _i7;
import 'package:xceleration/coach/flows/PreRaceFlow/controller/pre_race_controller.dart'
    as _i6;
import 'package:xceleration/coach/race_results/model/team_record.dart' as _i12;
import 'package:xceleration/coach/race_screen/controller/race_form_state.dart'
    as _i10;
import 'package:xceleration/coach/race_screen/controller/race_geo_controller.dart'
    as _i21;
import 'package:xceleration/coach/race_screen/controller/race_screen_controller.dart'
    as _i5;
import 'package:xceleration/coach/races_screen/controller/i_parent_race_controller.dart'
    as _i14;
import 'package:xceleration/core/services/date_picker_service.dart' as _i17;
import 'package:xceleration/core/services/device_connection_service.dart'
    as _i9;
import 'package:xceleration/core/services/event_bus.dart' as _i18;
import 'package:xceleration/core/services/i_device_connection_factory.dart'
    as _i19;
import 'package:xceleration/core/utils/database_helper.dart' as _i2;
import 'package:xceleration/core/utils/enums.dart' as _i20;
import 'package:xceleration/shared/models/database/base_models.dart' as _i3;
import 'package:xceleration/shared/models/database/master_race.dart' as _i11;
import 'package:xceleration/shared/services/race_results_service.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeDatabaseHelper_0 extends _i1.SmartFake
    implements _i2.DatabaseHelper {
  _FakeDatabaseHelper_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeRace_1 extends _i1.SmartFake implements _i3.Race {
  _FakeRace_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeRaceResultsData_2 extends _i1.SmartFake
    implements _i4.RaceResultsData {
  _FakeRaceResultsData_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeRaceController_3 extends _i1.SmartFake
    implements _i5.RaceController {
  _FakeRaceController_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePreRaceController_4 extends _i1.SmartFake
    implements _i6.PreRaceController {
  _FakePreRaceController_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePostRaceController_5 extends _i1.SmartFake
    implements _i7.PostRaceController {
  _FakePostRaceController_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeStreamSubscription_6<T1> extends _i1.SmartFake
    implements _i8.StreamSubscription<T1> {
  _FakeStreamSubscription_6(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDevicesManager_7 extends _i1.SmartFake
    implements _i9.DevicesManager {
  _FakeDevicesManager_7(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeRaceFormState_8 extends _i1.SmartFake implements _i10.RaceFormState {
  _FakeRaceFormState_8(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [MasterRace].
///
/// See the documentation for Mockito's code generation for more information.
class MockMasterRace extends _i1.Mock implements _i11.MasterRace {
  MockMasterRace() {
    _i1.throwOnMissingStub(this);
  }

  @override
  int get raceId => (super.noSuchMethod(
        Invocation.getter(#raceId),
        returnValue: 0,
      ) as int);

  @override
  _i2.DatabaseHelper get db => (super.noSuchMethod(
        Invocation.getter(#db),
        returnValue: _FakeDatabaseHelper_0(
          this,
          Invocation.getter(#db),
        ),
      ) as _i2.DatabaseHelper);

  @override
  _i8.Future<_i3.Race> get race => (super.noSuchMethod(
        Invocation.getter(#race),
        returnValue: _i8.Future<_i3.Race>.value(_FakeRace_1(
          this,
          Invocation.getter(#race),
        )),
      ) as _i8.Future<_i3.Race>);

  @override
  _i8.Future<List<_i3.RaceParticipant>> get raceParticipants =>
      (super.noSuchMethod(
        Invocation.getter(#raceParticipants),
        returnValue: _i8.Future<List<_i3.RaceParticipant>>.value(
            <_i3.RaceParticipant>[]),
      ) as _i8.Future<List<_i3.RaceParticipant>>);

  @override
  _i8.Future<List<_i3.RaceRunner>> get raceRunners => (super.noSuchMethod(
        Invocation.getter(#raceRunners),
        returnValue: _i8.Future<List<_i3.RaceRunner>>.value(<_i3.RaceRunner>[]),
      ) as _i8.Future<List<_i3.RaceRunner>>);

  @override
  _i8.Future<List<_i3.Team>> get teams => (super.noSuchMethod(
        Invocation.getter(#teams),
        returnValue: _i8.Future<List<_i3.Team>>.value(<_i3.Team>[]),
      ) as _i8.Future<List<_i3.Team>>);

  @override
  _i8.Future<Map<_i3.Team, List<_i3.RaceRunner>>> get teamtoRaceRunnersMap =>
      (super.noSuchMethod(
        Invocation.getter(#teamtoRaceRunnersMap),
        returnValue: _i8.Future<Map<_i3.Team, List<_i3.RaceRunner>>>.value(
            <_i3.Team, List<_i3.RaceRunner>>{}),
      ) as _i8.Future<Map<_i3.Team, List<_i3.RaceRunner>>>);

  @override
  _i8.Future<Map<_i3.Team, List<_i3.RaceRunner>>> get filteredSearchResults =>
      (super.noSuchMethod(
        Invocation.getter(#filteredSearchResults),
        returnValue: _i8.Future<Map<_i3.Team, List<_i3.RaceRunner>>>.value(
            <_i3.Team, List<_i3.RaceRunner>>{}),
      ) as _i8.Future<Map<_i3.Team, List<_i3.RaceRunner>>>);

  @override
  _i8.Future<List<_i3.RaceResult>> get results => (super.noSuchMethod(
        Invocation.getter(#results),
        returnValue: _i8.Future<List<_i3.RaceResult>>.value(<_i3.RaceResult>[]),
      ) as _i8.Future<List<_i3.RaceResult>>);

  @override
  _i8.Future<List<_i12.TeamRecord>> get teamStandings => (super.noSuchMethod(
        Invocation.getter(#teamStandings),
        returnValue:
            _i8.Future<List<_i12.TeamRecord>>.value(<_i12.TeamRecord>[]),
      ) as _i8.Future<List<_i12.TeamRecord>>);

  @override
  _i8.Future<_i4.RaceResultsData> get raceResultsData => (super.noSuchMethod(
        Invocation.getter(#raceResultsData),
        returnValue:
            _i8.Future<_i4.RaceResultsData>.value(_FakeRaceResultsData_2(
          this,
          Invocation.getter(#raceResultsData),
        )),
      ) as _i8.Future<_i4.RaceResultsData>);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  _i8.Future<_i3.RaceRunner?> getRaceRunnerFromRaceParticipant(
          _i3.RaceParticipant? raceParticipant) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRaceRunnerFromRaceParticipant,
          [raceParticipant],
        ),
        returnValue: _i8.Future<_i3.RaceRunner?>.value(),
      ) as _i8.Future<_i3.RaceRunner?>);

  @override
  _i8.Future<void> updateRaceParticipant(
          _i3.RaceParticipant? raceParticipant) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateRaceParticipant,
          [raceParticipant],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> addRaceParticipant(_i3.RaceParticipant? raceParticipant) =>
      (super.noSuchMethod(
        Invocation.method(
          #addRaceParticipant,
          [raceParticipant],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> addRaceParticipantsBulk(
          List<_i3.RaceParticipant>? raceParticipants) =>
      (super.noSuchMethod(
        Invocation.method(
          #addRaceParticipantsBulk,
          [raceParticipants],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> removeRaceParticipant(
          _i3.RaceParticipant? raceParticipant) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeRaceParticipant,
          [raceParticipant],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> addTeamParticipant(_i3.TeamParticipant? teamParticipant) =>
      (super.noSuchMethod(
        Invocation.method(
          #addTeamParticipant,
          [teamParticipant],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> removeTeamFromRace(_i3.TeamParticipant? teamParticipant) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeTeamFromRace,
          [teamParticipant],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> updateRace(_i3.Race? race) => (super.noSuchMethod(
        Invocation.method(
          #updateRace,
          [race],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> removeRaceRunner(_i3.RaceRunner? raceRunner) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeRaceRunner,
          [raceRunner],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> addResult(_i3.RaceResult? result) => (super.noSuchMethod(
        Invocation.method(
          #addResult,
          [result],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> saveResults(List<_i3.RaceResult>? results) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveResults,
          [results],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<_i3.Team?> getTeamByName(String? teamName) => (super.noSuchMethod(
        Invocation.method(
          #getTeamByName,
          [teamName],
        ),
        returnValue: _i8.Future<_i3.Team?>.value(),
      ) as _i8.Future<_i3.Team?>);

  @override
  _i8.Future<_i3.RaceRunner?> getRaceRunnerByBib(String? bibNumber) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRaceRunnerByBib,
          [bibNumber],
        ),
        returnValue: _i8.Future<_i3.RaceRunner?>.value(),
      ) as _i8.Future<_i3.RaceRunner?>);

  @override
  _i8.Future<void> searchRaceRunners(
    String? query, [
    String? searchAttribute = 'all',
  ]) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchRaceRunners,
          [
            query,
            searchAttribute,
          ],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<_i3.Runner?> getRunnerByBib(String? bibNumber) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRunnerByBib,
          [bibNumber],
        ),
        returnValue: _i8.Future<_i3.Runner?>.value(),
      ) as _i8.Future<_i3.Runner?>);

  @override
  _i8.Future<int> createRunner(_i3.Runner? runner) => (super.noSuchMethod(
        Invocation.method(
          #createRunner,
          [runner],
        ),
        returnValue: _i8.Future<int>.value(0),
      ) as _i8.Future<int>);

  @override
  _i8.Future<void> addRunnerToTeam(
    int? teamId,
    int? runnerId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #addRunnerToTeam,
          [
            teamId,
            runnerId,
          ],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<List<_i3.Team>> getOtherTeams() => (super.noSuchMethod(
        Invocation.method(
          #getOtherTeams,
          [],
        ),
        returnValue: _i8.Future<List<_i3.Team>>.value(<_i3.Team>[]),
      ) as _i8.Future<List<_i3.Team>>);

  @override
  void invalidateCache() => super.noSuchMethod(
        Invocation.method(
          #invalidateCache,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addListener(_i13.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i13.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [IParentRaceController].
///
/// See the documentation for Mockito's code generation for more information.
class MockIParentRaceController extends _i1.Mock
    implements _i14.IParentRaceController {
  MockIParentRaceController() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get canEdit => (super.noSuchMethod(
        Invocation.getter(#canEdit),
        returnValue: false,
      ) as bool);

  @override
  _i8.Future<void> loadRaces() => (super.noSuchMethod(
        Invocation.method(
          #loadRaces,
          [],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);
}

/// A class which mocks [MasterFlowController].
///
/// See the documentation for Mockito's code generation for more information.
class MockMasterFlowController extends _i1.Mock
    implements _i15.MasterFlowController {
  MockMasterFlowController() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.RaceController get raceController => (super.noSuchMethod(
        Invocation.getter(#raceController),
        returnValue: _FakeRaceController_3(
          this,
          Invocation.getter(#raceController),
        ),
      ) as _i5.RaceController);

  @override
  _i6.PreRaceController get preRaceController => (super.noSuchMethod(
        Invocation.getter(#preRaceController),
        returnValue: _FakePreRaceController_4(
          this,
          Invocation.getter(#preRaceController),
        ),
      ) as _i6.PreRaceController);

  @override
  _i7.PostRaceController get postRaceController => (super.noSuchMethod(
        Invocation.getter(#postRaceController),
        returnValue: _FakePostRaceController_5(
          this,
          Invocation.getter(#postRaceController),
        ),
      ) as _i7.PostRaceController);

  @override
  set preRaceController(_i6.PreRaceController? value) => super.noSuchMethod(
        Invocation.setter(
          #preRaceController,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set postRaceController(_i7.PostRaceController? value) => super.noSuchMethod(
        Invocation.setter(
          #postRaceController,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i8.Future<void> updateRaceFlowState(
    _i16.BuildContext? context,
    String? newState,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateRaceFlowState,
          [
            context,
            newState,
          ],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> markCurrentFlowCompleted(_i16.BuildContext? context) =>
      (super.noSuchMethod(
        Invocation.method(
          #markCurrentFlowCompleted,
          [context],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> beginNextFlow(_i16.BuildContext? context) =>
      (super.noSuchMethod(
        Invocation.method(
          #beginNextFlow,
          [context],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> continueRaceFlow(_i16.BuildContext? context) =>
      (super.noSuchMethod(
        Invocation.method(
          #continueRaceFlow,
          [context],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<bool> handleFlowNavigation(
    _i16.BuildContext? context,
    String? flowState,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #handleFlowNavigation,
          [
            context,
            flowState,
          ],
        ),
        returnValue: _i8.Future<bool>.value(false),
      ) as _i8.Future<bool>);
}

/// A class which mocks [IDatePickerService].
///
/// See the documentation for Mockito's code generation for more information.
class MockIDatePickerService extends _i1.Mock
    implements _i17.IDatePickerService {
  MockIDatePickerService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.Future<DateTime?> pickDate(
    _i16.BuildContext? context, {
    DateTime? initialDate,
    DateTime? firstDate,
    DateTime? lastDate,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #pickDate,
          [context],
          {
            #initialDate: initialDate,
            #firstDate: firstDate,
            #lastDate: lastDate,
          },
        ),
        returnValue: _i8.Future<DateTime?>.value(),
      ) as _i8.Future<DateTime?>);
}

/// A class which mocks [IEventBus].
///
/// See the documentation for Mockito's code generation for more information.
class MockIEventBus extends _i1.Mock implements _i18.IEventBus {
  MockIEventBus() {
    _i1.throwOnMissingStub(this);
  }

  @override
  void publish(_i18.Event? event) => super.noSuchMethod(
        Invocation.method(
          #publish,
          [event],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void fire(
    String? eventType, [
    dynamic data,
  ]) =>
      super.noSuchMethod(
        Invocation.method(
          #fire,
          [
            eventType,
            data,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i8.StreamSubscription<_i18.Event> on<T>(
    String? eventType,
    void Function(_i18.Event)? onData,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #on,
          [
            eventType,
            onData,
          ],
        ),
        returnValue: _FakeStreamSubscription_6<_i18.Event>(
          this,
          Invocation.method(
            #on,
            [
              eventType,
              onData,
            ],
          ),
        ),
      ) as _i8.StreamSubscription<_i18.Event>);
}

/// A class which mocks [IDeviceConnectionFactory].
///
/// See the documentation for Mockito's code generation for more information.
class MockIDeviceConnectionFactory extends _i1.Mock
    implements _i19.IDeviceConnectionFactory {
  MockIDeviceConnectionFactory() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i9.DevicesManager createDevices(
    _i20.DeviceName? deviceName,
    _i20.DeviceType? deviceType, {
    String? data,
    bool? toSpectator,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createDevices,
          [
            deviceName,
            deviceType,
          ],
          {
            #data: data,
            #toSpectator: toSpectator,
          },
        ),
        returnValue: _FakeDevicesManager_7(
          this,
          Invocation.method(
            #createDevices,
            [
              deviceName,
              deviceType,
            ],
            {
              #data: data,
              #toSpectator: toSpectator,
            },
          ),
        ),
      ) as _i9.DevicesManager);
}

/// A class which mocks [RaceGeoController].
///
/// See the documentation for Mockito's code generation for more information.
class MockRaceGeoController extends _i1.Mock implements _i21.RaceGeoController {
  MockRaceGeoController() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isLocationButtonVisible => (super.noSuchMethod(
        Invocation.getter(#isLocationButtonVisible),
        returnValue: false,
      ) as bool);

  @override
  _i10.RaceFormState get form => (super.noSuchMethod(
        Invocation.getter(#form),
        returnValue: _FakeRaceFormState_8(
          this,
          Invocation.getter(#form),
        ),
      ) as _i10.RaceFormState);

  @override
  set isLocationButtonVisible(bool? value) => super.noSuchMethod(
        Invocation.setter(
          #isLocationButtonVisible,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  _i8.Future<void> getCurrentLocation(_i16.BuildContext? context) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCurrentLocation,
          [context],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  void updateLocationButtonVisibility() => super.noSuchMethod(
        Invocation.method(
          #updateLocationButtonVisibility,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addListener(_i13.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i13.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
