// Mocks generated by Mockito 5.4.6 from annotations
// in xceleration/test/unit/coach/races_screen/controller/races_controller_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i2;
import 'dart:ui' as _i12;

import 'package:flutter/material.dart' as _i6;
import 'package:geocoding/geocoding.dart' as _i10;
import 'package:geolocator/geolocator.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:xceleration/coach/races_screen/services/races_service.dart'
    as _i4;
import 'package:xceleration/core/services/auth_service.dart' as _i7;
import 'package:xceleration/core/services/color_picker_dialog_service.dart'
    as _i15;
import 'package:xceleration/core/services/date_picker_service.dart' as _i14;
import 'package:xceleration/core/services/event_bus.dart' as _i8;
import 'package:xceleration/core/services/geo_location_service.dart' as _i9;
import 'package:xceleration/core/services/post_frame_callback_scheduler.dart'
    as _i11;
import 'package:xceleration/core/services/tutorial_manager.dart' as _i13;
import 'package:xceleration/shared/models/database/race.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeStreamSubscription_0<T1> extends _i1.SmartFake
    implements _i2.StreamSubscription<T1> {
  _FakeStreamSubscription_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePosition_1 extends _i1.SmartFake implements _i3.Position {
  _FakePosition_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [IRacesService].
///
/// See the documentation for Mockito's code generation for more information.
class MockIRacesService extends _i1.Mock implements _i4.IRacesService {
  MockIRacesService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.Future<List<_i5.Race>> loadRaces() => (super.noSuchMethod(
        Invocation.method(
          #loadRaces,
          [],
        ),
        returnValue: _i2.Future<List<_i5.Race>>.value(<_i5.Race>[]),
      ) as _i2.Future<List<_i5.Race>>);

  @override
  _i2.Future<int> createRace(_i5.Race? race) => (super.noSuchMethod(
        Invocation.method(
          #createRace,
          [race],
        ),
        returnValue: _i2.Future<int>.value(0),
      ) as _i2.Future<int>);

  @override
  _i2.Future<void> updateRace(_i5.Race? race) => (super.noSuchMethod(
        Invocation.method(
          #updateRace,
          [race],
        ),
        returnValue: _i2.Future<void>.value(),
        returnValueForMissingStub: _i2.Future<void>.value(),
      ) as _i2.Future<void>);

  @override
  _i2.Future<void> deleteRace(int? raceId) => (super.noSuchMethod(
        Invocation.method(
          #deleteRace,
          [raceId],
        ),
        returnValue: _i2.Future<void>.value(),
        returnValueForMissingStub: _i2.Future<void>.value(),
      ) as _i2.Future<void>);

  @override
  String? validateName(String? name) => (super.noSuchMethod(Invocation.method(
        #validateName,
        [name],
      )) as String?);

  @override
  String? validateLocation(String? location) =>
      (super.noSuchMethod(Invocation.method(
        #validateLocation,
        [location],
      )) as String?);

  @override
  String? validateDate(String? dateString) =>
      (super.noSuchMethod(Invocation.method(
        #validateDate,
        [dateString],
      )) as String?);

  @override
  String? validateDistance(String? distanceString) =>
      (super.noSuchMethod(Invocation.method(
        #validateDistance,
        [distanceString],
      )) as String?);

  @override
  String? getFirstError({
    required _i6.TextEditingController? nameController,
    required _i6.TextEditingController? locationController,
    required _i6.TextEditingController? dateController,
    required _i6.TextEditingController? distanceController,
    required List<_i6.TextEditingController>? teamControllers,
  }) =>
      (super.noSuchMethod(Invocation.method(
        #getFirstError,
        [],
        {
          #nameController: nameController,
          #locationController: locationController,
          #dateController: dateController,
          #distanceController: distanceController,
          #teamControllers: teamControllers,
        },
      )) as String?);
}

/// A class which mocks [IAuthService].
///
/// See the documentation for Mockito's code generation for more information.
class MockIAuthService extends _i1.Mock implements _i7.IAuthService {
  MockIAuthService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isSignedIn => (super.noSuchMethod(
        Invocation.getter(#isSignedIn),
        returnValue: false,
      ) as bool);
}

/// A class which mocks [IEventBus].
///
/// See the documentation for Mockito's code generation for more information.
class MockIEventBus extends _i1.Mock implements _i8.IEventBus {
  MockIEventBus() {
    _i1.throwOnMissingStub(this);
  }

  @override
  void publish(_i8.Event? event) => super.noSuchMethod(
        Invocation.method(
          #publish,
          [event],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void fire(
    String? eventType, [
    dynamic data,
  ]) =>
      super.noSuchMethod(
        Invocation.method(
          #fire,
          [
            eventType,
            data,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i2.StreamSubscription<_i8.Event> on<T>(
    String? eventType,
    void Function(_i8.Event)? onData,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #on,
          [
            eventType,
            onData,
          ],
        ),
        returnValue: _FakeStreamSubscription_0<_i8.Event>(
          this,
          Invocation.method(
            #on,
            [
              eventType,
              onData,
            ],
          ),
        ),
      ) as _i2.StreamSubscription<_i8.Event>);
}

/// A class which mocks [IGeoLocationService].
///
/// See the documentation for Mockito's code generation for more information.
class MockIGeoLocationService extends _i1.Mock
    implements _i9.IGeoLocationService {
  MockIGeoLocationService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.Future<_i3.LocationPermission> checkPermission() => (super.noSuchMethod(
        Invocation.method(
          #checkPermission,
          [],
        ),
        returnValue: _i2.Future<_i3.LocationPermission>.value(
            _i3.LocationPermission.denied),
      ) as _i2.Future<_i3.LocationPermission>);

  @override
  _i2.Future<_i3.LocationPermission> requestPermission() => (super.noSuchMethod(
        Invocation.method(
          #requestPermission,
          [],
        ),
        returnValue: _i2.Future<_i3.LocationPermission>.value(
            _i3.LocationPermission.denied),
      ) as _i2.Future<_i3.LocationPermission>);

  @override
  _i2.Future<bool> isLocationServiceEnabled() => (super.noSuchMethod(
        Invocation.method(
          #isLocationServiceEnabled,
          [],
        ),
        returnValue: _i2.Future<bool>.value(false),
      ) as _i2.Future<bool>);

  @override
  _i2.Future<_i3.Position> getCurrentPosition() => (super.noSuchMethod(
        Invocation.method(
          #getCurrentPosition,
          [],
        ),
        returnValue: _i2.Future<_i3.Position>.value(_FakePosition_1(
          this,
          Invocation.method(
            #getCurrentPosition,
            [],
          ),
        )),
      ) as _i2.Future<_i3.Position>);

  @override
  _i2.Future<List<_i10.Placemark>> placemarkFromCoordinates(
    double? lat,
    double? lng,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #placemarkFromCoordinates,
          [
            lat,
            lng,
          ],
        ),
        returnValue: _i2.Future<List<_i10.Placemark>>.value(<_i10.Placemark>[]),
      ) as _i2.Future<List<_i10.Placemark>>);
}

/// A class which mocks [IPostFrameCallbackScheduler].
///
/// See the documentation for Mockito's code generation for more information.
class MockIPostFrameCallbackScheduler extends _i1.Mock
    implements _i11.IPostFrameCallbackScheduler {
  MockIPostFrameCallbackScheduler() {
    _i1.throwOnMissingStub(this);
  }

  @override
  void addPostFrameCallback(_i12.VoidCallback? callback) => super.noSuchMethod(
        Invocation.method(
          #addPostFrameCallback,
          [callback],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [TutorialManager].
///
/// See the documentation for Mockito's code generation for more information.
class MockTutorialManager extends _i1.Mock implements _i13.TutorialManager {
  MockTutorialManager() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  void setTargetRect(_i12.Rect? rect) => super.noSuchMethod(
        Invocation.method(
          #setTargetRect,
          [rect],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void startTutorial(List<String>? coachMarkIds) => super.noSuchMethod(
        Invocation.method(
          #startTutorial,
          [coachMarkIds],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i2.Future<void> nextTutorial() => (super.noSuchMethod(
        Invocation.method(
          #nextTutorial,
          [],
        ),
        returnValue: _i2.Future<void>.value(),
        returnValueForMissingStub: _i2.Future<void>.value(),
      ) as _i2.Future<void>);

  @override
  _i2.Future<bool> hasSeenTutorial(String? id) => (super.noSuchMethod(
        Invocation.method(
          #hasSeenTutorial,
          [id],
        ),
        returnValue: _i2.Future<bool>.value(false),
      ) as _i2.Future<bool>);

  @override
  void addListener(_i12.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i12.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [IDatePickerService].
///
/// See the documentation for Mockito's code generation for more information.
class MockIDatePickerService extends _i1.Mock
    implements _i14.IDatePickerService {
  MockIDatePickerService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.Future<DateTime?> pickDate(_i6.BuildContext? context) =>
      (super.noSuchMethod(
        Invocation.method(
          #pickDate,
          [context],
        ),
        returnValue: _i2.Future<DateTime?>.value(),
      ) as _i2.Future<DateTime?>);
}

/// A class which mocks [IColorPickerDialogService].
///
/// See the documentation for Mockito's code generation for more information.
class MockIColorPickerDialogService extends _i1.Mock
    implements _i15.IColorPickerDialogService {
  MockIColorPickerDialogService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  void showColorPicker(
    _i6.BuildContext? context, {
    required _i12.Color? currentColor,
    required _i6.ValueChanged<_i12.Color>? onColorChanged,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #showColorPicker,
          [context],
          {
            #currentColor: currentColor,
            #onColorChanged: onColorChanged,
          },
        ),
        returnValueForMissingStub: null,
      );
}
