// Mocks generated by Mockito 5.4.6 from annotations
// in xceleration/test/unit/coach/runners_management_screen/controller/runners_management_controller_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;
import 'dart:ui' as _i7;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i11;
import 'package:xceleration/coach/race_results/model/team_record.dart' as _i6;
import 'package:xceleration/core/repositories/i_race_repository.dart' as _i10;
import 'package:xceleration/core/repositories/i_runner_repository.dart' as _i8;
import 'package:xceleration/core/repositories/i_team_repository.dart' as _i9;
import 'package:xceleration/shared/models/database/base_models.dart' as _i2;
import 'package:xceleration/shared/models/database/master_race.dart' as _i4;
import 'package:xceleration/shared/services/race_results_service.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeRace_0 extends _i1.SmartFake implements _i2.Race {
  _FakeRace_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeRaceResultsData_1 extends _i1.SmartFake
    implements _i3.RaceResultsData {
  _FakeRaceResultsData_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [MasterRace].
///
/// See the documentation for Mockito's code generation for more information.
class MockMasterRace extends _i1.Mock implements _i4.MasterRace {
  MockMasterRace() {
    _i1.throwOnMissingStub(this);
  }

  @override
  int get raceId => (super.noSuchMethod(
        Invocation.getter(#raceId),
        returnValue: 0,
      ) as int);

  @override
  _i5.Future<_i2.Race> get race => (super.noSuchMethod(
        Invocation.getter(#race),
        returnValue: _i5.Future<_i2.Race>.value(_FakeRace_0(
          this,
          Invocation.getter(#race),
        )),
      ) as _i5.Future<_i2.Race>);

  @override
  _i5.Future<List<_i2.RaceParticipant>> get raceParticipants =>
      (super.noSuchMethod(
        Invocation.getter(#raceParticipants),
        returnValue: _i5.Future<List<_i2.RaceParticipant>>.value(
            <_i2.RaceParticipant>[]),
      ) as _i5.Future<List<_i2.RaceParticipant>>);

  @override
  _i5.Future<List<_i2.RaceRunner>> get raceRunners => (super.noSuchMethod(
        Invocation.getter(#raceRunners),
        returnValue: _i5.Future<List<_i2.RaceRunner>>.value(<_i2.RaceRunner>[]),
      ) as _i5.Future<List<_i2.RaceRunner>>);

  @override
  _i5.Future<List<_i2.Team>> get teams => (super.noSuchMethod(
        Invocation.getter(#teams),
        returnValue: _i5.Future<List<_i2.Team>>.value(<_i2.Team>[]),
      ) as _i5.Future<List<_i2.Team>>);

  @override
  _i5.Future<Map<_i2.Team, List<_i2.RaceRunner>>> get teamtoRaceRunnersMap =>
      (super.noSuchMethod(
        Invocation.getter(#teamtoRaceRunnersMap),
        returnValue: _i5.Future<Map<_i2.Team, List<_i2.RaceRunner>>>.value(
            <_i2.Team, List<_i2.RaceRunner>>{}),
      ) as _i5.Future<Map<_i2.Team, List<_i2.RaceRunner>>>);

  @override
  _i5.Future<Map<_i2.Team, List<_i2.RaceRunner>>> get filteredSearchResults =>
      (super.noSuchMethod(
        Invocation.getter(#filteredSearchResults),
        returnValue: _i5.Future<Map<_i2.Team, List<_i2.RaceRunner>>>.value(
            <_i2.Team, List<_i2.RaceRunner>>{}),
      ) as _i5.Future<Map<_i2.Team, List<_i2.RaceRunner>>>);

  @override
  _i5.Future<List<_i2.RaceResult>> get results => (super.noSuchMethod(
        Invocation.getter(#results),
        returnValue: _i5.Future<List<_i2.RaceResult>>.value(<_i2.RaceResult>[]),
      ) as _i5.Future<List<_i2.RaceResult>>);

  @override
  _i5.Future<List<_i6.TeamRecord>> get teamStandings => (super.noSuchMethod(
        Invocation.getter(#teamStandings),
        returnValue: _i5.Future<List<_i6.TeamRecord>>.value(<_i6.TeamRecord>[]),
      ) as _i5.Future<List<_i6.TeamRecord>>);

  @override
  _i5.Future<_i3.RaceResultsData> get raceResultsData => (super.noSuchMethod(
        Invocation.getter(#raceResultsData),
        returnValue:
            _i5.Future<_i3.RaceResultsData>.value(_FakeRaceResultsData_1(
          this,
          Invocation.getter(#raceResultsData),
        )),
      ) as _i5.Future<_i3.RaceResultsData>);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  _i5.Future<_i2.RaceRunner?> getRaceRunnerFromRaceParticipant(
          _i2.RaceParticipant? raceParticipant) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRaceRunnerFromRaceParticipant,
          [raceParticipant],
        ),
        returnValue: _i5.Future<_i2.RaceRunner?>.value(),
      ) as _i5.Future<_i2.RaceRunner?>);

  @override
  _i5.Future<void> updateRaceParticipant(
          _i2.RaceParticipant? raceParticipant) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateRaceParticipant,
          [raceParticipant],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> addRaceParticipant(_i2.RaceParticipant? raceParticipant) =>
      (super.noSuchMethod(
        Invocation.method(
          #addRaceParticipant,
          [raceParticipant],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> addRaceParticipantsBulk(
          List<_i2.RaceParticipant>? raceParticipants) =>
      (super.noSuchMethod(
        Invocation.method(
          #addRaceParticipantsBulk,
          [raceParticipants],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> removeRaceParticipant(
          _i2.RaceParticipant? raceParticipant) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeRaceParticipant,
          [raceParticipant],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> addTeamParticipant(_i2.TeamParticipant? teamParticipant) =>
      (super.noSuchMethod(
        Invocation.method(
          #addTeamParticipant,
          [teamParticipant],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> removeTeamFromRace(_i2.TeamParticipant? teamParticipant) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeTeamFromRace,
          [teamParticipant],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> updateRace(_i2.Race? race) => (super.noSuchMethod(
        Invocation.method(
          #updateRace,
          [race],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> removeRaceRunner(_i2.RaceRunner? raceRunner) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeRaceRunner,
          [raceRunner],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> addResult(_i2.RaceResult? result) => (super.noSuchMethod(
        Invocation.method(
          #addResult,
          [result],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> saveResults(List<_i2.RaceResult>? results) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveResults,
          [results],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<_i2.Team?> getTeamByName(String? teamName) => (super.noSuchMethod(
        Invocation.method(
          #getTeamByName,
          [teamName],
        ),
        returnValue: _i5.Future<_i2.Team?>.value(),
      ) as _i5.Future<_i2.Team?>);

  @override
  _i5.Future<_i2.RaceRunner?> getRaceRunnerByBib(String? bibNumber) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRaceRunnerByBib,
          [bibNumber],
        ),
        returnValue: _i5.Future<_i2.RaceRunner?>.value(),
      ) as _i5.Future<_i2.RaceRunner?>);

  @override
  _i5.Future<void> searchRaceRunners(
    String? query, [
    String? searchAttribute = 'all',
  ]) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchRaceRunners,
          [
            query,
            searchAttribute,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<_i2.Runner?> getRunnerByBib(String? bibNumber) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRunnerByBib,
          [bibNumber],
        ),
        returnValue: _i5.Future<_i2.Runner?>.value(),
      ) as _i5.Future<_i2.Runner?>);

  @override
  _i5.Future<int> createRunner(_i2.Runner? runner) => (super.noSuchMethod(
        Invocation.method(
          #createRunner,
          [runner],
        ),
        returnValue: _i5.Future<int>.value(0),
      ) as _i5.Future<int>);

  @override
  _i5.Future<void> addRunnerToTeam(
    int? teamId,
    int? runnerId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #addRunnerToTeam,
          [
            teamId,
            runnerId,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<List<_i2.Team>> getOtherTeams() => (super.noSuchMethod(
        Invocation.method(
          #getOtherTeams,
          [],
        ),
        returnValue: _i5.Future<List<_i2.Team>>.value(<_i2.Team>[]),
      ) as _i5.Future<List<_i2.Team>>);

  @override
  void invalidateCache() => super.noSuchMethod(
        Invocation.method(
          #invalidateCache,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addListener(_i7.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i7.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [IRunnerRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockIRunnerRepository extends _i1.Mock implements _i8.IRunnerRepository {
  MockIRunnerRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<int> createRunner(_i2.Runner? runner) => (super.noSuchMethod(
        Invocation.method(
          #createRunner,
          [runner],
        ),
        returnValue: _i5.Future<int>.value(0),
      ) as _i5.Future<int>);

  @override
  _i5.Future<_i2.Runner?> getRunner(int? runnerId) => (super.noSuchMethod(
        Invocation.method(
          #getRunner,
          [runnerId],
        ),
        returnValue: _i5.Future<_i2.Runner?>.value(),
      ) as _i5.Future<_i2.Runner?>);

  @override
  _i5.Future<_i2.Runner?> getRunnerByBib(String? bibNumber) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRunnerByBib,
          [bibNumber],
        ),
        returnValue: _i5.Future<_i2.Runner?>.value(),
      ) as _i5.Future<_i2.Runner?>);

  @override
  _i5.Future<List<_i2.Runner>> getAllRunners() => (super.noSuchMethod(
        Invocation.method(
          #getAllRunners,
          [],
        ),
        returnValue: _i5.Future<List<_i2.Runner>>.value(<_i2.Runner>[]),
      ) as _i5.Future<List<_i2.Runner>>);

  @override
  _i5.Future<List<_i2.Runner>> searchRunners(String? query) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchRunners,
          [query],
        ),
        returnValue: _i5.Future<List<_i2.Runner>>.value(<_i2.Runner>[]),
      ) as _i5.Future<List<_i2.Runner>>);

  @override
  _i5.Future<void> updateRunner(_i2.Runner? runner) => (super.noSuchMethod(
        Invocation.method(
          #updateRunner,
          [runner],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> removeRunner(int? runnerId) => (super.noSuchMethod(
        Invocation.method(
          #removeRunner,
          [runnerId],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> deleteRunnerEverywhere(int? runnerId) => (super.noSuchMethod(
        Invocation.method(
          #deleteRunnerEverywhere,
          [runnerId],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<List<_i2.Runner>> getRunnersByBibAll(String? bib) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRunnersByBibAll,
          [bib],
        ),
        returnValue: _i5.Future<List<_i2.Runner>>.value(<_i2.Runner>[]),
      ) as _i5.Future<List<_i2.Runner>>);

  @override
  _i5.Future<void> addRunnerToTeam(
    int? teamId,
    int? runnerId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #addRunnerToTeam,
          [
            teamId,
            runnerId,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> removeRunnerFromTeam(
    int? teamId,
    int? runnerId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeRunnerFromTeam,
          [
            teamId,
            runnerId,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> setRunnerTeam(
    int? runnerId,
    int? newTeamId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #setRunnerTeam,
          [
            runnerId,
            newTeamId,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<_i2.Runner?> getTeamRunner(
    int? teamId,
    int? runnerId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTeamRunner,
          [
            teamId,
            runnerId,
          ],
        ),
        returnValue: _i5.Future<_i2.Runner?>.value(),
      ) as _i5.Future<_i2.Runner?>);

  @override
  _i5.Future<List<_i2.Runner>> getTeamRunners(int? teamId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTeamRunners,
          [teamId],
        ),
        returnValue: _i5.Future<List<_i2.Runner>>.value(<_i2.Runner>[]),
      ) as _i5.Future<List<_i2.Runner>>);

  @override
  _i5.Future<List<_i2.Team>> getRunnerTeams(int? runnerId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRunnerTeams,
          [runnerId],
        ),
        returnValue: _i5.Future<List<_i2.Team>>.value(<_i2.Team>[]),
      ) as _i5.Future<List<_i2.Team>>);
}

/// A class which mocks [ITeamRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockITeamRepository extends _i1.Mock implements _i9.ITeamRepository {
  MockITeamRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<int> createTeam(_i2.Team? team) => (super.noSuchMethod(
        Invocation.method(
          #createTeam,
          [team],
        ),
        returnValue: _i5.Future<int>.value(0),
      ) as _i5.Future<int>);

  @override
  _i5.Future<_i2.Team?> getTeam(int? teamId) => (super.noSuchMethod(
        Invocation.method(
          #getTeam,
          [teamId],
        ),
        returnValue: _i5.Future<_i2.Team?>.value(),
      ) as _i5.Future<_i2.Team?>);

  @override
  _i5.Future<_i2.Team?> getTeamByName(String? name) => (super.noSuchMethod(
        Invocation.method(
          #getTeamByName,
          [name],
        ),
        returnValue: _i5.Future<_i2.Team?>.value(),
      ) as _i5.Future<_i2.Team?>);

  @override
  _i5.Future<List<_i2.Team>> getAllTeams() => (super.noSuchMethod(
        Invocation.method(
          #getAllTeams,
          [],
        ),
        returnValue: _i5.Future<List<_i2.Team>>.value(<_i2.Team>[]),
      ) as _i5.Future<List<_i2.Team>>);

  @override
  _i5.Future<List<_i2.Team>> searchTeams(String? query) => (super.noSuchMethod(
        Invocation.method(
          #searchTeams,
          [query],
        ),
        returnValue: _i5.Future<List<_i2.Team>>.value(<_i2.Team>[]),
      ) as _i5.Future<List<_i2.Team>>);

  @override
  _i5.Future<void> updateTeam(_i2.Team? team) => (super.noSuchMethod(
        Invocation.method(
          #updateTeam,
          [team],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> deleteTeam(int? teamId) => (super.noSuchMethod(
        Invocation.method(
          #deleteTeam,
          [teamId],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
}

/// A class which mocks [IRaceRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockIRaceRepository extends _i1.Mock implements _i10.IRaceRepository {
  MockIRaceRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<int> createRace(_i2.Race? race) => (super.noSuchMethod(
        Invocation.method(
          #createRace,
          [race],
        ),
        returnValue: _i5.Future<int>.value(0),
      ) as _i5.Future<int>);

  @override
  _i5.Future<_i2.Race?> getRace(int? raceId) => (super.noSuchMethod(
        Invocation.method(
          #getRace,
          [raceId],
        ),
        returnValue: _i5.Future<_i2.Race?>.value(),
      ) as _i5.Future<_i2.Race?>);

  @override
  _i5.Future<List<_i2.Race>> getAllRaces() => (super.noSuchMethod(
        Invocation.method(
          #getAllRaces,
          [],
        ),
        returnValue: _i5.Future<List<_i2.Race>>.value(<_i2.Race>[]),
      ) as _i5.Future<List<_i2.Race>>);

  @override
  _i5.Future<void> updateRace(_i2.Race? race) => (super.noSuchMethod(
        Invocation.method(
          #updateRace,
          [race],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> deleteRace(int? raceId) => (super.noSuchMethod(
        Invocation.method(
          #deleteRace,
          [raceId],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> addTeamParticipantToRace(
          _i2.TeamParticipant? teamParticipant) =>
      (super.noSuchMethod(
        Invocation.method(
          #addTeamParticipantToRace,
          [teamParticipant],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> removeTeamParticipantFromRace(
          _i2.TeamParticipant? teamParticipant) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeTeamParticipantFromRace,
          [teamParticipant],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<_i2.Team?> getRaceTeamParticipant(
          _i2.TeamParticipant? teamParticipant) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRaceTeamParticipant,
          [teamParticipant],
        ),
        returnValue: _i5.Future<_i2.Team?>.value(),
      ) as _i5.Future<_i2.Team?>);

  @override
  _i5.Future<List<_i2.Team>> getRaceTeams(int? raceId) => (super.noSuchMethod(
        Invocation.method(
          #getRaceTeams,
          [raceId],
        ),
        returnValue: _i5.Future<List<_i2.Team>>.value(<_i2.Team>[]),
      ) as _i5.Future<List<_i2.Team>>);

  @override
  _i5.Future<void> addRaceParticipant(_i2.RaceParticipant? raceParticipant) =>
      (super.noSuchMethod(
        Invocation.method(
          #addRaceParticipant,
          [raceParticipant],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> updateRaceParticipant(
          _i2.RaceParticipant? raceParticipant) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateRaceParticipant,
          [raceParticipant],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> removeRaceParticipant(
          _i2.RaceParticipant? raceParticipant) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeRaceParticipant,
          [raceParticipant],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<_i2.RaceParticipant?> getRaceParticipant(
          _i2.RaceParticipant? raceParticipant) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRaceParticipant,
          [raceParticipant],
        ),
        returnValue: _i5.Future<_i2.RaceParticipant?>.value(),
      ) as _i5.Future<_i2.RaceParticipant?>);

  @override
  _i5.Future<List<_i2.RaceParticipant>> getRaceParticipants(int? raceId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRaceParticipants,
          [raceId],
        ),
        returnValue: _i5.Future<List<_i2.RaceParticipant>>.value(
            <_i2.RaceParticipant>[]),
      ) as _i5.Future<List<_i2.RaceParticipant>>);

  @override
  _i5.Future<_i2.RaceParticipant?> getRaceParticipantByBib(
    int? raceId,
    String? bibNumber,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRaceParticipantByBib,
          [
            raceId,
            bibNumber,
          ],
        ),
        returnValue: _i5.Future<_i2.RaceParticipant?>.value(),
      ) as _i5.Future<_i2.RaceParticipant?>);

  @override
  _i5.Future<List<_i2.RaceParticipant>> getRaceParticipantsByBibs(
    int? raceId,
    List<String>? bibNumbers,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRaceParticipantsByBibs,
          [
            raceId,
            bibNumbers,
          ],
        ),
        returnValue: _i5.Future<List<_i2.RaceParticipant>>.value(
            <_i2.RaceParticipant>[]),
      ) as _i5.Future<List<_i2.RaceParticipant>>);

  @override
  _i5.Future<List<_i2.RaceParticipant>> searchRaceParticipants(
    int? raceId,
    String? query, [
    String? searchParameter = 'all',
  ]) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchRaceParticipants,
          [
            raceId,
            query,
            searchParameter,
          ],
        ),
        returnValue: _i5.Future<List<_i2.RaceParticipant>>.value(
            <_i2.RaceParticipant>[]),
      ) as _i5.Future<List<_i2.RaceParticipant>>);

  @override
  _i5.Future<String> getRaceFlowState(int? raceId) => (super.noSuchMethod(
        Invocation.method(
          #getRaceFlowState,
          [raceId],
        ),
        returnValue: _i5.Future<String>.value(_i11.dummyValue<String>(
          this,
          Invocation.method(
            #getRaceFlowState,
            [raceId],
          ),
        )),
      ) as _i5.Future<String>);

  @override
  _i5.Future<void> updateRaceFlowState(
    int? raceId,
    String? flowState,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateRaceFlowState,
          [
            raceId,
            flowState,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> updateRaceParticipantTeam({
    required int? raceId,
    required int? runnerId,
    required int? newTeamId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateRaceParticipantTeam,
          [],
          {
            #raceId: raceId,
            #runnerId: runnerId,
            #newTeamId: newTeamId,
          },
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> updateRunnerWithTeams({
    required _i2.Runner? runner,
    int? newTeamId,
    int? raceIdForTeamUpdate,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateRunnerWithTeams,
          [],
          {
            #runner: runner,
            #newTeamId: newTeamId,
            #raceIdForTeamUpdate: raceIdForTeamUpdate,
          },
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
}
