// Mocks generated by Mockito 5.4.6 from annotations
// in xceleration/test/unit/coach/flows/post_race_flow/post_race_controller_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;
import 'dart:ui' as _i8;

import 'package:flutter/material.dart' as _i11;
import 'package:mockito/mockito.dart' as _i1;
import 'package:xceleration/coach/flows/post_race_flow/steps/load_results/controller/load_results_controller.dart'
    as _i9;
import 'package:xceleration/coach/race_results/model/team_record.dart' as _i7;
import 'package:xceleration/core/services/device_connection_service.dart'
    as _i5;
import 'package:xceleration/shared/models/database/base_models.dart' as _i2;
import 'package:xceleration/shared/models/database/master_race.dart' as _i4;
import 'package:xceleration/shared/models/timing_records/timing_chunk.dart'
    as _i10;
import 'package:xceleration/shared/services/race_results_service.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeRace_0 extends _i1.SmartFake implements _i2.Race {
  _FakeRace_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeRaceResultsData_1 extends _i1.SmartFake
    implements _i3.RaceResultsData {
  _FakeRaceResultsData_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeMasterRace_2 extends _i1.SmartFake implements _i4.MasterRace {
  _FakeMasterRace_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDevicesManager_3 extends _i1.SmartFake
    implements _i5.DevicesManager {
  _FakeDevicesManager_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [MasterRace].
///
/// See the documentation for Mockito's code generation for more information.
class MockMasterRace extends _i1.Mock implements _i4.MasterRace {
  MockMasterRace() {
    _i1.throwOnMissingStub(this);
  }

  @override
  int get raceId => (super.noSuchMethod(
        Invocation.getter(#raceId),
        returnValue: 0,
      ) as int);

  @override
  _i6.Future<_i2.Race> get race => (super.noSuchMethod(
        Invocation.getter(#race),
        returnValue: _i6.Future<_i2.Race>.value(_FakeRace_0(
          this,
          Invocation.getter(#race),
        )),
      ) as _i6.Future<_i2.Race>);

  @override
  _i6.Future<List<_i2.RaceParticipant>> get raceParticipants =>
      (super.noSuchMethod(
        Invocation.getter(#raceParticipants),
        returnValue: _i6.Future<List<_i2.RaceParticipant>>.value(
            <_i2.RaceParticipant>[]),
      ) as _i6.Future<List<_i2.RaceParticipant>>);

  @override
  _i6.Future<List<_i2.RaceRunner>> get raceRunners => (super.noSuchMethod(
        Invocation.getter(#raceRunners),
        returnValue: _i6.Future<List<_i2.RaceRunner>>.value(<_i2.RaceRunner>[]),
      ) as _i6.Future<List<_i2.RaceRunner>>);

  @override
  _i6.Future<List<_i2.Team>> get teams => (super.noSuchMethod(
        Invocation.getter(#teams),
        returnValue: _i6.Future<List<_i2.Team>>.value(<_i2.Team>[]),
      ) as _i6.Future<List<_i2.Team>>);

  @override
  _i6.Future<Map<_i2.Team, List<_i2.RaceRunner>>> get teamtoRaceRunnersMap =>
      (super.noSuchMethod(
        Invocation.getter(#teamtoRaceRunnersMap),
        returnValue: _i6.Future<Map<_i2.Team, List<_i2.RaceRunner>>>.value(
            <_i2.Team, List<_i2.RaceRunner>>{}),
      ) as _i6.Future<Map<_i2.Team, List<_i2.RaceRunner>>>);

  @override
  _i6.Future<Map<_i2.Team, List<_i2.RaceRunner>>> get filteredSearchResults =>
      (super.noSuchMethod(
        Invocation.getter(#filteredSearchResults),
        returnValue: _i6.Future<Map<_i2.Team, List<_i2.RaceRunner>>>.value(
            <_i2.Team, List<_i2.RaceRunner>>{}),
      ) as _i6.Future<Map<_i2.Team, List<_i2.RaceRunner>>>);

  @override
  _i6.Future<List<_i2.RaceResult>> get results => (super.noSuchMethod(
        Invocation.getter(#results),
        returnValue: _i6.Future<List<_i2.RaceResult>>.value(<_i2.RaceResult>[]),
      ) as _i6.Future<List<_i2.RaceResult>>);

  @override
  _i6.Future<List<_i7.TeamRecord>> get teamStandings => (super.noSuchMethod(
        Invocation.getter(#teamStandings),
        returnValue: _i6.Future<List<_i7.TeamRecord>>.value(<_i7.TeamRecord>[]),
      ) as _i6.Future<List<_i7.TeamRecord>>);

  @override
  _i6.Future<_i3.RaceResultsData> get raceResultsData => (super.noSuchMethod(
        Invocation.getter(#raceResultsData),
        returnValue:
            _i6.Future<_i3.RaceResultsData>.value(_FakeRaceResultsData_1(
          this,
          Invocation.getter(#raceResultsData),
        )),
      ) as _i6.Future<_i3.RaceResultsData>);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  _i6.Future<_i2.RaceRunner?> getRaceRunnerFromRaceParticipant(
          _i2.RaceParticipant? raceParticipant) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRaceRunnerFromRaceParticipant,
          [raceParticipant],
        ),
        returnValue: _i6.Future<_i2.RaceRunner?>.value(),
      ) as _i6.Future<_i2.RaceRunner?>);

  @override
  _i6.Future<void> updateRaceParticipant(
          _i2.RaceParticipant? raceParticipant) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateRaceParticipant,
          [raceParticipant],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> addRaceParticipant(_i2.RaceParticipant? raceParticipant) =>
      (super.noSuchMethod(
        Invocation.method(
          #addRaceParticipant,
          [raceParticipant],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> addRaceParticipantsBulk(
          List<_i2.RaceParticipant>? raceParticipants) =>
      (super.noSuchMethod(
        Invocation.method(
          #addRaceParticipantsBulk,
          [raceParticipants],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> removeRaceParticipant(
          _i2.RaceParticipant? raceParticipant) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeRaceParticipant,
          [raceParticipant],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> addTeamParticipant(_i2.TeamParticipant? teamParticipant) =>
      (super.noSuchMethod(
        Invocation.method(
          #addTeamParticipant,
          [teamParticipant],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> removeTeamFromRace(_i2.TeamParticipant? teamParticipant) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeTeamFromRace,
          [teamParticipant],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> updateRace(_i2.Race? race) => (super.noSuchMethod(
        Invocation.method(
          #updateRace,
          [race],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> removeRaceRunner(_i2.RaceRunner? raceRunner) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeRaceRunner,
          [raceRunner],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> addResult(_i2.RaceResult? result) => (super.noSuchMethod(
        Invocation.method(
          #addResult,
          [result],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> saveResults(List<_i2.RaceResult>? results) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveResults,
          [results],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<_i2.Team?> getTeamByName(String? teamName) => (super.noSuchMethod(
        Invocation.method(
          #getTeamByName,
          [teamName],
        ),
        returnValue: _i6.Future<_i2.Team?>.value(),
      ) as _i6.Future<_i2.Team?>);

  @override
  _i6.Future<_i2.RaceRunner?> getRaceRunnerByBib(String? bibNumber) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRaceRunnerByBib,
          [bibNumber],
        ),
        returnValue: _i6.Future<_i2.RaceRunner?>.value(),
      ) as _i6.Future<_i2.RaceRunner?>);

  @override
  _i6.Future<void> searchRaceRunners(
    String? query, [
    String? searchAttribute = 'all',
  ]) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchRaceRunners,
          [
            query,
            searchAttribute,
          ],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<_i2.Runner?> getRunnerByBib(String? bibNumber) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRunnerByBib,
          [bibNumber],
        ),
        returnValue: _i6.Future<_i2.Runner?>.value(),
      ) as _i6.Future<_i2.Runner?>);

  @override
  _i6.Future<int> createRunner(_i2.Runner? runner) => (super.noSuchMethod(
        Invocation.method(
          #createRunner,
          [runner],
        ),
        returnValue: _i6.Future<int>.value(0),
      ) as _i6.Future<int>);

  @override
  _i6.Future<void> addRunnerToTeam(
    int? teamId,
    int? runnerId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #addRunnerToTeam,
          [
            teamId,
            runnerId,
          ],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<List<_i2.Team>> getOtherTeams() => (super.noSuchMethod(
        Invocation.method(
          #getOtherTeams,
          [],
        ),
        returnValue: _i6.Future<List<_i2.Team>>.value(<_i2.Team>[]),
      ) as _i6.Future<List<_i2.Team>>);

  @override
  void invalidateCache() => super.noSuchMethod(
        Invocation.method(
          #invalidateCache,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addListener(_i8.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i8.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [LoadResultsController].
///
/// See the documentation for Mockito's code generation for more information.
class MockLoadResultsController extends _i1.Mock
    implements _i9.LoadResultsController {
  MockLoadResultsController() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.MasterRace get masterRace => (super.noSuchMethod(
        Invocation.getter(#masterRace),
        returnValue: _FakeMasterRace_2(
          this,
          Invocation.getter(#masterRace),
        ),
      ) as _i4.MasterRace);

  @override
  List<_i2.RaceResult> get results => (super.noSuchMethod(
        Invocation.getter(#results),
        returnValue: <_i2.RaceResult>[],
      ) as List<_i2.RaceResult>);

  @override
  _i5.DevicesManager get devices => (super.noSuchMethod(
        Invocation.getter(#devices),
        returnValue: _FakeDevicesManager_3(
          this,
          Invocation.getter(#devices),
        ),
      ) as _i5.DevicesManager);

  @override
  bool get resultsLoaded => (super.noSuchMethod(
        Invocation.getter(#resultsLoaded),
        returnValue: false,
      ) as bool);

  @override
  bool get hasBibConflicts => (super.noSuchMethod(
        Invocation.getter(#hasBibConflicts),
        returnValue: false,
      ) as bool);

  @override
  bool get hasTimingConflicts => (super.noSuchMethod(
        Invocation.getter(#hasTimingConflicts),
        returnValue: false,
      ) as bool);

  @override
  bool get hasError => (super.noSuchMethod(
        Invocation.getter(#hasError),
        returnValue: false,
      ) as bool);

  @override
  set results(List<_i2.RaceResult>? value) => super.noSuchMethod(
        Invocation.setter(
          #results,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set timingChunks(List<_i10.TimingChunk>? value) => super.noSuchMethod(
        Invocation.setter(
          #timingChunks,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set raceRunners(List<dynamic>? value) => super.noSuchMethod(
        Invocation.setter(
          #raceRunners,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set resultsLoaded(bool? value) => super.noSuchMethod(
        Invocation.setter(
          #resultsLoaded,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set hasBibConflicts(bool? value) => super.noSuchMethod(
        Invocation.setter(
          #hasBibConflicts,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set hasTimingConflicts(bool? value) => super.noSuchMethod(
        Invocation.setter(
          #hasTimingConflicts,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  void initialize() => super.noSuchMethod(
        Invocation.method(
          #initialize,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i6.Future<void> resetDevices() => (super.noSuchMethod(
        Invocation.method(
          #resetDevices,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> loadResults() => (super.noSuchMethod(
        Invocation.method(
          #loadResults,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> saveRaceResults(List<_i2.RaceResult>? results) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveRaceResults,
          [results],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> saveCurrentResults() => (super.noSuchMethod(
        Invocation.method(
          #saveCurrentResults,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> processReceivedData(_i11.BuildContext? context) =>
      (super.noSuchMethod(
        Invocation.method(
          #processReceivedData,
          [context],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> showBibConflictsSheet(_i11.BuildContext? context) =>
      (super.noSuchMethod(
        Invocation.method(
          #showBibConflictsSheet,
          [context],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> showTimingConflictsSheet(_i11.BuildContext? context) =>
      (super.noSuchMethod(
        Invocation.method(
          #showTimingConflictsSheet,
          [context],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  bool containsBibConflicts() => (super.noSuchMethod(
        Invocation.method(
          #containsBibConflicts,
          [],
        ),
        returnValue: false,
      ) as bool);

  @override
  bool containsTimingConflicts() => (super.noSuchMethod(
        Invocation.method(
          #containsTimingConflicts,
          [],
        ),
        returnValue: false,
      ) as bool);

  @override
  void addListener(_i8.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i8.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
