// Mocks generated by Mockito 5.4.6 from annotations
// in xceleration/test/unit/core/connection/controller/qr_connection_controller_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i7;

import 'package:barcode_scan2/barcode_scan2.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:xceleration/core/services/device_connection_service.dart'
    as _i2;
import 'package:xceleration/core/utils/barcode_scanner_interface.dart' as _i6;
import 'package:xceleration/core/utils/enums.dart' as _i4;
import 'package:xceleration/core/utils/platform_checker.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeDevicesManager_0 extends _i1.SmartFake
    implements _i2.DevicesManager {
  _FakeDevicesManager_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeScanResult_1 extends _i1.SmartFake implements _i3.ScanResult {
  _FakeScanResult_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [DevicesManager].
///
/// See the documentation for Mockito's code generation for more information.
class MockDevicesManager extends _i1.Mock implements _i2.DevicesManager {
  MockDevicesManager() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.DeviceName get currentDeviceName => (super.noSuchMethod(
        Invocation.getter(#currentDeviceName),
        returnValue: _i4.DeviceName.coach,
      ) as _i4.DeviceName);

  @override
  _i4.DeviceType get currentDeviceType => (super.noSuchMethod(
        Invocation.getter(#currentDeviceType),
        returnValue: _i4.DeviceType.advertiserDevice,
      ) as _i4.DeviceType);

  @override
  bool get toSpectator => (super.noSuchMethod(
        Invocation.getter(#toSpectator),
        returnValue: false,
      ) as bool);

  @override
  List<_i2.ConnectedDevice> get devices => (super.noSuchMethod(
        Invocation.getter(#devices),
        returnValue: <_i2.ConnectedDevice>[],
      ) as List<_i2.ConnectedDevice>);

  @override
  List<_i2.ConnectedDevice> get otherDevices => (super.noSuchMethod(
        Invocation.getter(#otherDevices),
        returnValue: <_i2.ConnectedDevice>[],
      ) as List<_i2.ConnectedDevice>);

  @override
  void reset() => super.noSuchMethod(
        Invocation.method(
          #reset,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool hasDevice(_i4.DeviceName? name) => (super.noSuchMethod(
        Invocation.method(
          #hasDevice,
          [name],
        ),
        returnValue: false,
      ) as bool);

  @override
  _i2.ConnectedDevice? getDevice(_i4.DeviceName? name) =>
      (super.noSuchMethod(Invocation.method(
        #getDevice,
        [name],
      )) as _i2.ConnectedDevice?);

  @override
  bool allDevicesFinished() => (super.noSuchMethod(
        Invocation.method(
          #allDevicesFinished,
          [],
        ),
        returnValue: false,
      ) as bool);

  @override
  _i2.DevicesManager copy() => (super.noSuchMethod(
        Invocation.method(
          #copy,
          [],
        ),
        returnValue: _FakeDevicesManager_0(
          this,
          Invocation.method(
            #copy,
            [],
          ),
        ),
      ) as _i2.DevicesManager);
}

/// A class which mocks [PlatformCheckerInterface].
///
/// See the documentation for Mockito's code generation for more information.
class MockPlatformCheckerInterface extends _i1.Mock
    implements _i5.PlatformCheckerInterface {
  MockPlatformCheckerInterface() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isAndroid => (super.noSuchMethod(
        Invocation.getter(#isAndroid),
        returnValue: false,
      ) as bool);

  @override
  bool get isIOS => (super.noSuchMethod(
        Invocation.getter(#isIOS),
        returnValue: false,
      ) as bool);
}

/// A class which mocks [BarcodeScannerInterface].
///
/// See the documentation for Mockito's code generation for more information.
class MockBarcodeScannerInterface extends _i1.Mock
    implements _i6.BarcodeScannerInterface {
  MockBarcodeScannerInterface() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Future<_i3.ScanResult> scan() => (super.noSuchMethod(
        Invocation.method(
          #scan,
          [],
        ),
        returnValue: _i7.Future<_i3.ScanResult>.value(_FakeScanResult_1(
          this,
          Invocation.method(
            #scan,
            [],
          ),
        )),
      ) as _i7.Future<_i3.ScanResult>);
}
