// Mocks generated by Mockito 5.4.6 from annotations
// in xceleration/test/unit/core/utils/google_drive_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:http/http.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;
import 'package:xceleration/core/services/connectivity_service.dart' as _i2;
import 'package:xceleration/core/utils/google_auth_service.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [ConnectivityService].
///
/// See the documentation for Mockito's code generation for more information.
class MockConnectivityService extends _i1.Mock
    implements _i2.ConnectivityService {
  MockConnectivityService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<bool> isOnline() => (super.noSuchMethod(
        Invocation.method(
          #isOnline,
          [],
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);
}

/// A class which mocks [GoogleAuthService].
///
/// See the documentation for Mockito's code generation for more information.
class MockGoogleAuthService extends _i1.Mock implements _i4.GoogleAuthService {
  MockGoogleAuthService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get hasValidIosToken => (super.noSuchMethod(
        Invocation.getter(#hasValidIosToken),
        returnValue: false,
      ) as bool);

  @override
  bool get hasValidWebToken => (super.noSuchMethod(
        Invocation.getter(#hasValidWebToken),
        returnValue: false,
      ) as bool);

  @override
  _i3.Future<String?> get iosAccessToken => (super.noSuchMethod(
        Invocation.getter(#iosAccessToken),
        returnValue: _i3.Future<String?>.value(),
      ) as _i3.Future<String?>);

  @override
  _i3.Future<String?> get webAccessToken => (super.noSuchMethod(
        Invocation.getter(#webAccessToken),
        returnValue: _i3.Future<String?>.value(),
      ) as _i3.Future<String?>);

  @override
  _i3.Future<_i5.Client?> getAuthClient() => (super.noSuchMethod(
        Invocation.method(
          #getAuthClient,
          [],
        ),
        returnValue: _i3.Future<_i5.Client?>.value(),
      ) as _i3.Future<_i5.Client?>);

  @override
  _i3.Future<bool> signIn() => (super.noSuchMethod(
        Invocation.method(
          #signIn,
          [],
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);

  @override
  _i3.Future<void> signOut() => (super.noSuchMethod(
        Invocation.method(
          #signOut,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}
