// Mocks generated by Mockito 5.4.6 from annotations
// in xceleration/test/unit/core/services/sync_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;
import 'package:sqflite/sqflite.dart' as _i2;
import 'package:supabase_flutter/supabase_flutter.dart' as _i3;
import 'package:xceleration/core/services/i_auth_service.dart' as _i9;
import 'package:xceleration/core/services/i_remote_api_client.dart' as _i8;
import 'package:xceleration/core/utils/i_database_helper.dart' as _i5;
import 'package:xceleration/shared/models/database/base_models.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeDatabase_0 extends _i1.SmartFake implements _i2.Database {
  _FakeDatabase_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSupabaseClient_1 extends _i1.SmartFake
    implements _i3.SupabaseClient {
  _FakeSupabaseClient_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeFuture_2<T1> extends _i1.SmartFake implements _i4.Future<T1> {
  _FakeFuture_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeQueryCursor_3 extends _i1.SmartFake implements _i2.QueryCursor {
  _FakeQueryCursor_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeBatch_4 extends _i1.SmartFake implements _i2.Batch {
  _FakeBatch_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeFunctionsClient_5 extends _i1.SmartFake
    implements _i3.FunctionsClient {
  _FakeFunctionsClient_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSupabaseStorageClient_6 extends _i1.SmartFake
    implements _i3.SupabaseStorageClient {
  _FakeSupabaseStorageClient_6(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeRealtimeClient_7 extends _i1.SmartFake
    implements _i3.RealtimeClient {
  _FakeRealtimeClient_7(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePostgrestClient_8 extends _i1.SmartFake
    implements _i3.PostgrestClient {
  _FakePostgrestClient_8(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeGoTrueClient_9 extends _i1.SmartFake implements _i3.GoTrueClient {
  _FakeGoTrueClient_9(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSupabaseQueryBuilder_10 extends _i1.SmartFake
    implements _i3.SupabaseQueryBuilder {
  _FakeSupabaseQueryBuilder_10(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSupabaseQuerySchema_11 extends _i1.SmartFake
    implements _i3.SupabaseQuerySchema {
  _FakeSupabaseQuerySchema_11(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePostgrestFilterBuilder_12<T1> extends _i1.SmartFake
    implements _i3.PostgrestFilterBuilder<T1> {
  _FakePostgrestFilterBuilder_12(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeRealtimeChannel_13 extends _i1.SmartFake
    implements _i3.RealtimeChannel {
  _FakeRealtimeChannel_13(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [IDatabaseHelper].
///
/// See the documentation for Mockito's code generation for more information.
class MockIDatabaseHelper extends _i1.Mock implements _i5.IDatabaseHelper {
  MockIDatabaseHelper() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Database> get databaseConn => (super.noSuchMethod(
        Invocation.getter(#databaseConn),
        returnValue: _i4.Future<_i2.Database>.value(_FakeDatabase_0(
          this,
          Invocation.getter(#databaseConn),
        )),
      ) as _i4.Future<_i2.Database>);

  @override
  _i4.Future<int> createRunner(_i6.Runner? runner) => (super.noSuchMethod(
        Invocation.method(
          #createRunner,
          [runner],
        ),
        returnValue: _i4.Future<int>.value(0),
      ) as _i4.Future<int>);

  @override
  _i4.Future<_i6.Runner?> getRunner(int? runnerId) => (super.noSuchMethod(
        Invocation.method(
          #getRunner,
          [runnerId],
        ),
        returnValue: _i4.Future<_i6.Runner?>.value(),
      ) as _i4.Future<_i6.Runner?>);

  @override
  _i4.Future<_i6.Runner?> getRunnerByBib(String? bibNumber) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRunnerByBib,
          [bibNumber],
        ),
        returnValue: _i4.Future<_i6.Runner?>.value(),
      ) as _i4.Future<_i6.Runner?>);

  @override
  _i4.Future<List<_i6.Runner>> getAllRunners() => (super.noSuchMethod(
        Invocation.method(
          #getAllRunners,
          [],
        ),
        returnValue: _i4.Future<List<_i6.Runner>>.value(<_i6.Runner>[]),
      ) as _i4.Future<List<_i6.Runner>>);

  @override
  _i4.Future<List<_i6.Runner>> searchRunners(String? query) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchRunners,
          [query],
        ),
        returnValue: _i4.Future<List<_i6.Runner>>.value(<_i6.Runner>[]),
      ) as _i4.Future<List<_i6.Runner>>);

  @override
  _i4.Future<void> updateRunner(_i6.Runner? runner) => (super.noSuchMethod(
        Invocation.method(
          #updateRunner,
          [runner],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> removeRunner(int? runnerId) => (super.noSuchMethod(
        Invocation.method(
          #removeRunner,
          [runnerId],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<int> createTeam(_i6.Team? team) => (super.noSuchMethod(
        Invocation.method(
          #createTeam,
          [team],
        ),
        returnValue: _i4.Future<int>.value(0),
      ) as _i4.Future<int>);

  @override
  _i4.Future<_i6.Team?> getTeam(int? teamId) => (super.noSuchMethod(
        Invocation.method(
          #getTeam,
          [teamId],
        ),
        returnValue: _i4.Future<_i6.Team?>.value(),
      ) as _i4.Future<_i6.Team?>);

  @override
  _i4.Future<_i6.Team?> getTeamByName(String? name) => (super.noSuchMethod(
        Invocation.method(
          #getTeamByName,
          [name],
        ),
        returnValue: _i4.Future<_i6.Team?>.value(),
      ) as _i4.Future<_i6.Team?>);

  @override
  _i4.Future<List<_i6.Team>> getAllTeams() => (super.noSuchMethod(
        Invocation.method(
          #getAllTeams,
          [],
        ),
        returnValue: _i4.Future<List<_i6.Team>>.value(<_i6.Team>[]),
      ) as _i4.Future<List<_i6.Team>>);

  @override
  _i4.Future<List<_i6.Team>> searchTeams(String? query) => (super.noSuchMethod(
        Invocation.method(
          #searchTeams,
          [query],
        ),
        returnValue: _i4.Future<List<_i6.Team>>.value(<_i6.Team>[]),
      ) as _i4.Future<List<_i6.Team>>);

  @override
  _i4.Future<void> updateTeam(_i6.Team? team) => (super.noSuchMethod(
        Invocation.method(
          #updateTeam,
          [team],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> deleteTeam(int? teamId) => (super.noSuchMethod(
        Invocation.method(
          #deleteTeam,
          [teamId],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<int> createRace(_i6.Race? race) => (super.noSuchMethod(
        Invocation.method(
          #createRace,
          [race],
        ),
        returnValue: _i4.Future<int>.value(0),
      ) as _i4.Future<int>);

  @override
  _i4.Future<_i6.Race?> getRace(int? raceId) => (super.noSuchMethod(
        Invocation.method(
          #getRace,
          [raceId],
        ),
        returnValue: _i4.Future<_i6.Race?>.value(),
      ) as _i4.Future<_i6.Race?>);

  @override
  _i4.Future<List<_i6.Race>> getAllRaces() => (super.noSuchMethod(
        Invocation.method(
          #getAllRaces,
          [],
        ),
        returnValue: _i4.Future<List<_i6.Race>>.value(<_i6.Race>[]),
      ) as _i4.Future<List<_i6.Race>>);

  @override
  _i4.Future<void> updateRace(_i6.Race? race) => (super.noSuchMethod(
        Invocation.method(
          #updateRace,
          [race],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> deleteRace(int? raceId) => (super.noSuchMethod(
        Invocation.method(
          #deleteRace,
          [raceId],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> addRunnerToTeam(
    int? teamId,
    int? runnerId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #addRunnerToTeam,
          [
            teamId,
            runnerId,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> removeRunnerFromTeam(
    int? teamId,
    int? runnerId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeRunnerFromTeam,
          [
            teamId,
            runnerId,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> setRunnerTeam(
    int? runnerId,
    int? newTeamId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #setRunnerTeam,
          [
            runnerId,
            newTeamId,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> updateRaceParticipantTeam({
    required int? raceId,
    required int? runnerId,
    required int? newTeamId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateRaceParticipantTeam,
          [],
          {
            #raceId: raceId,
            #runnerId: runnerId,
            #newTeamId: newTeamId,
          },
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> updateRunnerWithTeams({
    required _i6.Runner? runner,
    int? newTeamId,
    int? raceIdForTeamUpdate,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateRunnerWithTeams,
          [],
          {
            #runner: runner,
            #newTeamId: newTeamId,
            #raceIdForTeamUpdate: raceIdForTeamUpdate,
          },
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<_i6.Runner?> getTeamRunner(
    int? teamId,
    int? runnerId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTeamRunner,
          [
            teamId,
            runnerId,
          ],
        ),
        returnValue: _i4.Future<_i6.Runner?>.value(),
      ) as _i4.Future<_i6.Runner?>);

  @override
  _i4.Future<List<_i6.Runner>> getTeamRunners(int? teamId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTeamRunners,
          [teamId],
        ),
        returnValue: _i4.Future<List<_i6.Runner>>.value(<_i6.Runner>[]),
      ) as _i4.Future<List<_i6.Runner>>);

  @override
  _i4.Future<List<_i6.Team>> getRunnerTeams(int? runnerId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRunnerTeams,
          [runnerId],
        ),
        returnValue: _i4.Future<List<_i6.Team>>.value(<_i6.Team>[]),
      ) as _i4.Future<List<_i6.Team>>);

  @override
  _i4.Future<void> addTeamParticipantToRace(
          _i6.TeamParticipant? teamParticipant) =>
      (super.noSuchMethod(
        Invocation.method(
          #addTeamParticipantToRace,
          [teamParticipant],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> removeTeamParticipantFromRace(
          _i6.TeamParticipant? teamParticipant) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeTeamParticipantFromRace,
          [teamParticipant],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<_i6.Team?> getRaceTeamParticipant(
          _i6.TeamParticipant? teamParticipant) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRaceTeamParticipant,
          [teamParticipant],
        ),
        returnValue: _i4.Future<_i6.Team?>.value(),
      ) as _i4.Future<_i6.Team?>);

  @override
  _i4.Future<List<_i6.Team>> getRaceTeams(int? raceId) => (super.noSuchMethod(
        Invocation.method(
          #getRaceTeams,
          [raceId],
        ),
        returnValue: _i4.Future<List<_i6.Team>>.value(<_i6.Team>[]),
      ) as _i4.Future<List<_i6.Team>>);

  @override
  _i4.Future<void> addRaceParticipant(_i6.RaceParticipant? raceParticipant) =>
      (super.noSuchMethod(
        Invocation.method(
          #addRaceParticipant,
          [raceParticipant],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> updateRaceParticipant(
          _i6.RaceParticipant? raceParticipant) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateRaceParticipant,
          [raceParticipant],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> removeRaceParticipant(
          _i6.RaceParticipant? raceParticipant) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeRaceParticipant,
          [raceParticipant],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<_i6.RaceParticipant?> getRaceParticipant(
          _i6.RaceParticipant? raceParticipant) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRaceParticipant,
          [raceParticipant],
        ),
        returnValue: _i4.Future<_i6.RaceParticipant?>.value(),
      ) as _i4.Future<_i6.RaceParticipant?>);

  @override
  _i4.Future<List<_i6.RaceParticipant>> getRaceParticipants(int? raceId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRaceParticipants,
          [raceId],
        ),
        returnValue: _i4.Future<List<_i6.RaceParticipant>>.value(
            <_i6.RaceParticipant>[]),
      ) as _i4.Future<List<_i6.RaceParticipant>>);

  @override
  _i4.Future<_i6.RaceParticipant?> getRaceParticipantByBib(
    int? raceId,
    String? bibNumber,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRaceParticipantByBib,
          [
            raceId,
            bibNumber,
          ],
        ),
        returnValue: _i4.Future<_i6.RaceParticipant?>.value(),
      ) as _i4.Future<_i6.RaceParticipant?>);

  @override
  _i4.Future<List<_i6.RaceParticipant>> getRaceParticipantsByBibs(
    int? raceId,
    List<String>? bibNumbers,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRaceParticipantsByBibs,
          [
            raceId,
            bibNumbers,
          ],
        ),
        returnValue: _i4.Future<List<_i6.RaceParticipant>>.value(
            <_i6.RaceParticipant>[]),
      ) as _i4.Future<List<_i6.RaceParticipant>>);

  @override
  _i4.Future<List<_i6.RaceParticipant>> searchRaceParticipants(
    int? raceId,
    String? query, [
    String? searchParameter = 'all',
  ]) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchRaceParticipants,
          [
            raceId,
            query,
            searchParameter,
          ],
        ),
        returnValue: _i4.Future<List<_i6.RaceParticipant>>.value(
            <_i6.RaceParticipant>[]),
      ) as _i4.Future<List<_i6.RaceParticipant>>);

  @override
  _i4.Future<void> saveRaceResults(
    int? raceId,
    List<_i6.RaceResult>? results,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveRaceResults,
          [
            raceId,
            results,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> addRaceResult(_i6.RaceResult? result) => (super.noSuchMethod(
        Invocation.method(
          #addRaceResult,
          [result],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<_i6.RaceResult?> getRaceResult(_i6.RaceResult? raceResult) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRaceResult,
          [raceResult],
        ),
        returnValue: _i4.Future<_i6.RaceResult?>.value(),
      ) as _i4.Future<_i6.RaceResult?>);

  @override
  _i4.Future<List<_i6.RaceResult>> getRaceResults(int? raceId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRaceResults,
          [raceId],
        ),
        returnValue: _i4.Future<List<_i6.RaceResult>>.value(<_i6.RaceResult>[]),
      ) as _i4.Future<List<_i6.RaceResult>>);

  @override
  _i4.Future<void> updateRaceResult(_i6.RaceResult? raceResult) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateRaceResult,
          [raceResult],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> deleteRaceResult(_i6.RaceResult? raceResult) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteRaceResult,
          [raceResult],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<String> getRaceFlowState(int? raceId) => (super.noSuchMethod(
        Invocation.method(
          #getRaceFlowState,
          [raceId],
        ),
        returnValue: _i4.Future<String>.value(_i7.dummyValue<String>(
          this,
          Invocation.method(
            #getRaceFlowState,
            [raceId],
          ),
        )),
      ) as _i4.Future<String>);

  @override
  _i4.Future<void> updateRaceFlowState(
    int? raceId,
    String? flowState,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateRaceFlowState,
          [
            raceId,
            flowState,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<Map<String, List<dynamic>>> quickSearch(String? query) =>
      (super.noSuchMethod(
        Invocation.method(
          #quickSearch,
          [query],
        ),
        returnValue: _i4.Future<Map<String, List<dynamic>>>.value(
            <String, List<dynamic>>{}),
      ) as _i4.Future<Map<String, List<dynamic>>>);

  @override
  _i4.Future<String> getRaceState(int? raceId) => (super.noSuchMethod(
        Invocation.method(
          #getRaceState,
          [raceId],
        ),
        returnValue: _i4.Future<String>.value(_i7.dummyValue<String>(
          this,
          Invocation.method(
            #getRaceState,
            [raceId],
          ),
        )),
      ) as _i4.Future<String>);

  @override
  _i4.Future<void> clearAllData() => (super.noSuchMethod(
        Invocation.method(
          #clearAllData,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> clearRaceData(int? raceId) => (super.noSuchMethod(
        Invocation.method(
          #clearRaceData,
          [raceId],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> deleteAllRaces() => (super.noSuchMethod(
        Invocation.method(
          #deleteAllRaces,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> deleteAllRaceRunners(int? raceId) => (super.noSuchMethod(
        Invocation.method(
          #deleteAllRaceRunners,
          [raceId],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> deleteDatabase() => (super.noSuchMethod(
        Invocation.method(
          #deleteDatabase,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> close() => (super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> deleteRunnerEverywhere(int? runnerId) => (super.noSuchMethod(
        Invocation.method(
          #deleteRunnerEverywhere,
          [runnerId],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<List<_i6.Runner>> getRunnersByBibAll(String? bib) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRunnersByBibAll,
          [bib],
        ),
        returnValue: _i4.Future<List<_i6.Runner>>.value(<_i6.Runner>[]),
      ) as _i4.Future<List<_i6.Runner>>);
}

/// A class which mocks [IRemoteApiClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockIRemoteApiClient extends _i1.Mock implements _i8.IRemoteApiClient {
  MockIRemoteApiClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.SupabaseClient get client => (super.noSuchMethod(
        Invocation.getter(#client),
        returnValue: _FakeSupabaseClient_1(
          this,
          Invocation.getter(#client),
        ),
      ) as _i3.SupabaseClient);

  @override
  bool get isInitialized => (super.noSuchMethod(
        Invocation.getter(#isInitialized),
        returnValue: false,
      ) as bool);

  @override
  _i4.Future<void> init() => (super.noSuchMethod(
        Invocation.method(
          #init,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}

/// A class which mocks [IAuthService].
///
/// See the documentation for Mockito's code generation for more information.
class MockIAuthService extends _i1.Mock implements _i9.IAuthService {
  MockIAuthService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isSignedIn => (super.noSuchMethod(
        Invocation.getter(#isSignedIn),
        returnValue: false,
      ) as bool);
}

/// A class which mocks [Database].
///
/// See the documentation for Mockito's code generation for more information.
class MockDatabase extends _i1.Mock implements _i2.Database {
  MockDatabase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get path => (super.noSuchMethod(
        Invocation.getter(#path),
        returnValue: _i7.dummyValue<String>(
          this,
          Invocation.getter(#path),
        ),
      ) as String);

  @override
  bool get isOpen => (super.noSuchMethod(
        Invocation.getter(#isOpen),
        returnValue: false,
      ) as bool);

  @override
  _i2.Database get database => (super.noSuchMethod(
        Invocation.getter(#database),
        returnValue: _FakeDatabase_0(
          this,
          Invocation.getter(#database),
        ),
      ) as _i2.Database);

  @override
  _i4.Future<void> close() => (super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<T> transaction<T>(
    _i4.Future<T> Function(_i2.Transaction)? action, {
    bool? exclusive,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #transaction,
          [action],
          {#exclusive: exclusive},
        ),
        returnValue: _i7.ifNotNull(
              _i7.dummyValueOrNull<T>(
                this,
                Invocation.method(
                  #transaction,
                  [action],
                  {#exclusive: exclusive},
                ),
              ),
              (T v) => _i4.Future<T>.value(v),
            ) ??
            _FakeFuture_2<T>(
              this,
              Invocation.method(
                #transaction,
                [action],
                {#exclusive: exclusive},
              ),
            ),
      ) as _i4.Future<T>);

  @override
  _i4.Future<T> readTransaction<T>(
          _i4.Future<T> Function(_i2.Transaction)? action) =>
      (super.noSuchMethod(
        Invocation.method(
          #readTransaction,
          [action],
        ),
        returnValue: _i7.ifNotNull(
              _i7.dummyValueOrNull<T>(
                this,
                Invocation.method(
                  #readTransaction,
                  [action],
                ),
              ),
              (T v) => _i4.Future<T>.value(v),
            ) ??
            _FakeFuture_2<T>(
              this,
              Invocation.method(
                #readTransaction,
                [action],
              ),
            ),
      ) as _i4.Future<T>);

  @override
  _i4.Future<T> devInvokeMethod<T>(
    String? method, [
    Object? arguments,
  ]) =>
      (super.noSuchMethod(
        Invocation.method(
          #devInvokeMethod,
          [
            method,
            arguments,
          ],
        ),
        returnValue: _i7.ifNotNull(
              _i7.dummyValueOrNull<T>(
                this,
                Invocation.method(
                  #devInvokeMethod,
                  [
                    method,
                    arguments,
                  ],
                ),
              ),
              (T v) => _i4.Future<T>.value(v),
            ) ??
            _FakeFuture_2<T>(
              this,
              Invocation.method(
                #devInvokeMethod,
                [
                  method,
                  arguments,
                ],
              ),
            ),
      ) as _i4.Future<T>);

  @override
  _i4.Future<T> devInvokeSqlMethod<T>(
    String? method,
    String? sql, [
    List<Object?>? arguments,
  ]) =>
      (super.noSuchMethod(
        Invocation.method(
          #devInvokeSqlMethod,
          [
            method,
            sql,
            arguments,
          ],
        ),
        returnValue: _i7.ifNotNull(
              _i7.dummyValueOrNull<T>(
                this,
                Invocation.method(
                  #devInvokeSqlMethod,
                  [
                    method,
                    sql,
                    arguments,
                  ],
                ),
              ),
              (T v) => _i4.Future<T>.value(v),
            ) ??
            _FakeFuture_2<T>(
              this,
              Invocation.method(
                #devInvokeSqlMethod,
                [
                  method,
                  sql,
                  arguments,
                ],
              ),
            ),
      ) as _i4.Future<T>);

  @override
  _i4.Future<void> execute(
    String? sql, [
    List<Object?>? arguments,
  ]) =>
      (super.noSuchMethod(
        Invocation.method(
          #execute,
          [
            sql,
            arguments,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<int> rawInsert(
    String? sql, [
    List<Object?>? arguments,
  ]) =>
      (super.noSuchMethod(
        Invocation.method(
          #rawInsert,
          [
            sql,
            arguments,
          ],
        ),
        returnValue: _i4.Future<int>.value(0),
      ) as _i4.Future<int>);

  @override
  _i4.Future<int> insert(
    String? table,
    Map<String, Object?>? values, {
    String? nullColumnHack,
    _i2.ConflictAlgorithm? conflictAlgorithm,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #insert,
          [
            table,
            values,
          ],
          {
            #nullColumnHack: nullColumnHack,
            #conflictAlgorithm: conflictAlgorithm,
          },
        ),
        returnValue: _i4.Future<int>.value(0),
      ) as _i4.Future<int>);

  @override
  _i4.Future<List<Map<String, Object?>>> query(
    String? table, {
    bool? distinct,
    List<String>? columns,
    String? where,
    List<Object?>? whereArgs,
    String? groupBy,
    String? having,
    String? orderBy,
    int? limit,
    int? offset,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #query,
          [table],
          {
            #distinct: distinct,
            #columns: columns,
            #where: where,
            #whereArgs: whereArgs,
            #groupBy: groupBy,
            #having: having,
            #orderBy: orderBy,
            #limit: limit,
            #offset: offset,
          },
        ),
        returnValue: _i4.Future<List<Map<String, Object?>>>.value(
            <Map<String, Object?>>[]),
      ) as _i4.Future<List<Map<String, Object?>>>);

  @override
  _i4.Future<List<Map<String, Object?>>> rawQuery(
    String? sql, [
    List<Object?>? arguments,
  ]) =>
      (super.noSuchMethod(
        Invocation.method(
          #rawQuery,
          [
            sql,
            arguments,
          ],
        ),
        returnValue: _i4.Future<List<Map<String, Object?>>>.value(
            <Map<String, Object?>>[]),
      ) as _i4.Future<List<Map<String, Object?>>>);

  @override
  _i4.Future<_i2.QueryCursor> rawQueryCursor(
    String? sql,
    List<Object?>? arguments, {
    int? bufferSize,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #rawQueryCursor,
          [
            sql,
            arguments,
          ],
          {#bufferSize: bufferSize},
        ),
        returnValue: _i4.Future<_i2.QueryCursor>.value(_FakeQueryCursor_3(
          this,
          Invocation.method(
            #rawQueryCursor,
            [
              sql,
              arguments,
            ],
            {#bufferSize: bufferSize},
          ),
        )),
      ) as _i4.Future<_i2.QueryCursor>);

  @override
  _i4.Future<_i2.QueryCursor> queryCursor(
    String? table, {
    bool? distinct,
    List<String>? columns,
    String? where,
    List<Object?>? whereArgs,
    String? groupBy,
    String? having,
    String? orderBy,
    int? limit,
    int? offset,
    int? bufferSize,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #queryCursor,
          [table],
          {
            #distinct: distinct,
            #columns: columns,
            #where: where,
            #whereArgs: whereArgs,
            #groupBy: groupBy,
            #having: having,
            #orderBy: orderBy,
            #limit: limit,
            #offset: offset,
            #bufferSize: bufferSize,
          },
        ),
        returnValue: _i4.Future<_i2.QueryCursor>.value(_FakeQueryCursor_3(
          this,
          Invocation.method(
            #queryCursor,
            [table],
            {
              #distinct: distinct,
              #columns: columns,
              #where: where,
              #whereArgs: whereArgs,
              #groupBy: groupBy,
              #having: having,
              #orderBy: orderBy,
              #limit: limit,
              #offset: offset,
              #bufferSize: bufferSize,
            },
          ),
        )),
      ) as _i4.Future<_i2.QueryCursor>);

  @override
  _i4.Future<int> rawUpdate(
    String? sql, [
    List<Object?>? arguments,
  ]) =>
      (super.noSuchMethod(
        Invocation.method(
          #rawUpdate,
          [
            sql,
            arguments,
          ],
        ),
        returnValue: _i4.Future<int>.value(0),
      ) as _i4.Future<int>);

  @override
  _i4.Future<int> update(
    String? table,
    Map<String, Object?>? values, {
    String? where,
    List<Object?>? whereArgs,
    _i2.ConflictAlgorithm? conflictAlgorithm,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #update,
          [
            table,
            values,
          ],
          {
            #where: where,
            #whereArgs: whereArgs,
            #conflictAlgorithm: conflictAlgorithm,
          },
        ),
        returnValue: _i4.Future<int>.value(0),
      ) as _i4.Future<int>);

  @override
  _i4.Future<int> rawDelete(
    String? sql, [
    List<Object?>? arguments,
  ]) =>
      (super.noSuchMethod(
        Invocation.method(
          #rawDelete,
          [
            sql,
            arguments,
          ],
        ),
        returnValue: _i4.Future<int>.value(0),
      ) as _i4.Future<int>);

  @override
  _i4.Future<int> delete(
    String? table, {
    String? where,
    List<Object?>? whereArgs,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #delete,
          [table],
          {
            #where: where,
            #whereArgs: whereArgs,
          },
        ),
        returnValue: _i4.Future<int>.value(0),
      ) as _i4.Future<int>);

  @override
  _i2.Batch batch() => (super.noSuchMethod(
        Invocation.method(
          #batch,
          [],
        ),
        returnValue: _FakeBatch_4(
          this,
          Invocation.method(
            #batch,
            [],
          ),
        ),
      ) as _i2.Batch);
}

/// A class which mocks [SupabaseClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockSupabaseClient extends _i1.Mock implements _i3.SupabaseClient {
  MockSupabaseClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.FunctionsClient get functions => (super.noSuchMethod(
        Invocation.getter(#functions),
        returnValue: _FakeFunctionsClient_5(
          this,
          Invocation.getter(#functions),
        ),
      ) as _i3.FunctionsClient);

  @override
  _i3.SupabaseStorageClient get storage => (super.noSuchMethod(
        Invocation.getter(#storage),
        returnValue: _FakeSupabaseStorageClient_6(
          this,
          Invocation.getter(#storage),
        ),
      ) as _i3.SupabaseStorageClient);

  @override
  _i3.RealtimeClient get realtime => (super.noSuchMethod(
        Invocation.getter(#realtime),
        returnValue: _FakeRealtimeClient_7(
          this,
          Invocation.getter(#realtime),
        ),
      ) as _i3.RealtimeClient);

  @override
  _i3.PostgrestClient get rest => (super.noSuchMethod(
        Invocation.getter(#rest),
        returnValue: _FakePostgrestClient_8(
          this,
          Invocation.getter(#rest),
        ),
      ) as _i3.PostgrestClient);

  @override
  Map<String, String> get headers => (super.noSuchMethod(
        Invocation.getter(#headers),
        returnValue: <String, String>{},
      ) as Map<String, String>);

  @override
  _i3.GoTrueClient get auth => (super.noSuchMethod(
        Invocation.getter(#auth),
        returnValue: _FakeGoTrueClient_9(
          this,
          Invocation.getter(#auth),
        ),
      ) as _i3.GoTrueClient);

  @override
  set functions(_i3.FunctionsClient? value) => super.noSuchMethod(
        Invocation.setter(
          #functions,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set storage(_i3.SupabaseStorageClient? value) => super.noSuchMethod(
        Invocation.setter(
          #storage,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set realtime(_i3.RealtimeClient? value) => super.noSuchMethod(
        Invocation.setter(
          #realtime,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set rest(_i3.PostgrestClient? value) => super.noSuchMethod(
        Invocation.setter(
          #rest,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set headers(Map<String, String>? headers) => super.noSuchMethod(
        Invocation.setter(
          #headers,
          headers,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i3.SupabaseQueryBuilder from(String? table) => (super.noSuchMethod(
        Invocation.method(
          #from,
          [table],
        ),
        returnValue: _FakeSupabaseQueryBuilder_10(
          this,
          Invocation.method(
            #from,
            [table],
          ),
        ),
      ) as _i3.SupabaseQueryBuilder);

  @override
  _i3.SupabaseQuerySchema schema(String? schema) => (super.noSuchMethod(
        Invocation.method(
          #schema,
          [schema],
        ),
        returnValue: _FakeSupabaseQuerySchema_11(
          this,
          Invocation.method(
            #schema,
            [schema],
          ),
        ),
      ) as _i3.SupabaseQuerySchema);

  @override
  _i3.PostgrestFilterBuilder<T> rpc<T>(
    String? fn, {
    Map<String, dynamic>? params,
    dynamic get = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #rpc,
          [fn],
          {
            #params: params,
            #get: get,
          },
        ),
        returnValue: _FakePostgrestFilterBuilder_12<T>(
          this,
          Invocation.method(
            #rpc,
            [fn],
            {
              #params: params,
              #get: get,
            },
          ),
        ),
      ) as _i3.PostgrestFilterBuilder<T>);

  @override
  _i3.RealtimeChannel channel(
    String? name, {
    _i3.RealtimeChannelConfig? opts = const _i3.RealtimeChannelConfig(),
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #channel,
          [name],
          {#opts: opts},
        ),
        returnValue: _FakeRealtimeChannel_13(
          this,
          Invocation.method(
            #channel,
            [name],
            {#opts: opts},
          ),
        ),
      ) as _i3.RealtimeChannel);

  @override
  List<_i3.RealtimeChannel> getChannels() => (super.noSuchMethod(
        Invocation.method(
          #getChannels,
          [],
        ),
        returnValue: <_i3.RealtimeChannel>[],
      ) as List<_i3.RealtimeChannel>);

  @override
  _i4.Future<String> removeChannel(_i3.RealtimeChannel? channel) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeChannel,
          [channel],
        ),
        returnValue: _i4.Future<String>.value(_i7.dummyValue<String>(
          this,
          Invocation.method(
            #removeChannel,
            [channel],
          ),
        )),
      ) as _i4.Future<String>);

  @override
  _i4.Future<List<String>> removeAllChannels() => (super.noSuchMethod(
        Invocation.method(
          #removeAllChannels,
          [],
        ),
        returnValue: _i4.Future<List<String>>.value(<String>[]),
      ) as _i4.Future<List<String>>);

  @override
  _i4.Future<void> dispose() => (super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}
