// Mocks generated by Mockito 5.4.6 from annotations
// in xceleration/test/widget/assistant/finish_line_roles/verifier/verifier_screen_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;
import 'dart:ui' as _i9;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;
import 'package:xceleration/assistant/finish_line_roles/shared/models/verifier_entry.dart'
    as _i3;
import 'package:xceleration/assistant/finish_line_roles/shared/peer_connection/p2p_session_service.dart'
    as _i8;
import 'package:xceleration/assistant/finish_line_roles/verifier/controller/verifier_controller.dart'
    as _i2;
import 'package:xceleration/assistant/shared/models/race_record.dart' as _i4;
import 'package:xceleration/core/result.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [VerifierController].
///
/// See the documentation for Mockito's code generation for more information.
class MockVerifierController extends _i1.Mock
    implements _i2.VerifierController {
  MockVerifierController() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<_i3.VerifierEntry> get entries => (super.noSuchMethod(
        Invocation.getter(#entries),
        returnValue: <_i3.VerifierEntry>[],
      ) as List<_i3.VerifierEntry>);

  @override
  bool get isInRace => (super.noSuchMethod(
        Invocation.getter(#isInRace),
        returnValue: false,
      ) as bool);

  @override
  List<_i4.RaceRecord> get races => (super.noSuchMethod(
        Invocation.getter(#races),
        returnValue: <_i4.RaceRecord>[],
      ) as List<_i4.RaceRecord>);

  @override
  int get confirmed => (super.noSuchMethod(
        Invocation.getter(#confirmed),
        returnValue: 0,
      ) as int);

  @override
  int get wrong => (super.noSuchMethod(
        Invocation.getter(#wrong),
        returnValue: 0,
      ) as int);

  @override
  int get skipped => (super.noSuchMethod(
        Invocation.getter(#skipped),
        returnValue: 0,
      ) as int);

  @override
  int get pending => (super.noSuchMethod(
        Invocation.getter(#pending),
        returnValue: 0,
      ) as int);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  _i5.Future<void> initialize() => (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<_i6.Result<void>> processLoadedRaceData(String? data) =>
      (super.noSuchMethod(
        Invocation.method(
          #processLoadedRaceData,
          [data],
        ),
        returnValue:
            _i5.Future<_i6.Result<void>>.value(_i7.dummyValue<_i6.Result<void>>(
          this,
          Invocation.method(
            #processLoadedRaceData,
            [data],
          ),
        )),
      ) as _i5.Future<_i6.Result<void>>);

  @override
  _i5.Future<void> joinRace({required int? raceId}) => (super.noSuchMethod(
        Invocation.method(
          #joinRace,
          [],
          {#raceId: raceId},
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  void verify(int? id) => super.noSuchMethod(
        Invocation.method(
          #verify,
          [id],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void flag(int? id) => super.noSuchMethod(
        Invocation.method(
          #flag,
          [id],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void skip(int? id) => super.noSuchMethod(
        Invocation.method(
          #skip,
          [id],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void undo(int? id) => super.noSuchMethod(
        Invocation.method(
          #undo,
          [id],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void leaveRace() => super.noSuchMethod(
        Invocation.method(
          #leaveRace,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i5.Future<void> deleteRaceFromLobby(int? raceId) => (super.noSuchMethod(
        Invocation.method(
          #deleteRaceFromLobby,
          [raceId],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  void attachSession(_i8.P2PSessionService? session) => super.noSuchMethod(
        Invocation.method(
          #attachSession,
          [session],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addListener(_i9.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i9.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
