// Mocks generated by Mockito 5.4.6 from annotations
// in xceleration/test/widget/assistant/finish_line_roles/verifier/verifier_screen_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:ui' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:xceleration/assistant/finish_line_roles/shared/models/verifier_entry.dart'
    as _i3;
import 'package:xceleration/assistant/finish_line_roles/verifier/controller/verifier_controller.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [VerifierController].
///
/// See the documentation for Mockito's code generation for more information.
class MockVerifierController extends _i1.Mock
    implements _i2.VerifierController {
  MockVerifierController() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<_i3.VerifierEntry> get entries => (super.noSuchMethod(
        Invocation.getter(#entries),
        returnValue: <_i3.VerifierEntry>[],
      ) as List<_i3.VerifierEntry>);

  @override
  bool get isInRace => (super.noSuchMethod(
        Invocation.getter(#isInRace),
        returnValue: false,
      ) as bool);

  @override
  int get confirmed => (super.noSuchMethod(
        Invocation.getter(#confirmed),
        returnValue: 0,
      ) as int);

  @override
  int get wrong => (super.noSuchMethod(
        Invocation.getter(#wrong),
        returnValue: 0,
      ) as int);

  @override
  int get skipped => (super.noSuchMethod(
        Invocation.getter(#skipped),
        returnValue: 0,
      ) as int);

  @override
  int get pending => (super.noSuchMethod(
        Invocation.getter(#pending),
        returnValue: 0,
      ) as int);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  void initialize() => super.noSuchMethod(
        Invocation.method(
          #initialize,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void joinRace() => super.noSuchMethod(
        Invocation.method(
          #joinRace,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void verify(int? id) => super.noSuchMethod(
        Invocation.method(
          #verify,
          [id],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void flag(int? id) => super.noSuchMethod(
        Invocation.method(
          #flag,
          [id],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void skip(int? id) => super.noSuchMethod(
        Invocation.method(
          #skip,
          [id],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void undo(int? id) => super.noSuchMethod(
        Invocation.method(
          #undo,
          [id],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void leaveRace() => super.noSuchMethod(
        Invocation.method(
          #leaveRace,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addListener(_i4.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i4.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
