// Mocks generated by Mockito 5.4.6 from annotations
// in xceleration/test/unit/coach/races_screen/services/races_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i5;
import 'package:xceleration/core/repositories/i_race_repository.dart' as _i2;
import 'package:xceleration/shared/models/database/base_models.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [IRaceRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockIRaceRepository extends _i1.Mock implements _i2.IRaceRepository {
  MockIRaceRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<int> createRace(_i4.Race? race) => (super.noSuchMethod(
        Invocation.method(
          #createRace,
          [race],
        ),
        returnValue: _i3.Future<int>.value(0),
      ) as _i3.Future<int>);

  @override
  _i3.Future<_i4.Race?> getRace(int? raceId) => (super.noSuchMethod(
        Invocation.method(
          #getRace,
          [raceId],
        ),
        returnValue: _i3.Future<_i4.Race?>.value(),
      ) as _i3.Future<_i4.Race?>);

  @override
  _i3.Future<List<_i4.Race>> getAllRaces() => (super.noSuchMethod(
        Invocation.method(
          #getAllRaces,
          [],
        ),
        returnValue: _i3.Future<List<_i4.Race>>.value(<_i4.Race>[]),
      ) as _i3.Future<List<_i4.Race>>);

  @override
  _i3.Future<void> updateRace(_i4.Race? race) => (super.noSuchMethod(
        Invocation.method(
          #updateRace,
          [race],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> deleteRace(int? raceId) => (super.noSuchMethod(
        Invocation.method(
          #deleteRace,
          [raceId],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> addTeamParticipantToRace(
          _i4.TeamParticipant? teamParticipant) =>
      (super.noSuchMethod(
        Invocation.method(
          #addTeamParticipantToRace,
          [teamParticipant],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> removeTeamParticipantFromRace(
          _i4.TeamParticipant? teamParticipant) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeTeamParticipantFromRace,
          [teamParticipant],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<_i4.Team?> getRaceTeamParticipant(
          _i4.TeamParticipant? teamParticipant) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRaceTeamParticipant,
          [teamParticipant],
        ),
        returnValue: _i3.Future<_i4.Team?>.value(),
      ) as _i3.Future<_i4.Team?>);

  @override
  _i3.Future<List<_i4.Team>> getRaceTeams(int? raceId) => (super.noSuchMethod(
        Invocation.method(
          #getRaceTeams,
          [raceId],
        ),
        returnValue: _i3.Future<List<_i4.Team>>.value(<_i4.Team>[]),
      ) as _i3.Future<List<_i4.Team>>);

  @override
  _i3.Future<void> addRaceParticipant(_i4.RaceParticipant? raceParticipant) =>
      (super.noSuchMethod(
        Invocation.method(
          #addRaceParticipant,
          [raceParticipant],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> updateRaceParticipant(
          _i4.RaceParticipant? raceParticipant) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateRaceParticipant,
          [raceParticipant],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> removeRaceParticipant(
          _i4.RaceParticipant? raceParticipant) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeRaceParticipant,
          [raceParticipant],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<_i4.RaceParticipant?> getRaceParticipant(
          _i4.RaceParticipant? raceParticipant) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRaceParticipant,
          [raceParticipant],
        ),
        returnValue: _i3.Future<_i4.RaceParticipant?>.value(),
      ) as _i3.Future<_i4.RaceParticipant?>);

  @override
  _i3.Future<List<_i4.RaceParticipant>> getRaceParticipants(int? raceId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRaceParticipants,
          [raceId],
        ),
        returnValue: _i3.Future<List<_i4.RaceParticipant>>.value(
            <_i4.RaceParticipant>[]),
      ) as _i3.Future<List<_i4.RaceParticipant>>);

  @override
  _i3.Future<_i4.RaceParticipant?> getRaceParticipantByBib(
    int? raceId,
    String? bibNumber,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRaceParticipantByBib,
          [
            raceId,
            bibNumber,
          ],
        ),
        returnValue: _i3.Future<_i4.RaceParticipant?>.value(),
      ) as _i3.Future<_i4.RaceParticipant?>);

  @override
  _i3.Future<List<_i4.RaceParticipant>> getRaceParticipantsByBibs(
    int? raceId,
    List<String>? bibNumbers,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRaceParticipantsByBibs,
          [
            raceId,
            bibNumbers,
          ],
        ),
        returnValue: _i3.Future<List<_i4.RaceParticipant>>.value(
            <_i4.RaceParticipant>[]),
      ) as _i3.Future<List<_i4.RaceParticipant>>);

  @override
  _i3.Future<List<_i4.RaceParticipant>> searchRaceParticipants(
    int? raceId,
    String? query, [
    String? searchParameter = 'all',
  ]) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchRaceParticipants,
          [
            raceId,
            query,
            searchParameter,
          ],
        ),
        returnValue: _i3.Future<List<_i4.RaceParticipant>>.value(
            <_i4.RaceParticipant>[]),
      ) as _i3.Future<List<_i4.RaceParticipant>>);

  @override
  _i3.Future<String> getRaceFlowState(int? raceId) => (super.noSuchMethod(
        Invocation.method(
          #getRaceFlowState,
          [raceId],
        ),
        returnValue: _i3.Future<String>.value(_i5.dummyValue<String>(
          this,
          Invocation.method(
            #getRaceFlowState,
            [raceId],
          ),
        )),
      ) as _i3.Future<String>);

  @override
  _i3.Future<void> updateRaceFlowState(
    int? raceId,
    String? flowState,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateRaceFlowState,
          [
            raceId,
            flowState,
          ],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> updateRaceParticipantTeam({
    required int? raceId,
    required int? runnerId,
    required int? newTeamId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateRaceParticipantTeam,
          [],
          {
            #raceId: raceId,
            #runnerId: runnerId,
            #newTeamId: newTeamId,
          },
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> updateRunnerWithTeams({
    required _i4.Runner? runner,
    int? newTeamId,
    int? raceIdForTeamUpdate,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateRunnerWithTeams,
          [],
          {
            #runner: runner,
            #newTeamId: newTeamId,
            #raceIdForTeamUpdate: raceIdForTeamUpdate,
          },
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}
