name: CI

on:
  pull_request:
    branches: [ dev ]

jobs:

  lint_and_format:
    name: Lint and Format
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get changed Dart files
        id: dart-changes
        uses: tj-actions/changed-files@v39
        with:
          files: |
            **/*.dart

      - name: Skip formatting (no Dart changes)
        if: steps.dart-changes.outputs.any_changed == 'false'
        run: |
          echo "⏭️ Skipping formatting - no Dart files changed"
          echo "✅ Formatting step completed (skipped)"

      - name: Cache Flutter dependencies
        if: steps.dart-changes.outputs.any_changed == 'true'
        uses: actions/cache@v4
        with:
          path: |
            ~/.pub-cache
            .dart_tool
          key: ${{ runner.os }}-flutter-deps-${{ hashFiles('**/pubspec.lock') }}
          restore-keys: |
            ${{ runner.os }}-flutter-deps-

      - name: Setup Flutter
        if: steps.dart-changes.outputs.any_changed == 'true'
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.5'
          channel: 'stable'
          cache: true

      - name: Get Flutter dependencies
        if: steps.dart-changes.outputs.any_changed == 'true'
        run: flutter pub get

      - name: Check formatting
        if: steps.dart-changes.outputs.any_changed == 'true'
        run: dart format --output=none --set-exit-if-changed .

  analyze:
    name: Analyze Code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get changed Dart files
        id: dart-changes
        uses: tj-actions/changed-files@v39
        with:
          files: |
            **/*.dart

      - name: Skip analysis (no Dart changes)
        if: steps.dart-changes.outputs.any_changed == 'false'
        run: |
          echo "⏭️ Skipping analysis - no Dart files changed"
          echo "✅ Analysis step completed (skipped)"

      - name: Cache Flutter dependencies
        if: steps.dart-changes.outputs.any_changed == 'true'
        uses: actions/cache@v4
        with:
          path: |
            ~/.pub-cache
            .dart_tool
          key: ${{ runner.os }}-flutter-deps-${{ hashFiles('**/pubspec.lock') }}
          restore-keys: |
            ${{ runner.os }}-flutter-deps-

      - name: Setup Flutter
        if: steps.dart-changes.outputs.any_changed == 'true'
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.5'
          channel: 'stable'
          cache: true

      - name: Get Flutter dependencies
        if: steps.dart-changes.outputs.any_changed == 'true'
        run: flutter pub get

      - name: Create .env file for analyzer
        if: steps.dart-changes.outputs.any_changed == 'true'
        run: touch .env

      - name: Analyze changed files only (faster)
        if: steps.dart-changes.outputs.any_changed == 'true'
        run: |
          echo "🔍 Analyzing only changed Dart files for faster feedback..."
          
          # Analyze only changed files
          changed_files="${{ steps.dart-changes.outputs.all_changed_files }}"
          for file in $changed_files; do
            echo "  Analyzing: $file"
            flutter analyze --fatal-infos --fatal-warnings "$file" || exit 1
          done
          
          echo "✅ Incremental analysis complete!"

  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get changed Dart files
        id: dart-changes
        uses: tj-actions/changed-files@v39
        with:
          files: |
            **/*.dart

      - name: Skip tests (no Dart changes)
        if: steps.dart-changes.outputs.any_changed == 'false'
        run: |
          echo "⏭️ Skipping tests - no Dart files changed"
          echo "✅ Test step completed (skipped)"

      - name: Cache Flutter dependencies
        if: steps.dart-changes.outputs.any_changed == 'true'
        uses: actions/cache@v4
        with:
          path: |
            ~/.pub-cache
            .dart_tool
          key: ${{ runner.os }}-flutter-deps-${{ hashFiles('**/pubspec.lock') }}
          restore-keys: |
            ${{ runner.os }}-flutter-deps-

      - name: Setup Flutter
        if: steps.dart-changes.outputs.any_changed == 'true'
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.5'
          channel: 'stable'
          cache: true

      - name: Get Flutter dependencies
        if: steps.dart-changes.outputs.any_changed == 'true'
        run: flutter pub get

      - name: Create .env file for tests
        if: steps.dart-changes.outputs.any_changed == 'true'
        run: touch .env

      - name: Run unit and widget tests
        if: steps.dart-changes.outputs.any_changed == 'true'
        run: flutter test --concurrency=4

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: [lint_and_format, analyze, test]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get changed build-relevant files
        id: build-changes
        uses: tj-actions/changed-files@v39
        with:
          files: |
            lib/**
            assets/**
            pubspec.yaml
            pubspec.lock
            analysis_options.yaml

      - name: Skip build (no relevant changes)
        if: steps.build-changes.outputs.any_changed == 'false'
        run: |
          echo "⏭️ Skipping build - no build-relevant files changed"
          echo "✅ Build step completed (skipped)"

      - name: Cache Flutter dependencies
        if: steps.build-changes.outputs.any_changed == 'true'
        uses: actions/cache@v4
        with:
          path: |
            ~/.pub-cache
            .dart_tool
          key: ${{ runner.os }}-flutter-deps-${{ hashFiles('**/pubspec.lock') }}
          restore-keys: |
            ${{ runner.os }}-flutter-deps-

      - name: Setup Flutter
        if: steps.build-changes.outputs.any_changed == 'true'
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.5'
          channel: 'stable'
          cache: true

      - name: Get Flutter dependencies
        if: steps.build-changes.outputs.any_changed == 'true'
        run: flutter pub get

      - name: Create .env file
        if: steps.build-changes.outputs.any_changed == 'true' && github.event.pull_request.head.repo.full_name == github.repository
        run: echo "${{ secrets.DOTENV }}" > .env

      - name: Create empty .env file for forks
        if: steps.build-changes.outputs.any_changed == 'true' && github.event.pull_request.head.repo.full_name != github.repository
        run: touch .env

      - name: Cache build artifacts
        if: steps.build-changes.outputs.any_changed == 'true'
        id: build-cache
        uses: actions/cache@v4
        with:
          path: |
            build/
            .dart_tool/build/
          key: build-${{ hashFiles('pubspec.lock') }}-${{ hashFiles('lib/**', 'assets/**', 'analysis_options.yaml') }}-${{ runner.os }}
          restore-keys: |
            build-${{ hashFiles('pubspec.lock') }}-${{ runner.os }}-
            build-${{ runner.os }}-

      - name: Build from cache (if available)
        if: steps.build-changes.outputs.any_changed == 'true' && steps.build-cache.outputs.cache-hit == 'true'
        run: |
          echo "✅ Build artifacts restored from cache!"
          echo "📦 Skipping build - no relevant changes detected"
          ls -la build/ || echo "Build directory structure:"

      - name: Build from source (cache miss)
        if: steps.build-changes.outputs.any_changed == 'true' && steps.build-cache.outputs.cache-hit != 'true'
        run: |
          echo "🔨 Building from source..."
          flutter build bundle
          echo "✅ Build complete - artifacts cached for future runs" 