name: Deploy

on:
  pull_request:
    types: [closed]
    branches: [ main ]

jobs:
  deploy-app:
    name: Deploy Application
    if: github.event.pull_request.merged == true && github.event.pull_request.head.ref == 'dev'
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.5'
          cache: true

      - name: Set up Ruby and Bundler
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2.8'
          bundler-cache: true
          working-directory: ./ios

      - name: Create .env file
        run: echo "${{ secrets.DOTENV }}" > .env

      - name: Deploy to TestFlight via Fastlane
        working-directory: ./ios
        run: bundle exec fastlane deploy 