name: Flutter CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint-and-test:
    name: Lint, Format, and Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest]
        flutter-version: ['3.29.x']
        flutter-channel: ['stable']
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ matrix.flutter-version }}
          channel: ${{ matrix.flutter-channel }}
          cache: true
      
      - name: Install dependencies
        run: flutter pub get

      - name: Create a dummy .env file for tests
        run: touch .env
      
      # - name: Format code automatically
      #   run: dart format .
        
      
      # - name: Analyze project source
      #   run: flutter analyze --fatal-infos --fatal-warnings
      
      - name: Run unit and widget tests
        run: flutter test --coverage

      
      # Optional: Upload test coverage if you set up a coverage tool
      # - name: Upload coverage to Codecov
      #   uses: codecov/codecov-action@v3
      #   with:
      #     file: ./coverage/lcov.info
      
      # Optional: Check for outdated dependencies
      - name: Check for outdated dependencies
        run: flutter pub outdated
      
      # Optional: Run integration tests if you have them (disabled by default)
      # - name: Run integration tests
      #   run: flutter test integration_test

  build:
    name: Build on ${{ matrix.os }}
    needs: lint-and-test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest]
        flutter-version: ['3.29.x']
        flutter-channel: ['stable']
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ matrix.flutter-version }}
          channel: ${{ matrix.flutter-channel }}
          cache: true
      
      - name: Install dependencies
        run: flutter pub get

      - name: Create .env file
        run: |
          echo "GOOGLE_APP_ID=${{ secrets.GOOGLE_APP_ID }}" >> .env
          echo "GOOGLE_IOS_OAUTH_CLIENT_ID=${{ secrets.GOOGLE_IOS_OAUTH_CLIENT_ID }}" >> .env
          echo "GOOGLE_IOS_OAUTH_REVERSED_CLIENT_ID=${{ secrets.GOOGLE_IOS_OAUTH_REVERSED_CLIENT_ID }}" >> .env
          echo "GOOGLE_WEB_OAUTH_CLIENT_ID=${{ secrets.GOOGLE_WEB_OAUTH_CLIENT_ID }}" >> .env
          echo "GOOGLE_WEB_API_KEY=${{ secrets.GOOGLE_WEB_API_KEY }}" >> .env
          echo "SENTRY_DSN=${{ secrets.SENTRY_DSN }}" >> .env
          echo "WEB_ACCESS_TOKEN_API_ENDPOINT=${{ secrets.WEB_ACCESS_TOKEN_API_ENDPOINT }}" >> .env
          echo "GOOGLE_PICKER_URL=${{ secrets.GOOGLE_PICKER_URL }}" >> .env
      
      - name: Verify Build
        run: flutter build bundle
