name: Lint

on:
  pull_request:
    branches: [ dev, main ]

jobs:
  lint-and-format:
    name: Lint and Format Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.x'
          channel: 'stable'
          cache: true
      
      - name: Install dependencies
        run: flutter pub get

      - name: Create empty .env file for analyzer
        run: touch .env

      - name: Check formatting
        run: dart format --output=none --set-exit-if-changed .
      
      - name: Analyze project source
        run: flutter analyze --fatal-infos --fatal-warnings
        
      - name: Run unit and widget tests
        run: flutter test --coverage 